In [1]:
import pandas as pd
import os

In [2]:
import os

relative_path = r"..\..\DATASETS\ENRICHMENT DATASETS\Enrichment_Housing1Y2021.csv"

if os.path.exists(relative_path):
    print("The file exists at the specified path.")
else:
    print("The file does not exist at the specified path.")

The file exists at the specified path.

In [4]:
housingEnrichment= pd.read_csv(r"..\..\DATASETS\ENRICHMENT DATASETS\Enrichment_Housing1Y2021.csv", low_memory=False)
housingEnrichment

,GEO_ID,NAME,DP04_0001E,DP04_0001M,DP04_0002E,DP04_0002M,DP04_0003E,DP04_0003M,DP04_0004E,DP04_0004M,...,DP04_0061E,DP04_0061M,DP04_0076E,DP04_0076M,DP04_0077E,DP04_0077M,DP04_0078E,DP04_0078M,DP04_0079E,DP04_0079M
0,0500000US01003,"Baldwin County, Alabama",128533.0,889.0,94105.0,3462.0,34428.0,3410.0,1.4,0.9,...,21901.0,2769.0,94105,3462,92836,3510,1269,786,0,216
1,0500000US01015,"Calhoun County, Alabama",53211.0,656.0,44631.0,1889.0,8580.0,1750.0,1.6,1.5,...,13044.0,1906.0,44631,1889,43578,1946,760,538,293,329
2,0500000US01043,"Cullman County, Alabama",39465.0,186.0,35131.0,1361.0,4334.0,1350.0,1.8,2.2,...,12253.0,1563.0,35131,1361,34290,1401,587,395,254,283
3,0500000US01049,"DeKalb County, Alabama",30774.0,204.0,24979.0,1117.0,5795.0,1105.0,0.1,0.2,...,7828.0,1197.0,24979,1117,23889,1261,944,558,146,155
4,0500000US01051,"Elmore County, Alabama",37081.0,602.0,32108.0,1460.0,4973.0,1304.0,1.3,1.6,...,10731.0,1376.0,N,N,per,N,N,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
836,0500000US72113,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
837,0500000US72127,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
838,0500000US72135,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
839,0500000US72137,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
840,0500000US72139,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# reading two csv files
data1 = pd.read_csv(r"..\..\DATASETS\SUPER DATASETS\covidSuperDS.csv", low_memory=False)
data2= pd.read_csv(r"..\..\DATASETS\ENRICHMENT DATASETS\Enrichment_Housing1Y2021.csv", low_memory=False)

#getting the last 5 digits to match the countyfips in covidsuperdata
data2['countyFIPS'] = data2['GEO_ID'].str[-5:]
data2['countyFIPS'] = pd.to_numeric(data2['countyFIPS'])

# using merge function by setting 
output1 = pd.merge(data1, data2,
                   on= ('countyFIPS')
                   )
                   
#displaying result

output1.drop(output1.columns[output1.columns.str.contains('unnamed',case = False)],axis = 1, inplace = True)
output1 = output1.drop('NAME', axis=1)

output1

,countyFIPS,County Name,State,StateFIPS,Date,Number of Cases,Number of Deaths,population,GEO_ID,DP04_0001E,...,DP04_0061E,DP04_0061M,DP04_0076E,DP04_0076M,DP04_0077E,DP04_0077M,DP04_0078E,DP04_0078M,DP04_0079E,DP04_0079M
0,1003,Baldwin County,AL,1,2020-01-22,0,0,223234,0500000US01003,128533.0,...,21901.0,2769.0,94105,3462,92836,3510,1269,786,0,216
1,1003,Baldwin County,AL,1,2020-01-23,0,0,223234,0500000US01003,128533.0,...,21901.0,2769.0,94105,3462,92836,3510,1269,786,0,216
2,1003,Baldwin County,AL,1,2020-01-24,0,0,223234,0500000US01003,128533.0,...,21901.0,2769.0,94105,3462,92836,3510,1269,786,0,216
3,1003,Baldwin County,AL,1,2020-01-25,0,0,223234,0500000US01003,128533.0,...,21901.0,2769.0,94105,3462,92836,3510,1269,786,0,216
4,1003,Baldwin County,AL,1,2020-01-26,0,0,223234,0500000US01003,128533.0,...,21901.0,2769.0,94105,3462,92836,3510,1269,786,0,216
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
905525,56025,Natrona County,WY,56,2023-01-12,25636,302,79858,0500000US56025,37051.0,...,9390.0,1390.0,N,N,N,N,N,N,N,N
905526,56025,Natrona County,WY,56,2023-01-13,25636,302,79858,0500000US56025,37051.0,...,9390.0,1390.0,N,N,N,N,N,N,N,N
905527,56025,Natrona County,WY,56,2023-01-14,25636,302,79858,0500000US56025,37051.0,...,9390.0,1390.0,N,N,N,N,N,N,N,N
905528,56025,Natrona County,WY,56,2023-01-15,25636,302,79858,0500000US56025,37051.0,...,9390.0,1390.0,N,N,N,N,N,N,N,N
905529,56025,Natrona County,WY,56,2023-01-16,25636,302,79858,0500000US56025,37051.0,...,9390.0,1390.0,N,N,N,N,N,N,N,N

In [6]:
output1.to_csv(r"..\..\Member\AshritaD\EnrichmentSuperDataSet_Housing.csv", index = False)

In [7]:
output2= pd.read_csv(r"..\..\Member\AshritaD\EnrichmentSuperDataSet_Housing.csv", low_memory=False)
output2

,countyFIPS,County Name,State,StateFIPS,Date,Number of Cases,Number of Deaths,population,GEO_ID,DP04_0001E,...,DP04_0061E,DP04_0061M,DP04_0076E,DP04_0076M,DP04_0077E,DP04_0077M,DP04_0078E,DP04_0078M,DP04_0079E,DP04_0079M
0,1003,Baldwin County,AL,1,2020-01-22,0,0,223234,0500000US01003,128533.0,...,21901.0,2769.0,94105,3462,92836,3510,1269,786,0,216
1,1003,Baldwin County,AL,1,2020-01-23,0,0,223234,0500000US01003,128533.0,...,21901.0,2769.0,94105,3462,92836,3510,1269,786,0,216
2,1003,Baldwin County,AL,1,2020-01-24,0,0,223234,0500000US01003,128533.0,...,21901.0,2769.0,94105,3462,92836,3510,1269,786,0,216
3,1003,Baldwin County,AL,1,2020-01-25,0,0,223234,0500000US01003,128533.0,...,21901.0,2769.0,94105,3462,92836,3510,1269,786,0,216
4,1003,Baldwin County,AL,1,2020-01-26,0,0,223234,0500000US01003,128533.0,...,21901.0,2769.0,94105,3462,92836,3510,1269,786,0,216
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
905525,56025,Natrona County,WY,56,2023-01-12,25636,302,79858,0500000US56025,37051.0,...,9390.0,1390.0,N,N,N,N,N,N,N,N
905526,56025,Natrona County,WY,56,2023-01-13,25636,302,79858,0500000US56025,37051.0,...,9390.0,1390.0,N,N,N,N,N,N,N,N
905527,56025,Natrona County,WY,56,2023-01-14,25636,302,79858,0500000US56025,37051.0,...,9390.0,1390.0,N,N,N,N,N,N,N,N
905528,56025,Natrona County,WY,56,2023-01-15,25636,302,79858,0500000US56025,37051.0,...,9390.0,1390.0,N,N,N,N,N,N,N,N
905529,56025,Natrona County,WY,56,2023-01-16,25636,302,79858,0500000US56025,37051.0,...,9390.0,1390.0,N,N,N,N,N,N,N,N