# Stage - 1(Task : 3) Displaying Enrichment dataset and making initial merging with super covid datset.

Memeber: Venkatesh Pulibandla

Description:
    In this task I have took a demographic census dataset as an enrichment dataset and analysed how covid-19 impacted the enrichment dataset.

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Here i have displayed the enrichment dataset first 5 rows.

file_cvs = pd.read_csv("../../DATASETS/ENRICHMENT DATASETS/demographic updated.csv")
demographic = pd.DataFrame(file_cvs)
demographic.head()

,GEO_ID,NAME,DP05_0001E,DP05_0001M,DP05_0002E,DP05_0002M,DP05_0003E,DP05_0003M,DP05_0004E,DP05_0004M,...,DP05_0085PE,DP05_0085PM,DP05_0086PE,DP05_0086PM,DP05_0087PE,DP05_0087PM,DP05_0088PE,DP05_0088PM,DP05_0089PE,DP05_0089PM
0,Geography,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Margin of Error!!SEX AND AGE!!Total population,Estimate!!SEX AND AGE!!Total population!!Male,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!Female,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!Sex r...,Margin of Error!!SEX AND AGE!!Total population...,...,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,Percent Margin of Error!!HISPANIC OR LATINO AN...,Percent!!Total housing units,Percent Margin of Error!!Total housing units,"Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...","Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...","Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P..."
1,0500000US01003,"Baldwin County, Alabama",239294,*****,115696,1401,123598,1401,93.6,2.2,...,2.2,0.6,(X),(X),185566,(X),48.5,0.7,51.5,0.7
2,0500000US01015,"Calhoun County, Alabama",115972,*****,55581,722,60391,722,92,2.3,...,3.6,1.8,(X),(X),88832,(X),47.8,0.4,52.2,0.4
3,0500000US01043,"Cullman County, Alabama",89496,*****,44331,477,45165,477,98.2,2.1,...,1.5,0.6,(X),(X),68751,(X),49.3,0.5,50.7,0.5
4,0500000US01049,"DeKalb County, Alabama",71813,*****,35952,1069,35861,1069,100.3,6,...,3.2,0.6,(X),(X),49274,(X),48.5,0.8,51.5,0.8

In [3]:
# In this step we have used the split() function to split the GEo_ID column so that i can get 'countyFIPS' column.
# 'countyFIPS' column will be helpfull to merge this dataset with covid-19 dataset.

demographic[['geoId','countyFIPS']] = demographic.GEO_ID.str.split("S", expand = True)

In [4]:
# Here we have placed the 'countyFIPS' as a starting column using pop() and insert() functions.

countyID = demographic.pop('countyFIPS')
demograhic=demographic.insert(0, 'countyFIPS', countyID)

In [5]:
demographic.dtypes

countyFIPS     object
GEO_ID         object
NAME           object
DP05_0001E     object
DP05_0001M     object
                ...
DP05_0088PE    object
DP05_0088PM    object
DP05_0089PE    object
DP05_0089PM    object
geoId          object
Length: 358, dtype: object

In [6]:
# Here we have removed the extra column named 'geoId', which came into existence when we split the 'GEO_ID' column.

demographic.drop('geoId', axis=1,inplace = True)

In [7]:
# here we have countyFIPS column to string type so that i can perform any string operations in future steps.

demographic.countyFIPS[0]= '00000'
demographic['countyFIPS']=demographic['countyFIPS'].astype(str)

In [8]:
# Here we have filtered the data by removing the unwanted first row.

demographic.drop(0, inplace=True)

In [9]:
# Here we have removed any extra zeros in the countyFIPS columns, so that we donot get any merge errors.

i=1
for id in demographic.countyFIPS:
    if id[0]=='0':
        y=id[1:]
        demographic.at[i,'countyFIPS'] = y
        i=i+1
        
demographic # This is the final dataset after filtering the data.

,countyFIPS,GEO_ID,NAME,DP05_0001E,DP05_0001M,DP05_0002E,DP05_0002M,DP05_0003E,DP05_0003M,DP05_0004E,...,DP05_0085PE,DP05_0085PM,DP05_0086PE,DP05_0086PM,DP05_0087PE,DP05_0087PM,DP05_0088PE,DP05_0088PM,DP05_0089PE,DP05_0089PM
1,1003,0500000US01003,"Baldwin County, Alabama",239294,*****,115696,1401,123598,1401,93.6,...,2.2,0.6,(X),(X),185566,(X),48.5,0.7,51.5,0.7
2,1015,0500000US01015,"Calhoun County, Alabama",115972,*****,55581,722,60391,722,92,...,3.6,1.8,(X),(X),88832,(X),47.8,0.4,52.2,0.4
3,1043,0500000US01043,"Cullman County, Alabama",89496,*****,44331,477,45165,477,98.2,...,1.5,0.6,(X),(X),68751,(X),49.3,0.5,50.7,0.5
4,1049,0500000US01049,"DeKalb County, Alabama",71813,*****,35952,1069,35861,1069,100.3,...,3.2,0.6,(X),(X),49274,(X),48.5,0.8,51.5,0.8
5,1051,0500000US01051,"Elmore County, Alabama",89304,*****,44004,785,45300,785,97.1,...,N,N,(X),(X),68232,(X),48,0.3,52,0.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
837,72113,0500000US72113,"Ponce Municipio, Puerto Rico",135084,*****,64529,*****,70555,*****,91.5,...,N,N,(X),(X),110128,(X),47.1,0.3,52.9,0.3
838,72127,0500000US72127,"San Juan Municipio, Puerto Rico",337300,*****,154195,*****,183105,*****,84.2,...,0.1,0.1,(X),(X),263918,(X),44.2,0.5,55.8,0.5
839,72135,0500000US72135,"Toa Alta Municipio, Puerto Rico",67569,*****,31626,564,35943,564,88,...,N,N,(X),(X),55680,(X),47.3,0.2,52.7,0.2
840,72137,0500000US72137,"Toa Baja Municipio, Puerto Rico",74368,*****,33780,306,40588,306,83.2,...,N,N,(X),(X),61112,(X),45.2,0.4,54.8,0.4
841,72139,0500000US72139,"Trujillo Alto Municipio, Puerto Rico",67211,*****,31040,762,36171,762,85.8,...,N,N,(X),(X),55195,(X),46.2,0.6,53.8,0.6

In [15]:
# Reading the covid super dataset.

superCovidDS = pd.read_csv("../../Team/STAGE1/superCovidDS.csv")

In [16]:
# Converting the 'countyFIPS' column to integer type to perform merge operations.

demographic['countyFIPS']=demographic['countyFIPS'].astype(int)
enrichment=pd.merge(superCovidDS,demographic, on =('countyFIPS'))

In [17]:
enrichment

,countyFIPS,County Name,State,StateFIPS,2020-01-22_x,2020-01-23_x,2020-01-24_x,2020-01-25_x,2020-01-26_x,2020-01-27_x,...,DP05_0085PE,DP05_0085PM,DP05_0086PE,DP05_0086PM,DP05_0087PE,DP05_0087PM,DP05_0088PE,DP05_0088PM,DP05_0089PE,DP05_0089PM
0,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,2.2,0.6,(X),(X),185566,(X),48.5,0.7,51.5,0.7
1,1015,Calhoun County,AL,1,0,0,0,0,0,0,...,3.6,1.8,(X),(X),88832,(X),47.8,0.4,52.2,0.4
2,1043,Cullman County,AL,1,0,0,0,0,0,0,...,1.5,0.6,(X),(X),68751,(X),49.3,0.5,50.7,0.5
3,1049,DeKalb County,AL,1,0,0,0,0,0,0,...,3.2,0.6,(X),(X),49274,(X),48.5,0.8,51.5,0.8
4,1051,Elmore County,AL,1,0,0,0,0,0,0,...,N,N,(X),(X),68232,(X),48,0.3,52,0.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
825,55133,Waukesha County,WI,55,0,0,0,0,0,0,...,1.7,0.3,(X),(X),314942,(X),49.1,0.2,50.9,0.2
826,55139,Winnebago County,WI,55,0,0,0,0,0,0,...,1.6,0.4,(X),(X),134474,(X),50.6,0.3,49.4,0.3
827,55141,Wood County,WI,55,0,0,0,0,0,0,...,1.6,0.5,(X),(X),57238,(X),49.4,0.6,50.6,0.6
828,56021,Laramie County,WY,56,0,0,0,0,0,0,...,1.5,0.4,(X),(X),76738,(X),50.7,0.7,49.3,0.7
829,56025,Natrona County,WY,56,0,0,0,0,0,0,...,4.4,0.4,(X),(X),59929,(X),51.1,0.7,48.9,0.7