# Covid Data Analysis
## Stage 1 Task 3

## Importing the required Packages

In [ ]:
import pandas as pd
import plotly.express as px

## Reading the data

In [ ]:
 # Covid Data
covid_cases = pd.read_csv('/content/drive/Shareddrives/605-DataScience/DS_Project_Stage1/covid_confirmed_usafacts.csv')
covid_deaths = pd.read_csv('/content/drive/Shareddrives/605-DataScience/DS_Project_Stage1/covid_deaths_usafacts.csv')
county_population = pd.read_csv('/content/drive/Shareddrives/605-DataScience/DS_Project_Stage1/covid_county_population_usafacts.csv')

#Enrichment Data (2020 Election Data)
governors_county = pd.read_csv('/content/drive/Shareddrives/605-DataScience/DS_Project_Stage1/Presidential_Electin_Results/governors_county.csv')
governors_county_candidate = pd.read_csv('/content/drive/Shareddrives/605-DataScience/DS_Project_Stage1/Presidential_Electin_Results/governors_county_candidate.csv')
governors_state = pd.read_csv('/content/drive/Shareddrives/605-DataScience/DS_Project_Stage1/Presidential_Electin_Results/governors_state.csv')
house_candidate = pd.read_csv('/content/drive/Shareddrives/605-DataScience/DS_Project_Stage1/Presidential_Electin_Results/house_candidate.csv')
house_state = pd.read_csv('/content/drive/Shareddrives/605-DataScience/DS_Project_Stage1/Presidential_Electin_Results/house_state.csv')
president_county = pd.read_csv('/content/drive/Shareddrives/605-DataScience/DS_Project_Stage1/Presidential_Electin_Results/president_county.csv')
president_county_candidate = pd.read_csv('/content/drive/Shareddrives/605-DataScience/DS_Project_Stage1/Presidential_Electin_Results/president_county_candidate.csv')
president_state = pd.read_csv('/content/drive/Shareddrives/605-DataScience/DS_Project_Stage1/Presidential_Electin_Results/president_state.csv')
senate_county = pd.read_csv('/content/drive/Shareddrives/605-DataScience/DS_Project_Stage1/Presidential_Electin_Results/senate_county.csv')
senate_county_candidate = pd.read_csv('/content/drive/Shareddrives/605-DataScience/DS_Project_Stage1/Presidential_Electin_Results/senate_county_candidate.csv')
senate_state = pd.read_csv('/content/drive/Shareddrives/605-DataScience/DS_Project_Stage1/Presidential_Electin_Results/senate_state.csv')

## Covid 19 Data trend for last week

### Data Exploration

#### County Population

In [ ]:
county_population.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3195 entries, 0 to 3194
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   countyFIPS   3195 non-null   int64
 1   County Name  3195 non-null   object
 2   State        3195 non-null   object
 3   population   3195 non-null   int64
dtypes: int64(2), object(2)
memory usage: 100.0+ KB

In [ ]:
county_population.head()

   countyFIPS            County Name State  population
0           0  Statewide Unallocated    AL           0
1        1001         Autauga County    AL       55869
2        1003         Baldwin County    AL      223234
3        1005         Barbour County    AL       24686
4        1007            Bibb County    AL       22394

In [ ]:
county_population["State"].nunique()

51

Checking for duplicate county and state pairs

In [ ]:
county_population[county_population.duplicated(subset=["County Name", "State"])]

Empty DataFrame
Columns: [countyFIPS, County Name, State, population]
Index: []

In [ ]:
county_population[county_population["County Name"] == "Statewide Unallocated"]

      countyFIPS            County Name State  population
0              0  Statewide Unallocated    AL           0
68             0  Statewide Unallocated    AK           0
99             0  Statewide Unallocated    AZ           0
115            0  Statewide Unallocated    AR           0
191            0  Statewide Unallocated    CA           0
251            0  Statewide Unallocated    CO           0
316            0  Statewide Unallocated    CT           0
325            0  Statewide Unallocated    DE           0
330            0  Statewide Unallocated    FL           0
398            0  Statewide Unallocated    GA           0
558            0  Statewide Unallocated    HI           0
564            0  Statewide Unallocated    ID           0
609            0  Statewide Unallocated    IL           0
712            0  Statewide Unallocated    IN           0
805            0  Statewide Unallocated    IA           0
905            0  Statewide Unallocated    KS           0
1011           0  Statewide Unallocated    KY           0
1132           0  Statewide Unallocated    LA           0
1197           0  Statewide Unallocated    ME           0
1214           0  Statewide Unallocated    MD           0
1239           0  Statewide Unallocated    MA           0
1254           0  Statewide Unallocated    MI           0
1338           0  Statewide Unallocated    MN           0
1426           0  Statewide Unallocated    MS           0
1509           0  Statewide Unallocated    MO           0
1625           0  Statewide Unallocated    MT           0
1682           0  Statewide Unallocated    NE           0
1776           0  Statewide Unallocated    NV           0
1794           0  Statewide Unallocated    NH           0
1805           0  Statewide Unallocated    NJ           0
1827           0  Statewide Unallocated    NM           0
1861           0  Statewide Unallocated    NY           0
1925           0  Statewide Unallocated    NC           0
2026           0  Statewide Unallocated    ND           0
2080           0  Statewide Unallocated    OH           0
2169           0  Statewide Unallocated    OK           0
2247           0  Statewide Unallocated    OR           0
2284           0  Statewide Unallocated    PA           0
2352           0  Statewide Unallocated    RI           0
2358           0  Statewide Unallocated    SC           0
2405           0  Statewide Unallocated    SD           0
2472           0  Statewide Unallocated    TN           0
2568           0  Statewide Unallocated    TX           0
2823           0  Statewide Unallocated    UT           0
2853           0  Statewide Unallocated    VT           0
2868           0  Statewide Unallocated    VA           0
3002           0  Statewide Unallocated    WA           0
3042           0  Statewide Unallocated    WV           0
3098           0  Statewide Unallocated    WI           0
3171           0  Statewide Unallocated    WY           0

In [ ]:
county_population[county_population["County Name"] == "Statewide Unallocated"].count()

countyFIPS     50
County Name    50
State          50
population     50
dtype: int64

These statewide unallocated counties has no population and not required. Hence dropping them

In [ ]:
county_population = county_population[county_population["County Name"] != "Statewide Unallocated"]

In [ ]:
print(county_population.info())
county_population.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3145 entries, 1 to 3194
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   countyFIPS   3145 non-null   int64
 1   County Name  3145 non-null   object
 2   State        3145 non-null   object
 3   population   3145 non-null   int64
dtypes: int64(2), object(2)
memory usage: 122.9+ KB
None

   countyFIPS     County Name State  population
1        1001  Autauga County    AL       55869
2        1003  Baldwin County    AL      223234
3        1005  Barbour County    AL       24686
4        1007     Bibb County    AL       22394
5        1009   Blount County    AL       57826

County Population dataset has population data for 3145 counties (After removing the Statewide Unallocated category) across 51 states

In [ ]:
county_population.groupby(by="State")["County Name"].count()

State
AK     30
AL     67
AR     75
AZ     15
CA     59
CO     64
CT      8
DC      1
DE      3
FL     67
GA    159
HI      5
IA     99
ID     44
IL    102
IN     92
KS    105
KY    120
LA     64
MA     14
MD     24
ME     16
MI     83
MN     87
MO    115
MS     82
MT     56
NC    100
ND     53
NE     93
NH     10
NJ     21
NM     33
NV     17
NY     63
OH     88
OK     77
OR     36
PA     67
RI      5
SC     46
SD     66
TN     95
TX    254
UT     29
VA    133
VT     14
WA     39
WI     72
WV     55
WY     23
Name: County Name, dtype: int64

#### Covid Cases

In [ ]:
covid_cases.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3193 entries, 0 to 3192
Columns: 1087 entries, countyFIPS to 2023-01-08
dtypes: int64(1085), object(2)
memory usage: 26.5+ MB

In [ ]:
covid_cases.head()

,countyFIPS,County Name,State,StateFIPS,2020-01-22,2020-01-23,2020-01-24,2020-01-25,2020-01-26,2020-01-27,...,2022-12-30,2022-12-31,2023-01-01,2023-01-02,2023-01-03,2023-01-04,2023-01-05,2023-01-06,2023-01-07,2023-01-08
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,18961,18961,18961,18961,18961,18961,18961,19205,19205,19205
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,67496,67496,67496,67496,67496,67496,67496,68182,68182,68182
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,7027,7027,7027,7027,7027,7027,7027,7120,7120,7120
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,7692,7692,7692,7692,7692,7692,7692,7808,7808,7808

covid_cases dataset has the confirmed covid cases started from the date 01-22-2022 to till 01-08-2023 for each county

#### Covid Deaths

In [ ]:
covid_deaths.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3193 entries, 0 to 3192
Columns: 1095 entries, countyFIPS to 2023-01-16
dtypes: int64(1093), object(2)
memory usage: 26.7+ MB

In [ ]:
covid_deaths.head()

,countyFIPS,County Name,State,StateFIPS,2020-01-22,2020-01-23,2020-01-24,2020-01-25,2020-01-26,2020-01-27,...,2023-01-07,2023-01-08,2023-01-09,2023-01-10,2023-01-11,2023-01-12,2023-01-13,2023-01-14,2023-01-15,2023-01-16
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,230,230,230,230,230,230,230,230,230,230
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,719,719,719,719,719,721,721,721,721,721
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,103,103,103,103,103,103,103,103,103,103
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,108,108,108,108,108,108,108,108,108,108

covid_deaths dataset  has the record of deaths confirmed from the date 01-22-2022 to till 01-16-2023 for each county.

#### Last Week Data Trends for North Dakota

##### Filtering Data for North Dakota State and last week i.e from 01-02-2023 to 01-08-2023

In [ ]:
#Filtering State
filtering_state = 'ND'
county_population_filtered = pd.DataFrame(county_population[county_population["State"]==filtering_state])
covid_cases_filtered = pd.DataFrame(covid_cases[covid_cases["State"]==filtering_state])
covid_deaths_filtered = pd.DataFrame(covid_deaths[covid_deaths["State"]==filtering_state])

In [ ]:
#Filtering Last Week Data
filtering_columns = ['County Name', 
                     'State', 
                     '2023-01-02', 
                     '2023-01-03', 
                     '2023-01-04', 
                     '2023-01-05', 
                     '2023-01-06',
                     '2023-01-07',
                     '2023-01-08'
                     ]
covid_cases_filtered = covid_cases_filtered[filtering_columns]
covid_deaths_filtered = covid_deaths_filtered[filtering_columns]

In [ ]:
county_population_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 53 entries, 2027 to 2079
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   countyFIPS   53 non-null     int64
 1   County Name  53 non-null     object
 2   State        53 non-null     object
 3   population   53 non-null     int64
dtypes: int64(2), object(2)
memory usage: 2.1+ KB

In [ ]:
covid_cases_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 54 entries, 2024 to 2077
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   County Name  54 non-null     object
 1   State        54 non-null     object
 2   2023-01-02   54 non-null     int64
 3   2023-01-03   54 non-null     int64
 4   2023-01-04   54 non-null     int64
 5   2023-01-05   54 non-null     int64
 6   2023-01-06   54 non-null     int64
 7   2023-01-07   54 non-null     int64
 8   2023-01-08   54 non-null     int64
dtypes: int64(7), object(2)
memory usage: 4.2+ KB

In [ ]:
covid_cases_filtered.head()

,County Name,State,2023-01-02,2023-01-03,2023-01-04,2023-01-05,2023-01-06,2023-01-07,2023-01-08
2024,Statewide Unallocated,ND,0,0,0,0,0,0,0
2025,Adams County,ND,681,681,681,681,681,681,681
2026,Barnes County,ND,3520,3520,3520,3520,3536,3536,3536
2027,Benson County,ND,2245,2245,2245,2245,2255,2255,2255
2028,Billings County,ND,167,167,167,167,167,167,167

In [ ]:
covid_deaths_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 54 entries, 2024 to 2077
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   County Name  54 non-null     object
 1   State        54 non-null     object
 2   2023-01-02   54 non-null     int64
 3   2023-01-03   54 non-null     int64
 4   2023-01-04   54 non-null     int64
 5   2023-01-05   54 non-null     int64
 6   2023-01-06   54 non-null     int64
 7   2023-01-07   54 non-null     int64
 8   2023-01-08   54 non-null     int64
dtypes: int64(7), object(2)
memory usage: 4.2+ KB

In [ ]:
covid_deaths_filtered.head()

,County Name,State,2023-01-02,2023-01-03,2023-01-04,2023-01-05,2023-01-06,2023-01-07,2023-01-08
2024,Statewide Unallocated,ND,0,0,0,0,0,0,0
2025,Adams County,ND,10,10,10,10,10,10,10
2026,Barnes County,ND,47,47,47,47,47,47,47
2027,Benson County,ND,23,23,23,23,23,23,23
2028,Billings County,ND,1,1,1,1,1,1,1

In [ ]:
# Removing the Statewide Unallocated data
covid_cases_filtered = covid_cases_filtered[covid_cases_filtered['County Name']!='Statewide Unallocated']
covid_deaths_filtered = covid_deaths_filtered[covid_deaths_filtered['County Name']!='Statewide Unallocated']

##### State Aggregated Data Analysis

###### Aggregating Data

In [ ]:
state_population = pd.DataFrame(county_population_filtered.groupby(by='State')['population'].sum()).reset_index()
state_covid_cases = pd.DataFrame(covid_cases_filtered.groupby(by='State').sum()).reset_index()
state_covid_deaths = pd.DataFrame(covid_deaths_filtered.groupby(by='State').sum()).reset_index()

In [ ]:
state_population

  State  population
0    ND      762062

In [ ]:
state_covid_cases

,State,2023-01-02,2023-01-03,2023-01-04,2023-01-05,2023-01-06,2023-01-07,2023-01-08
0,ND,280043,280043,280043,280043,281092,281092,281092

In [ ]:
state_covid_deaths

,State,2023-01-02,2023-01-03,2023-01-04,2023-01-05,2023-01-06,2023-01-07,2023-01-08
0,ND,2232,2232,2232,2232,2232,2232,2232

###### Plotting Covid Cases

In [ ]:
# Transforming the dataframe to suit for the plotting
state_covid_cases = pd.DataFrame(state_covid_cases.T.reset_index().drop([0]))
state_covid_cases.columns = ['Date', 'Total Cases']
state_covid_cases

         Date Total Cases
1  2023-01-02      280043
2  2023-01-03      280043
3  2023-01-04      280043
4  2023-01-05      280043
5  2023-01-06      281092
6  2023-01-07      281092
7  2023-01-08      281092

In [ ]:
state_covid_cases['New Cases'] = 0
for i in range(len(state_covid_cases)):
  if i == 0:
    state_covid_cases.iat[i,2] = 0
  else:
    state_covid_cases.iat[i,2] = state_covid_cases.iat[i,1]-state_covid_cases.iat[i-1,1]

In [ ]:
state_covid_cases

         Date Total Cases  New Cases
1  2023-01-02      280043          0
2  2023-01-03      280043          0
3  2023-01-04      280043          0
4  2023-01-05      280043          0
5  2023-01-06      281092       1049
6  2023-01-07      281092          0
7  2023-01-08      281092          0

In [ ]:
state_covid_deaths = pd.DataFrame(state_covid_deaths.T.reset_index().drop([0]))
state_covid_deaths.columns = ['Date', 'Total Deaths']
state_covid_deaths

         Date Total Deaths
1  2023-01-02         2232
2  2023-01-03         2232
3  2023-01-04         2232
4  2023-01-05         2232
5  2023-01-06         2232
6  2023-01-07         2232
7  2023-01-08         2232

In [ ]:
state_covid_deaths['New Deaths'] = 0
for i in range(len(state_covid_deaths)):
  if i == 0:
    state_covid_deaths.iat[i,2] = 0
  else:
    state_covid_deaths.iat[i,2] = state_covid_deaths.iat[i,1]-state_covid_deaths.iat[i-1,1]
state_covid_deaths

         Date Total Deaths  New Deaths
1  2023-01-02         2232           0
2  2023-01-03         2232           0
3  2023-01-04         2232           0
4  2023-01-05         2232           0
5  2023-01-06         2232           0
6  2023-01-07         2232           0
7  2023-01-08         2232           0

In [ ]:
px.line(state_covid_cases, x='Date', y='Total Cases', title='Cumulative Covid Cases in ND For the week of 02-Jan-23 to 08-Jan-23')

In [ ]:
px.line(state_covid_cases, x='Date', y='New Cases', title='Daily Covid Cases in ND For the week of 02-Jan-23 to 08-Jan-23')

In [ ]:
px.line(state_covid_deaths, x='Date', y='Total Deaths', title='Cumulative Covid Deaths in ND For the week of 02-Jan-23 to 08-Jan-23')

In [ ]:
px.line(state_covid_deaths, x='Date', y='New Deaths', title='Daily Covid Deaths in ND For the week of 02-Jan-23 to 08-Jan-23')

###### Summary

After plotting the trends for the state of North Dakota, we can see that there is a spike in the reported covid cases on Jan 6th 2023. And no cases there after. Also there are no deaths in the analyzed week.

##### County Wise Analysis

###### Transforming County Data

In [ ]:
covid_cases_filtered.drop(columns=['State'], inplace=True)

In [ ]:
covid_cases_filtered.head()

,County Name,2023-01-02,2023-01-03,2023-01-04,2023-01-05,2023-01-06,2023-01-07,2023-01-08
2025,Adams County,681,681,681,681,681,681,681
2026,Barnes County,3520,3520,3520,3520,3536,3536,3536
2027,Benson County,2245,2245,2245,2245,2255,2255,2255
2028,Billings County,167,167,167,167,167,167,167
2029,Bottineau County,1834,1834,1834,1834,1838,1838,1838

In [ ]:
nd_covid_cases_transformed = pd.DataFrame(columns=['Date','County Name', 'Cases'])
nd_covid_cases_transformed.head()

Empty DataFrame
Columns: [Date, County Name, Cases]
Index: []

In [ ]:
county_list = list(covid_cases_filtered['County Name'].unique())
dates_list = list(covid_cases_filtered.columns)[1:]

In [ ]:
for county in county_list:
  for date in dates_list:
    nd_covid_cases_transformed.loc[len(nd_covid_cases_transformed)] = [date, county, int(covid_cases_filtered[covid_cases_filtered['County Name']==county][date])]

In [ ]:
nd_covid_cases_transformed.head()

         Date    County Name Cases
0  2023-01-02  Adams County    681
1  2023-01-03  Adams County    681
2  2023-01-04  Adams County    681
3  2023-01-05  Adams County    681
4  2023-01-06  Adams County    681

In [ ]:
def add_new_diff_column(df,col_name):
  df[col_name] = 0
  for i in range(len(df)):
    if df.iat[i,0] == '2023-01-02':
      df.iat[i,3] = 0
    else:
      df.iat[i,3] = df.iat[i,2]-df.iat[i-1,2]

In [ ]:
add_new_diff_column(nd_covid_cases_transformed,'New Cases')

In [ ]:
nd_covid_cases_transformed.head()

         Date    County Name Cases  New Cases
0  2023-01-02  Adams County    681          0
1  2023-01-03  Adams County    681          0
2  2023-01-04  Adams County    681          0
3  2023-01-05  Adams County    681          0
4  2023-01-06  Adams County    681          0

In [ ]:
covid_deaths_filtered.head()

,County Name,State,2023-01-02,2023-01-03,2023-01-04,2023-01-05,2023-01-06,2023-01-07,2023-01-08
2025,Adams County,ND,10,10,10,10,10,10,10
2026,Barnes County,ND,47,47,47,47,47,47,47
2027,Benson County,ND,23,23,23,23,23,23,23
2028,Billings County,ND,1,1,1,1,1,1,1
2029,Bottineau County,ND,26,26,26,26,26,26,26

In [ ]:
try:
  covid_deaths_filtered.drop(columns=['State'], inplace=True)
except KeyError as e:
  print("State already dropped")
nd_covid_deaths_transformed = pd.DataFrame(columns=['Date','County Name', 'Deaths'])
county_list = list(covid_deaths_filtered['County Name'].unique())
dates_list = list(covid_deaths_filtered.columns)[1:]

for county in county_list:
  for date in dates_list:
    nd_covid_deaths_transformed.loc[len(nd_covid_deaths_transformed)] = [date, county, int(covid_deaths_filtered[covid_deaths_filtered['County Name']==county][date])]

add_new_diff_column(nd_covid_deaths_transformed,'New Deaths')
nd_covid_deaths_transformed.head()

         Date    County Name Deaths  New Deaths
0  2023-01-02  Adams County      10           0
1  2023-01-03  Adams County      10           0
2  2023-01-04  Adams County      10           0
3  2023-01-05  Adams County      10           0
4  2023-01-06  Adams County      10           0

###### Plotting

In [ ]:
px.line(nd_covid_cases_transformed, x='Date', y='Cases',color='County Name', title='Cumulative Covid Cases in ND For the week of 02-Jan-23 to 08-Jan-23 by County')

In [ ]:
px.line(nd_covid_cases_transformed, x='Date', y='New Cases',color='County Name', title='New Covid Cases in ND For the week of 02-Jan-23 to 08-Jan-23 by County')

In [ ]:
px.line(nd_covid_deaths_transformed, x='Date', y='Deaths',color='County Name', title='Cumulative Covid Deaths in ND For the week of 02-Jan-23 to 08-Jan-23 by County')

In [ ]:
px.line(nd_covid_deaths_transformed, x='Date', y='New Deaths',color='County Name', title='New Covid Deaths in ND For the week of 02-Jan-23 to 08-Jan-23 by county')

In [ ]:
px.bar(data_frame=county_population_filtered,x='County Name', y='population', title= 'Bar Chart of ND population County Wise')

###### Summary

Below are my deductions from the above plots


1.   The ***Cumulative Covid Cases in ND For the week of 02-Jan-23 to 08-Jan-23 by County*** plot shows not much important information about covid trends for the week. We can only deduce that till Jan 2023, Cass County has the highest covid cases registred.
2.   The ***New Covid Cases in ND For the week of 02-Jan-23 to 08-Jan-23 by County*** plot shows that all the counties has a cases raise on Jan 6th which is also evident from the previously plotted ***New Covid Cases in ND For the week of 02-Jan-23 to 08-Jan-23*** Plot. However, here we can see that Cass County has highest new cases and also only 5 Counties [Cass, Burleigh, Grand Forks, Ward, Williams] has new cases over 50. 
3. The high numbers in those 5 counties is clearly evident because they are the top 5 populous counties in the state.
4. The other two plots related to deaths show no specific information except that there are zero deaths in the First week of January 2023. And Cass County has highest deaths 333 until that week.


Overall we can say that there is no much covid affect [Stable] in the state of North Dakota. Whatever the cases raise that was observed on Jan 6th could be due to Holiday [Christmas and New Year] gatherings.

## Displaying Enrichment Data

### Governor's Election Data

In [ ]:
governors_county.head()

      state             county  current_votes  total_votes  percent
0  Delaware        Kent County          85415        87025      100
1  Delaware  New Castle County         280039       287633      100
2  Delaware      Sussex County         127181       129352      100
3   Indiana       Adams County          14154        14209      100
4   Indiana       Allen County         168312       169082      100

In [ ]:
governors_county.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   state          1025 non-null   object
 1   county         1025 non-null   object
 2   current_votes  1025 non-null   int64
 3   total_votes    1025 non-null   int64
 4   percent        1025 non-null   int64
dtypes: int64(3), object(2)
memory usage: 40.2+ KB

In [ ]:
governors_county_candidate.head()

      state             county        candidate party   votes    won
0  Delaware        Kent County      John Carney   DEM   44352   True
1  Delaware        Kent County  Julianne Murray   REP   39332  False
2  Delaware        Kent County  Kathy DeMatteis   IPD    1115  False
3  Delaware        Kent County    John Machurek   LIB     616  False
4  Delaware  New Castle County      John Carney   DEM  191678   True

In [ ]:
governors_county_candidate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5145 entries, 0 to 5144
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   state      5145 non-null   object
 1   county     5145 non-null   object
 2   candidate  5145 non-null   object
 3   party      5145 non-null   object
 4   votes      5145 non-null   int64
 5   won        5145 non-null   bool
dtypes: bool(1), int64(1), object(4)
memory usage: 206.1+ KB

In [ ]:
governors_state.head()

           state    votes
0       Delaware   492635
1        Indiana  3020383
2       Missouri  3012274
3        Montana   603587
4  New Hampshire   792804

In [ ]:
governors_state.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   state   11 non-null     object
 1   votes   11 non-null     int64
dtypes: int64(1), object(1)
memory usage: 304.0+ bytes

In [ ]:
# Number of States in which elections took place
governors_state.state.nunique()

11

In [ ]:
#Number of Counties in which elections took place
governors_county[governors_county.duplicated(subset=["state", "county"])]

Empty DataFrame
Columns: [state, county, current_votes, total_votes, percent]
Index: []

In [ ]:
#Number of Candidates and Parties
print("# Candidates:", governors_county_candidate.candidate.nunique())
print("# Parties:", governors_county_candidate.party.nunique())

# Candidates: 43
# Parties: 12

The Governor's Election occured in 11 states comprising of 1025 Counties.

A total of 43 Members from 12 different parties contested in these elections for different states

### House Election Data

In [ ]:
house_candidate.head()

                 district             candidate party  total_votes    won
0       Delaware at large  Lisa Blunt Rochester   DEM       281382   True
1       Delaware at large            Lee Murphy   REP       196392  False
2       Delaware at large     Catherine Purcell   IND         6682  False
3       Delaware at large          David Rogers   LIB         3814  False
4  Florida’s 1st district            Matt Gaetz   REP       283352   True

In [ ]:
house_candidate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1215 entries, 0 to 1214
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   district     1215 non-null   object
 1   candidate    1215 non-null   object
 2   party        1215 non-null   object
 3   total_votes  1215 non-null   int64
 4   won          1215 non-null   bool
dtypes: bool(1), int64(1), object(3)
memory usage: 39.3+ KB

In [ ]:
house_state.head()

                 district  current_votes  total_votes  percent
0       Delaware at large         488270       488270      100
1  Florida’s 1st district         438562       438562      100
2  Florida’s 2nd district         311999       311999      100
3  Florida’s 3rd district         390401       390401      100
4  Florida’s 4th district         504940       504940      100

In [ ]:
house_state.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 436 entries, 0 to 435
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   district       436 non-null    object
 1   current_votes  436 non-null    int64
 2   total_votes    436 non-null    int64
 3   percent        436 non-null    int64
dtypes: int64(3), object(1)
memory usage: 13.8+ KB

The house Election dataset has elections mixed data for house candidate either state level or district level of the state. This data needs to be transformed before further analysis or merging to the covid dataset

### President Election Data

In [ ]:
president_county.head()

,state,county,current_votes,total_votes,percent
0,Delaware,Kent County,87025,87025,100
1,Delaware,New Castle County,287633,287633,100
2,Delaware,Sussex County,129352,129352,100
3,District of Columbia,District of Columbia,41681,41681,100
4,District of Columbia,Ward 2,32881,32881,100

In [ ]:
president_county.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4633 entries, 0 to 4632
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   state          4633 non-null   object
 1   county         4633 non-null   object
 2   current_votes  4633 non-null   int64
 3   total_votes    4633 non-null   int64
 4   percent        4633 non-null   int64
dtypes: int64(3), object(2)
memory usage: 181.1+ KB

In [ ]:
president_county_candidate.head()

      state             county      candidate party  total_votes    won
0  Delaware        Kent County      Joe Biden   DEM        44552   True
1  Delaware        Kent County   Donald Trump   REP        41009  False
2  Delaware        Kent County   Jo Jorgensen   LIB         1044  False
3  Delaware        Kent County  Howie Hawkins   GRN          420  False
4  Delaware  New Castle County      Joe Biden   DEM       195034   True

In [ ]:
president_county_candidate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32177 entries, 0 to 32176
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   state        32177 non-null  object
 1   county       32177 non-null  object
 2   candidate    32177 non-null  object
 3   party        32177 non-null  object
 4   total_votes  32177 non-null  int64
 5   won          32177 non-null  bool
dtypes: bool(1), int64(1), object(4)
memory usage: 1.3+ MB

In [ ]:
president_state.head()

                  state  total_votes
0              Delaware       504010
1  District of Columbia       344356
2               Florida     11067456
3               Georgia      4997716
4                Hawaii       574469

In [ ]:
president_state.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   state        52 non-null     object
 1   total_votes  52 non-null     int64
dtypes: int64(1), object(1)
memory usage: 960.0+ bytes

In [ ]:
#Number of candidates
president_county_candidate.candidate.nunique()

38

The President Election data has 2020 president election results data on county basis. The data is liste for 4633 Counties which is greater than the number of counties in US. So this data needs to be transformed before further analyzing it. It listed 38 Unique candidates contesting running for the President

### Senate Election Data

In [ ]:
senate_county.head()

      state             county  current_votes  total_votes  percent
0  Delaware        Kent County          84975        87025      100
1  Delaware  New Castle County         279462       287633      100
2  Delaware      Sussex County         126498       129352      100
3   Georgia     Appling County           8187         8341      100
4   Georgia    Atkinson County           3097         3155      100

In [ ]:
senate_county.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3582 entries, 0 to 3581
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   state          3582 non-null   object
 1   county         3582 non-null   object
 2   current_votes  3582 non-null   int64
 3   total_votes    3582 non-null   int64
 4   percent        3582 non-null   int64
dtypes: int64(3), object(2)
memory usage: 140.0+ KB

In [ ]:
senate_county_candidate.head()

      state             county      candidate party  total_votes
0  Delaware        Kent County  Lauren Witzke   REP        38571
1  Delaware        Kent County    Mark Turley   IPD         1553
2  Delaware        Kent County   Nadine Frost   LIB          958
3  Delaware  New Castle County  Lauren Witzke   REP        80081
4  Delaware  New Castle County    Mark Turley   IPD         4277

In [ ]:
senate_county_candidate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14125 entries, 0 to 14124
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   state        14125 non-null  object
 1   county       14125 non-null  object
 2   candidate    14125 non-null  object
 3   party        14125 non-null  object
 4   total_votes  14125 non-null  int64
dtypes: int64(1), object(4)
memory usage: 551.9+ KB

In [ ]:
senate_state.head()

      state  total_votes
0  Delaware       490935
1   Georgia      4952440
2     Idaho       858826
3  Illinois      5969702
4      Iowa      1670617

In [ ]:
senate_state.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   state        35 non-null     object
 1   total_votes  35 non-null     int64
dtypes: int64(1), object(1)
memory usage: 688.0+ bytes

In [ ]:
#Number of candidates
senate_county_candidate.candidate.nunique()

148

The Senate Election dataset lists senate election data for 2020. The data lists 3582 counties which is greater than total counties in US. So this data needs to be transformed for futher analysis. The data listed 148 candidates are contesting for the senate.

## Merging Enrichment data with Covid data

### Merging all Covid Datasets

In [ ]:
# Removing CountyFIPS code of 0 from all the datasets
county_population = county_population[county_population['countyFIPS']!=0]
covid_cases = covid_cases[covid_cases['countyFIPS']!=0]
covid_deaths = covid_deaths[covid_deaths['countyFIPS']!=0]

In [ ]:
print(county_population.shape)
print(covid_cases.shape)
print(covid_deaths.shape)

(3144, 4)
(3142, 1087)
(3142, 1095)

In [ ]:
merge_covid_dataset = county_population.merge(covid_cases,how='left',on='countyFIPS')
merge_covid_dataset

,countyFIPS,County Name_x,State_x,population,County Name_y,State_y,StateFIPS,2020-01-22,2020-01-23,2020-01-24,...,2022-12-30,2022-12-31,2023-01-01,2023-01-02,2023-01-03,2023-01-04,2023-01-05,2023-01-06,2023-01-07,2023-01-08
0,1001,Autauga County,AL,55869,Autauga County,AL,1.0,0.0,0.0,0.0,...,18961.0,18961.0,18961.0,18961.0,18961.0,18961.0,18961.0,19205.0,19205.0,19205.0
1,1003,Baldwin County,AL,223234,Baldwin County,AL,1.0,0.0,0.0,0.0,...,67496.0,67496.0,67496.0,67496.0,67496.0,67496.0,67496.0,68182.0,68182.0,68182.0
2,1005,Barbour County,AL,24686,Barbour County,AL,1.0,0.0,0.0,0.0,...,7027.0,7027.0,7027.0,7027.0,7027.0,7027.0,7027.0,7120.0,7120.0,7120.0
3,1007,Bibb County,AL,22394,Bibb County,AL,1.0,0.0,0.0,0.0,...,7692.0,7692.0,7692.0,7692.0,7692.0,7692.0,7692.0,7808.0,7808.0,7808.0
4,1009,Blount County,AL,57826,Blount County,AL,1.0,0.0,0.0,0.0,...,17731.0,17731.0,17731.0,17731.0,17731.0,17731.0,17731.0,17952.0,17952.0,17952.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3139,56037,Sweetwater County,WY,42343,Sweetwater County,WY,56.0,0.0,0.0,0.0,...,12394.0,12394.0,12394.0,12394.0,12394.0,12394.0,12394.0,12394.0,12394.0,12394.0
3140,56039,Teton County,WY,23464,Teton County,WY,56.0,0.0,0.0,0.0,...,11997.0,11997.0,11997.0,11997.0,11997.0,11997.0,11997.0,11997.0,11997.0,11997.0
3141,56041,Uinta County,WY,20226,Uinta County,WY,56.0,0.0,0.0,0.0,...,6303.0,6303.0,6303.0,6303.0,6303.0,6303.0,6303.0,6303.0,6303.0,6303.0
3142,56043,Washakie County,WY,7805,Washakie County,WY,56.0,0.0,0.0,0.0,...,2717.0,2717.0,2717.0,2717.0,2717.0,2717.0,2717.0,2717.0,2717.0,2717.0
3143,56045,Weston County,WY,6927,Weston County,WY,56.0,0.0,0.0,0.0,...,1876.0,1876.0,1876.0,1876.0,1876.0,1876.0,1876.0,1876.0,1876.0,1876.0

In [ ]:
#Removing unwanted columns
merge_filter_columns  = ['countyFIPS','County Name_x','State_x','population','2020-10-31']
merge_covid_dataset = merge_covid_dataset[merge_filter_columns]

In [ ]:
merge_covid_dataset_columns_list = list(merge_covid_dataset.columns)
merge_covid_dataset_columns_list[1] = 'County_Name'
merge_covid_dataset_columns_list[2] = 'State'
merge_covid_dataset_columns_list[4] = 'Total_Covid_Cases_Till_Election'
merge_covid_dataset.columns = merge_covid_dataset_columns_list
merge_covid_dataset

,countyFIPS,County_Name,State,population,Total_Covid_Cases_Till_Election
0,1001,Autauga County,AL,55869,2159.0
1,1003,Baldwin County,AL,223234,6940.0
2,1005,Barbour County,AL,24686,1060.0
3,1007,Bibb County,AL,22394,873.0
4,1009,Blount County,AL,57826,2074.0
...,...,...,...,...,...
3139,56037,Sweetwater County,WY,42343,553.0
3140,56039,Teton County,WY,23464,796.0
3141,56041,Uinta County,WY,20226,479.0
3142,56043,Washakie County,WY,7805,158.0
3143,56045,Weston County,WY,6927,159.0

In [ ]:
#Joining Deaths
merge_covid_dataset = merge_covid_dataset.merge(covid_deaths,how='left',on='countyFIPS')
merge_covid_dataset

,countyFIPS,County_Name,State_x,population,Total_Covid_Cases_Till_Election,County Name,State_y,StateFIPS,2020-01-22,2020-01-23,...,2023-01-07,2023-01-08,2023-01-09,2023-01-10,2023-01-11,2023-01-12,2023-01-13,2023-01-14,2023-01-15,2023-01-16
0,1001,Autauga County,AL,55869,2159.0,Autauga County,AL,1.0,0.0,0.0,...,230.0,230.0,230.0,230.0,230.0,230.0,230.0,230.0,230.0,230.0
1,1003,Baldwin County,AL,223234,6940.0,Baldwin County,AL,1.0,0.0,0.0,...,719.0,719.0,719.0,719.0,719.0,721.0,721.0,721.0,721.0,721.0
2,1005,Barbour County,AL,24686,1060.0,Barbour County,AL,1.0,0.0,0.0,...,103.0,103.0,103.0,103.0,103.0,103.0,103.0,103.0,103.0,103.0
3,1007,Bibb County,AL,22394,873.0,Bibb County,AL,1.0,0.0,0.0,...,108.0,108.0,108.0,108.0,108.0,108.0,108.0,108.0,108.0,108.0
4,1009,Blount County,AL,57826,2074.0,Blount County,AL,1.0,0.0,0.0,...,260.0,260.0,260.0,260.0,260.0,261.0,261.0,261.0,261.0,261.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3139,56037,Sweetwater County,WY,42343,553.0,Sweetwater County,WY,56.0,0.0,0.0,...,136.0,136.0,136.0,136.0,136.0,136.0,136.0,136.0,136.0,136.0
3140,56039,Teton County,WY,23464,796.0,Teton County,WY,56.0,0.0,0.0,...,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0
3141,56041,Uinta County,WY,20226,479.0,Uinta County,WY,56.0,0.0,0.0,...,43.0,43.0,43.0,43.0,43.0,43.0,43.0,43.0,43.0,43.0
3142,56043,Washakie County,WY,7805,158.0,Washakie County,WY,56.0,0.0,0.0,...,47.0,47.0,47.0,47.0,47.0,47.0,47.0,47.0,47.0,47.0
3143,56045,Weston County,WY,6927,159.0,Weston County,WY,56.0,0.0,0.0,...,22.0,22.0,22.0,22.0,22.0,22.0,22.0,22.0,22.0,22.0

In [ ]:
#Removing unwanted columns
merge_filter_columns  = ['countyFIPS','County_Name','State_x','population','Total_Covid_Cases_Till_Election','2020-10-31']
merge_covid_dataset = merge_covid_dataset[merge_filter_columns]
merge_covid_dataset

,countyFIPS,County_Name,State_x,population,Total_Covid_Cases_Till_Election,2020-10-31
0,1001,Autauga County,AL,55869,2159.0,30.0
1,1003,Baldwin County,AL,223234,6940.0,71.0
2,1005,Barbour County,AL,24686,1060.0,9.0
3,1007,Bibb County,AL,22394,873.0,15.0
4,1009,Blount County,AL,57826,2074.0,25.0
...,...,...,...,...,...,...
3139,56037,Sweetwater County,WY,42343,553.0,2.0
3140,56039,Teton County,WY,23464,796.0,1.0
3141,56041,Uinta County,WY,20226,479.0,3.0
3142,56043,Washakie County,WY,7805,158.0,7.0
3143,56045,Weston County,WY,6927,159.0,0.0

In [ ]:
merge_covid_dataset_columns_list = list(merge_covid_dataset.columns)
merge_covid_dataset_columns_list[2] = 'State'
merge_covid_dataset_columns_list[5] = 'Total_Covid_Deaths_Till_Election'
merge_covid_dataset.columns = merge_covid_dataset_columns_list
merge_covid_dataset

,countyFIPS,County_Name,State,population,Total_Covid_Cases_Till_Election,Total_Covid_Deaths_Till_Election
0,1001,Autauga County,AL,55869,2159.0,30.0
1,1003,Baldwin County,AL,223234,6940.0,71.0
2,1005,Barbour County,AL,24686,1060.0,9.0
3,1007,Bibb County,AL,22394,873.0,15.0
4,1009,Blount County,AL,57826,2074.0,25.0
...,...,...,...,...,...,...
3139,56037,Sweetwater County,WY,42343,553.0,2.0
3140,56039,Teton County,WY,23464,796.0,1.0
3141,56041,Uinta County,WY,20226,479.0,3.0
3142,56043,Washakie County,WY,7805,158.0,7.0
3143,56045,Weston County,WY,6927,159.0,0.0

### Merging Covid data with Senate Data

In [ ]:
senate_county

         state             county  current_votes  total_votes  percent
0     Delaware        Kent County          84975        87025      100
1     Delaware  New Castle County         279462       287633      100
2     Delaware      Sussex County         126498       129352      100
3      Georgia     Appling County           8187         8341      100
4      Georgia    Atkinson County           3097         3155      100
...        ...                ...            ...          ...      ...
3577   Georgia   Whitfield County          35593        36746      100
3578   Georgia      Wilcox County           3218         3281      100
3579   Georgia      Wilkes County           4905         5029      100
3580   Georgia   Wilkinson County           4689         4770      100
3581   Georgia       Worth County           9129         9286      100

[3582 rows x 5 columns]

Senate has 3582 rows which is more than the counties data present in covid data. So let us validate the counties data in senate dataset for duplicates

In [ ]:
senate_county[senate_county.duplicated(['state','county'])]

        state            county  current_votes  total_votes  percent
3423  Georgia    Appling County           8159         8341      100
3424  Georgia   Atkinson County           2995         3155      100
3425  Georgia      Bacon County           4512         4668      100
3426  Georgia      Baker County           1514         1555      100
3427  Georgia    Baldwin County          17942        18251      100
...       ...               ...            ...          ...      ...
3577  Georgia  Whitfield County          35593        36746      100
3578  Georgia     Wilcox County           3218         3281      100
3579  Georgia     Wilkes County           4905         5029      100
3580  Georgia  Wilkinson County           4689         4770      100
3581  Georgia      Worth County           9129         9286      100

[159 rows x 5 columns]

In [ ]:
senate_county.state.nunique()

34

It shows the duplicated data is 159 rows. Even if we remove those rows we will have more counties and there are only 34 states available in senate_county election data. So we need to verify the authenticity of data by cross checking the county names across those states

In [ ]:
#States in senate_county data
senate_county_state_list = list(senate_county['state'].unique())
state_abbreviations_df = pd.read_csv('/content/drive/Shareddrives/605-DataScience/DS_Project_Stage1/Additional_Resources/US_State_Abbreviations.csv')

In [ ]:
state_abbreviations_df.head()

        State Abbreviation
0     Alabama           AL
1      Alaska           AK
2     Arizona           AZ
3    Arkansas           AR
4  California           CA

In [ ]:
#Checking for County Name discrepancies
def get_different_county_names(state_name):
  senate_county_names_list = senate_county[senate_county['state']==state_name]['county'].to_list()
  covid_dataset_county_names_list = merge_covid_dataset[merge_covid_dataset['State']==str(state_abbreviations_df[state_abbreviations_df['State']==state_name]['Abbreviation'].item())]['County_Name'].to_list()
  return list(set(senate_county_names_list).symmetric_difference(set(covid_dataset_county_names_list)))

In [ ]:
county_population_state_list = county_population['State'].unique()
for state in county_population_state_list:
  try:
    state_name = state_abbreviations_df[state_abbreviations_df['Abbreviation']==state]['State'].item()
    output = get_different_county_names(state_name)
    if len(output) > 0:
      if state_name in senate_county[senate_county['state']==state_name]['state'].to_list():
        print(f'{state_name} State has discrepancies Please verify:')
        print(output)
      else:
        print(f'state {state_name} is not available in senate election data so excluding')
  # except ValueError as e:
  #   print(f'state {state} is not available in state_abbreviations and is not present in any election data so excluding')
  except Exception as e:
    print(f'Unknown Error occured for the state {state}. {e}')

Alaska State has discrepancies Please verify:
['ED 13', 'ED 39', 'Wrangell City and Borough', 'ED 1', 'Yakutat City and Borough', 'ED 17', 'Aleutians West Census Area', 'ED 26', 'Wade Hampton Census Area', 'ED 24', 'ED 25', 'ED 31', 'Municipality of Anchorage', 'ED 23', 'ED 38', 'Hoonah-Angoon Census Area', 'ED 36', 'ED 22', 'ED 8', 'ED 16', 'ED 12', 'ED 4', 'ED 3', 'Valdez-Cordova Census Area', 'Haines Borough', 'Northwest Arctic Borough', 'Aleutians East Borough', 'Petersburg Census Area', 'Bristol Bay Borough', 'Kenai Peninsula Borough', 'ED 34', 'Dillingham Census Area', 'North Slope Borough', 'ED 15', 'ED 27', 'Ketchikan Gateway Borough', 'Skagway Municipality', 'ED 35', 'ED 37', 'Denali Borough', 'ED 21', 'ED 7', 'Nome Census Area', 'ED 14', 'ED 29', 'Southeast Fairbanks Census Area', 'ED 18', 'Fairbanks North Star Borough', 'Kusilvak Census Area', 'Lake and Peninsula Borough', 'ED 5', 'ED 19', 'ED 2', 'ED 9', 'Bethel Census Area', 'ED 28', 'ED 32', 'Kodiak Island Borough', 'ED 33', 'Matanuska-Susitna Borough', 'Yukon-Koyukuk Census Area', 'Sitka City and Borough', 'ED 6', 'ED 30', 'ED 11', 'City and Borough of Juneau', 'Prince of Wales-Hyder Census Area', 'ED 40', 'ED 10', 'ED 20']
state California is not available in senate election data so excluding
Colorado State has discrepancies Please verify:
['Broomfield County', 'Broomfield County and City']
state Connecticut is not available in senate election data so excluding
state District of Columbia is not available in senate election data so excluding
state Florida is not available in senate election data so excluding
state Hawaii is not available in senate election data so excluding
Illinois State has discrepancies Please verify:
['Cook Suburbs']
state Indiana is not available in senate election data so excluding
Louisiana State has discrepancies Please verify:
['LaSalle Parish', 'La Salle Parish']
Maine State has discrepancies Please verify:
['Mercer', 'Lewiston', 'Mexico', 'Harrington', 'Islesboro', 'Dennysville', 'Lincolnville', 'Hanover', 'Amherst', 'West Forks Plt.', 'Peru', 'Tremont', 'St. Francis', 'Oakfield', 'Prospect', 'Brownville', 'Machias', 'Seboeis Plt.', 'Freedom', 'Rome', 'Casco', 'Berwick', 'Jackman', 'Sedgwick', 'Smithfield', 'Woodstock', 'Bath', 'Farmington', 'Washington County', 'Dyer Brook', 'Nashville Plt.', 'Minot', 'Searsport', 'Gouldsboro', 'Friendship', 'Northfield', 'Castle Hill', 'Sherman', 'The Forks Plt.', 'Phippsburg', 'Moro Plt.', 'Franklin Cty Townships', 'Orient', 'Lebanon', 'Veazie', 'Corinna', 'York', 'Lincoln County', 'Monmouth', 'Cornville', 'Harrison', 'Wilton', 'Meddybemps', 'Wales', 'Ripley', 'Swanville', 'Brewer', 'Jefferson', 'Cherryfield', 'Franklin County', 'Lee', 'Linneus', 'Temple', 'Sebec', 'Beddington', 'Burlington', 'Winterville Plt.', 'Lovell', 'Princeton', 'Boothbay', 'Whitefield', 'Bridgton', 'Fairfield', 'Orrington', 'Wesley', 'Woodland', 'Waterboro', 'Standish', 'Indian Township Vtng Dst', 'Limerick', 'Eastbrook', 'Lyman', 'Newcastle', 'Millinocket', 'Whitneyville', 'Great Pond', 'Buckfield', 'Monticello', 'Hartford', 'Sorrento', 'Holden', 'Charlotte', 'Baring Plt.', 'Androscoggin County', 'Waldo County', 'Solon', 'Carrabassett Valley', 'Beals', 'Pleasant Point Votng Dst', 'Bangor', 'Cary Plt.', 'Greenbush', 'Rockport', 'Roxbury', 'Benton', 'Saco', 'Smyrna', 'Lake View Plt.', 'New Vineyard', 'Ludlow', 'Long Island', 'Chapman', 'Paris', 'Turner', 'Woolwich', 'Bremen', 'Ellsworth', 'Ashland', 'Westmanland', 'Bar Harbor', 'Dixmont', 'Greene', 'Bradford', 'Fayette', 'Topsfield', 'Isle Au Haut', 'Drew Plt.', 'Penobscot Nation Vot Dst', 'Patten', 'Otis', 'Chebeague Island', 'Kingsbury Plt.', 'South Bristol', 'Oxford County', 'Auburn', 'Dallas Plt.', 'New Sweden', 'Lubec', 'LaGrange', 'Old Town', 'Waterford', 'Caribou', 'Manchester', 'Shirley', 'Strong', 'Allagash', 'Vienna', 'Stockton Springs', 'Otisfield', 'Washburn', 'Mars Hill', 'Wallagrass', 'South Thomaston', 'Hammond', 'Falmouth', 'Dayton', 'Thorndike', 'York County', 'Hancock County', 'Somerset Cty Townships', 'Vanceboro', 'Stetson', 'Somerset County', 'Knox', 'Caratunk', 'Deblois', 'Bucksport', 'Portage Lake', 'Surry', 'Alna', 'Osborn', 'Alexander', 'Sagadahoc County', 'Starks', 'New Canada', 'Lakeville', 'Edinburg', 'Buxton', 'Trenton', 'Robbinston', 'Limestone', 'Phillips', 'Weld', 'Westbrook', 'Carroll Plt.', 'Levant', 'Knox County', 'Unity', 'West Gardiner', 'Hamlin', 'East Millinocket', 'Anson', 'Piscataquis County', 'Sangerville', 'Palermo', 'Piscataquis Cty Townshps', 'Reed Plt.', 'New Gloucester', 'Denmark', 'Presque Isle', 'Andover', 'Gray', 'Athens', 'Bradley', 'Wells', 'Bristol', 'Pleasant Ridge Plt.', 'Industry', 'Pittston', 'Garland', "Owl's Head", 'Orono', 'Bowerbank', 'Macwahoc Plt.', 'Hebron', 'Westport', 'Kenduskeag', 'Plymouth', 'Dexter', 'Belmont', 'Blue Hill', 'Embden', 'Lincoln', 'Waltham', 'Easton', 'Perham', 'Rangeley Plt.', 'Ogunquit', 'Woodville', 'Kingfield', 'Wayne', 'Winslow', 'Springfield', 'Medford', 'Skowhegan', 'Franklin', 'Baileyville', 'Dover-Foxcroft', 'Crawford', 'Coplin Plt.', 'Canton', 'North Berwick', 'Belfast', 'Upton', 'Cumberland', 'Bowdoin', 'Waldoboro', 'Brunswick', 'Sidney', 'Sumner', 'Winn', 'Guilford', 'Grand Isle', 'Lincoln Plt.', 'Old Orchrd Bch', 'Eliot', 'Litchfield', 'Rumford', 'Warren', 'Shapleigh', 'Poland', 'Eagle Lake', 'Hermon', 'Hallowell', 'Greenville', 'North Haven', 'Carmel', 'Frankfort', 'Cutler', 'Windsor', 'Hiram', 'Monson', 'Washington Cty Townships', 'Rockland', 'Topsham', 'Eastport', 'Naples', 'Fort Kent', 'Hancock Cty Townships', 'Kennebunkport', 'Stockholm', 'Penobscot County', 'Pownal', 'Thomaston', 'Newfield', "Swan's Island", 'Hodgdon', 'Aroostook Cty Townships', 'Boothbay Harbor', 'Talmadge', 'St. Albans', 'Winter Harbor', 'Jay', 'Cranberry Isles', 'Glenburn', 'Harpswell', 'Corinth', 'Hudson', 'Farmingdale', 'Beaver Cove', 'Alfred', 'Wellington', 'Madison', 'Columbia Falls', 'Houlton', 'Chelsea', 'Sweden', 'Garfield Plt.', 'Weston', 'New Sharon', 'Penobscot Cty Townships', 'Mattawamkeag', 'Milo', 'Stow', 'Magalloway Plt.', 'Yarmouth', 'Arundel', 'Hersey', 'Sabattus', 'Oxbow Plt.', 'Chester', 'West Bath', 'Fryeburg', 'Cape Elizabeth', 'Kittery', 'Cushing', 'Byron', 'Brownfield', 'Sullivan', 'Eustis', 'China', 'Cumberland County', 'Mapleton', 'Webster Plt.', 'Passadumkeag', 'Morrill', 'Parsonsfield', 'New Portland', 'Verona', 'Mount Desert', 'Arrowsic', 'Milbridge', 'North Yarmouth', 'Windham', 'Milford', 'Troy', 'Grand Lake Stream Plt', 'Camden', 'Northport', 'Hope', 'Matinicus Isle Plt.', 'Caswell', 'Vinalhaven', 'Palmyra', 'Portland', 'Frenchboro', 'Oxford Cty Townships', 'Cyr Plt.', 'Montville', 'Damariscotta', 'Perry', 'Bethel', 'Oakland', 'Norway', 'Gardiner', 'Brooks', 'Jackson', 'Charleston', 'Augusta', 'Abbot', 'Lowell', 'Hartland', 'Livermore Falls', 'Brighton Plt.', 'Freeport', 'Hollis', 'Lamoine', 'Merrill', 'Maxfield', 'Oxford', 'Penobscot', 'Aroostook County', 'Mariaville', 'Willimantic', 'Island Falls', 'Moose River', 'Danforth', 'Frye Island', 'Pembroke', 'Fort Fairfield', 'Waite', 'Bingham', 'Monroe', 'Bridgewater', 'South Portland', 'Albion', 'Blaine', 'Whiting', 'Enfield', 'Moscow', 'Appleton', 'Dennistown Plt.', 'Washington', 'Newburgh', 'Wade', 'Calais', 'Exeter', 'Canaan', 'Brooksville', 'Stonington', 'Littleton', 'Lisbon', 'Sebago', 'Rangeley', 'Brooklin', 'Stacyville', 'Waldo', 'Gorham', 'Dedham', 'Castine', 'Nobleboro', 'Newport', 'Biddeford', 'Readfield', 'Norridgewock', 'Raymond', 'Scarborough', 'Georgetown', 'Southport', 'Randolph', 'Limington', 'Vassalboro', 'Stoneham', 'Cambridge', 'Kennebunk', 'Cooper', 'Clifton', 'Searsmont', 'Dixfield', 'Detroit', 'Kennebec County', 'Winterport', 'Highland Plt.', 'Union', 'Mechanic Falls', 'Columbia', 'Liberty', 'Carthage', 'Parkman', 'Marshfield', 'Van Buren', 'Roque Bluffs', 'Cornish', 'East Machias', 'St. George', 'Glenwood Plt.', 'Durham', 'Hancock', 'Gilead', 'Frenchville', 'Southwest Harbor', 'Crystal', 'Saint Agatha', 'Waterville', 'Edgecomb', 'Porter', 'Hampden', 'Alton', 'Acton', 'Baldwin', 'Wiscasset', 'Medway', 'Eddington', 'Jonesboro', 'Westfield', 'Winthrop', 'Haynesville', 'Madawaska', 'New Limerick', 'Machiasport', 'Chesterville', 'Amity', 'Greenwood', 'West Paris', 'Clinton', 'Mount Vernon', 'Mount Chase', 'Jonesport', 'Etna', 'Orland', 'South Berwick', 'Monhegan Plt.', 'Livermore', 'Leeds', 'Dresden', 'Burnham', 'Masardis', 'Avon', 'Atkinson', 'Bowdoinham', 'Howland', 'Sanford', 'Deer Isle', 'Richmond', 'Somerville', 'Newry', 'Belgrade', 'Harmony', 'Pittsfield', 'Aurora', 'Steuben', 'Addison', 'Sandy River Plt.', 'St. John Plt.']
state Maryland is not available in senate election data so excluding
Massachusetts State has discrepancies Please verify:
['Whately', 'Hanover', 'Westwood', 'Adams', 'Walpole', 'Nantucket County', 'Plainville', 'Athol', 'Hardwick', 'Montgomery', 'Hampshire County', 'Lancaster', 'Belchertown', 'Blandford', 'Holyoke', 'Framingham', 'Southwick', 'Kingston', 'Lee', 'Billerica', 'Seekonk', 'Lawrence', 'Princeton', 'Plympton', 'Nahant', 'Shutesbury', 'New Marlborough', 'Wayland', 'Newbury', 'North Attleborough', 'West Newbury', 'Northampton', 'Stoughton', 'Huntington', 'West Boylston', 'Orange', 'Hamilton', 'Rockport', 'Dover', 'Holland', 'Maynard', 'Norton', 'Cheshire', 'Ludlow', 'Brockton', 'Wareham', 'Boylston', 'Shrewsbury', 'Fall River', 'Chesterfield', 'Hampden County', 'Woburn', 'Dudley', 'Dennis', 'Sheffield', 'Otis', 'Northborough', 'Nantucket', 'Wakefield', 'Longmeadow', 'Granville', 'Wilmington', 'Falmouth', 'Swansea', 'Townsend', 'Wellfleet', 'Essex County', 'Worcester County', 'Greenfield', 'Eastham', 'Boxborough', 'Blackstone', 'Methuen', 'Lakeville', 'Gosnold', 'Sunderland', 'Phillipston', 'Andover', 'Arlington', 'Stockbridge', 'Rutland', 'Belmont', 'Beverly', 'Malden', 'Ashburnham', 'Springfield', 'Easthampton', 'Franklin', 'Provincetown', 'Canton', 'Salem', 'Paxton', 'Egremont', 'Tyringham', 'Sharon', 'Worcester', 'Marblehead', 'Sterling', 'Windsor', 'Colrain', 'North Andover', 'Monson', 'Brookline', 'Wrentham', 'Rockland', 'Millville', 'Raynham', 'Saugus', 'Hadley', 'Gloucester', 'Hudson', 'Abington', 'East Longmeadow', 'Concord', 'Hull', 'Uxbridge', 'Barnstable County', 'Chelsea', 'Winchendon', 'Chatham', 'Fairhaven', 'Chester', 'Berlin', 'Granby', 'Westborough', 'Clarksburg', 'Chilmark', 'Holliston', 'Wenham', 'Becket', 'Edgartown', 'Needham', 'Merrimac', 'Webster', 'Medfield', 'Dukes County', 'Orleans', 'Hopedale', 'Russell', 'West Bridgewater', 'Leverett', 'Lexington', 'East Bridgewater', 'Westford', 'Pembroke', 'Monroe', 'Mount Washington', 'Lynnfield', 'Holbrook', 'Great Barrington', 'Hingham', 'Halifax', 'Newton', 'Peabody', 'West Brookfield', 'Natick', 'Bourne', 'Melrose', 'Norwell', 'Bellingham', 'Plymouth County', 'Georgetown', 'Bedford', 'Randolph', 'Stoneham', 'Mashpee', 'Ipswich', 'Scituate', 'Ayer', 'Wilbraham', 'Hancock', 'Bristol County', 'Rowley', 'Chicopee', 'Savoy', 'Somerset', 'Middlefield', 'Medway', 'Warwick', 'Westfield', 'Wellesley', 'Lunenburg', 'Rowe', 'North Reading', 'Dighton', 'Deerfield', 'Amherst', 'Mansfield', 'Peru', 'Douglas', 'Tisbury', 'Mattapoisett', 'New Ashford', 'Taunton', 'Northfield', 'Swampscott', 'Middleton', 'Oak Bluffs', 'Pelham', 'Bolton', 'Tewksbury', 'Wales', 'Franklin County', 'Revere', 'Brewster', 'Goshen', 'Boston', 'Burlington', 'Middlesex County', 'Holden', 'Leicester', 'Haverhill', 'Carver', 'Mendon', 'Dracut', 'Conway', 'East Brookfield', 'Marion', 'Florida', 'Ashland', 'Lynn', 'Oakham', 'Gill', 'Topsfield', 'Foxborough', 'Southampton', 'Auburn', 'Harvard', 'Tolland', 'Manchester', 'Shirley', 'New Braintree', 'Sandwich', 'Wendell', 'Ashby', 'Hopkinton', 'Sandisfield', 'Grafton', 'Groton', 'Tyngsborough', 'Acushnet', 'Westminster', 'West Springfield', 'Agawam', 'Marlborough', 'Aquinnah', 'Shelburne', 'Hinsdale', 'Southborough', 'Charlton', 'Sudbury', 'Westport', 'Plymouth', 'Millis', 'Buckland', 'Lincoln', 'Waltham', 'Easton', 'Newburyport', 'Medford', 'Norfolk County', 'Upton', 'Milton', 'Monterey', 'Berkley', 'Petersham', 'Pepperell', 'Northbridge', 'Berkshire County', 'Duxbury', 'Brimfield', 'Warren', 'Boxford', 'Attleboro', 'Williamstown', 'Cohasset', 'Barre', 'Quincy', 'Barnstable', 'Brookfield', 'Charlemont', 'New Salem', 'Norfolk', 'Royalston', 'Gardner', 'Erving', 'Westhampton', 'Essex', 'Bernardston', 'Rehoboth', 'West Stockbridge', 'Salisbury', 'Weston', 'Leominster', 'Dunstable', 'Stow', 'Sherborn', 'Winchester', 'Yarmouth', 'North Adams', 'Palmer', 'Danvers', 'Whitman', 'Spencer', 'Weymouth', 'Fitchburg', 'West Tisbury', 'Braintree', 'Amesbury', 'Milford', 'Montague', 'Southbridge', 'Williamsburg', 'Reading', 'Leyden', 'Ashfield', 'Lowell', 'Oxford', 'Everett', 'Norwood', 'North Brookfield', 'Dalton', 'Bridgewater', 'Templeton', 'Hatfield', 'Washington', 'Heath', 'Hanson', 'Littleton', 'New Bedford', 'Lanesborough', 'Dedham', 'Cummington', 'Groveland', 'Sutton', 'Cambridge', 'Hawley', 'South Hadley', 'Chelmsford', 'Alford', 'Marshfield', 'Ware', 'Suffolk County', 'Middleborough', 'Worthington', 'Hampden', 'Acton', 'Watertown', 'Rochester', 'Freetown', 'Harwich', 'Winthrop', 'Hubbardston', 'Clinton', 'Dartmouth', 'Carlisle', 'Lenox', 'Avon', 'Truro', 'Richmond', 'Somerville', 'Pittsfield', 'Plainfield', 'Millbury', 'Sturbridge']
Minnesota State has discrepancies Please verify:
['Lac Qui Parle County', 'Lac qui Parle County']
state Missouri is not available in senate election data so excluding
state Nevada is not available in senate election data so excluding
New Hampshire State has discrepancies Please verify:
['Sugar Hill', 'Merrimack', 'Alexandria', 'Stewartstown', 'Sharon', 'Hanover', 'Amherst', 'Merrimack County', 'Deerfield', 'Tamworth', 'Harrisville', 'Litchfield', 'Brentwood', 'Campton', 'Newfields', 'Walpole', 'Warren', 'Holderness', 'Henniker', 'Hillsborough', 'Grantham', 'New Hampton', 'Eaton', 'Croydon', 'Greenville', 'Freedom', 'Lancaster', 'Antrim', 'Bath', 'Woodstock', 'Windsor', 'Farmington', 'Brookline', 'Northfield', 'Stoddard', 'Middleton', 'Brookfield', 'Coos County', 'Pelham', 'Lebanon', 'Newington', 'Chichester', 'Hampton', 'Wilton', 'Gilmanton', 'Hudson', 'Warner', 'Jefferson', 'Concord', 'Kingston', 'Temple', 'Lee', 'Goshen', 'Hill', 'Cheshire County', 'Madison', 'New Castle', 'Northumberland', 'Salisbury', 'Whitefield', 'Bartlett', 'Allenstown', 'Rollinsford', 'Winchester', 'Langdon', 'Canterbury', 'Chatham', 'Lyman', 'Peterborough', 'Newbury', 'Jaffrey', 'Moultonborough', 'Effingham', 'Orford', 'Chester', 'Berlin', 'Lempster', 'Strafford County', 'East Kingston', 'Gilsum', 'Haverhill', 'Millsfield', 'Lyme', 'Hillsborough County', 'Wilmot', 'Orange', 'Fitzwilliam', 'Epsom', 'Rockingham County', 'Deering', 'Sullivan', 'Mont Vernon', 'Dover', 'Roxbury', 'Wentworth', 'Conway', 'Milan', 'Benton', 'Barnstead', 'New Durham', 'Dublin', 'Colebrook', 'Madbury', 'Charlestown', 'Albany', 'Sanbornton', 'Windham', 'Milford', 'Troy', 'Ellsworth', 'Stratford', 'Ashland', 'Nashua', 'Webster', 'Candia', 'Grafton County', 'Weare', 'Chesterfield', 'Fremont', 'Bradford', 'Westmoreland', 'Piermont', 'Jackson', 'Center Harbor', 'Hollis', 'Portsmouth', 'Danbury', 'Wakefield', 'Auburn', 'Thornton', 'Nelson', 'Pittsburg', 'Sullivan County', 'Newmarket', 'Pembroke', 'Dalton', 'Manchester', 'Bridgewater', 'Monroe', 'Stark', 'Hampton Falls', 'Enfield', 'Bennington', 'Sunapee', 'Sandwich', 'Carroll', 'Tuftonboro', 'Claremont', 'Washington', 'Meredith', 'Boscawen', 'Bow', "Wentworth's Location", 'Hopkinton', 'Exeter', 'Canaan', 'Littleton', 'Lisbon', 'Newton', 'Grafton', 'Epping', 'Strafford', 'Ossipee', 'Dunbarton', 'Barrington', 'New London', 'Gorham', 'Groton', 'Newport', 'Surry', 'Sandown', 'Alstead', 'Laconia', 'Greenfield', 'Tilton', 'Dixville', 'Mason', 'Gilford', 'Swanzey', 'Sutton', 'Francestown', 'Raymond', 'Carroll County', 'Nottingham', 'Londonderry', 'Randolph', 'Bedford', 'Somersworth', 'Landaff', 'Wolfeboro', 'Unity', 'Acworth', 'Danville', 'Marlborough', 'Columbia', 'Marlow', 'Shelburne', 'Errol', 'Loudon', 'Seabrook', 'Hinsdale', 'Belknap County', 'Cornish', 'Clarksville', 'Durham', 'Hancock', 'New Ipswich', 'Andover', 'Derry', 'Bristol', 'Waterville', 'Rumney', 'Alton', 'Goffstown', 'Hebron', 'Rochester', 'Plymouth', 'New Boston', 'South Hampton', 'Belmont', 'Franconia', 'Plaistow', 'Lincoln', 'Easton', 'Bethlehem', 'Hooksett', 'Harts Location', 'Springfield', 'Keene', 'Atkinson', 'Franklin', 'Kensington', 'Dummer', 'Richmond', 'North Hampton', 'Rindge', 'Pittsfield', 'Northwood', 'Stratham', 'Greenland', 'Plainfield', 'Milton', 'Rye', 'Lyndeborough', 'Salem', 'Dorchester', 'Hampstead']
New Mexico State has discrepancies Please verify:
['Do�a Ana County', 'Doña Ana County']
state New York is not available in senate election data so excluding
state North Dakota is not available in senate election data so excluding
state Ohio is not available in senate election data so excluding
state Pennsylvania is not available in senate election data so excluding
Rhode Island State has discrepancies Please verify:
['Newport County', 'West Warwick', 'Portsmouth', 'Warren', 'Providence County', 'Jamestown', 'Smithfield', 'Washington County', 'East Greenwich', 'Little Compton', 'Woonsocket', 'Providence', 'Hopkinton', 'Exeter', 'North Kingstown', 'South Kingstown', 'Barrington', 'Newport', 'Glocester', 'Central Falls', 'North Smithfield', 'Middletown', 'Tiverton', 'Cranston', 'Foster', 'Westerly', 'North Providence', 'West Greenwich', 'Scituate', 'Bristol County', 'Johnston', 'Bristol', 'New Shoreham', 'Warwick', 'Narragansett', 'Lincoln', 'Burrillville', 'Charlestown', 'Kent County', 'East Providence', 'Richmond', 'Coventry', 'Pawtucket', 'Cumberland']
state Utah is not available in senate election data so excluding
state Vermont is not available in senate election data so excluding
Virginia State has discrepancies Please verify:
['Williamsburg city', 'Mathews County', 'Richmond city', 'Suffolk City', 'Norfolk city', 'Williamsburg City', 'Virginia Beach City', 'Virginia Beach city', 'Manassas City', 'Danville city', 'Manassas city', 'Harrisonburg city', 'Alexandria city', 'Charlottesville city', 'Fredericksburg city', 'Newport News city', 'Fredericksburg City', 'Richmond City', 'Chesapeake City', 'Norfolk City', 'Chesapeake city', 'Portsmouth City', 'Alexandria City', 'Newport News City', 'Charlottesville City', 'Suffolk city', 'Matthews County', 'Danville City', 'Harrisonburg City', 'Portsmouth city']
state Washington is not available in senate election data so excluding
state Wisconsin is not available in senate election data so excluding

After assessing the above states manually to see if we can clean and transform the data so that we can merge our covid data with election data related to those states. These are the key points we found

1. The below list of states has no information available in senate data so they will be exculded for senate election analysis

```
    California
    Connecticut
    District of Columbia
    Florida
    Indiana
    Maryland
    Misouri
    Nevada
    New York
    North Dakota
    Ohio
    Pennsylvania
    Utah
    Vermont
    Washington
    Wisconsin
```

2. The below list of states can be rectified with small name corrections
or dropping those specific counties or merging with related county name

```
Colarado
Illinois
Louisiana 
Minnesota
New Mexico
```
3. The below list of states has city names in senate data. Which needs to be merged/transformed to county names

```
Maine
Massachusetts
New Hampshire
Rhode Island
```

4. ***Virginia*** The data is consistent but there are case errors in city names. Which needs to cleaned

5. ***Alaska*** has no counties. And for election purpose they divided the boroughs into 40 electoral districts. Which is tough for us here to divide and merge. So we are removing Alaska Data

### Preparing Senate dataset to merge with covid dataset

In [ ]:
senate_merge_data = senate_county.copy()

In [ ]:
senate_merge_data.head()

      state             county  current_votes  total_votes  percent
0  Delaware        Kent County          84975        87025      100
1  Delaware  New Castle County         279462       287633      100
2  Delaware      Sussex County         126498       129352      100
3   Georgia     Appling County           8187         8341      100
4   Georgia    Atkinson County           3097         3155      100

The percentage in this data is not accurate. Let us clean it.

In [ ]:
senate_merge_data['percent'] = round((senate_merge_data['current_votes']/senate_merge_data['total_votes'])*100,2)

In [ ]:
senate_merge_data.head()

      state             county  current_votes  total_votes  percent
0  Delaware        Kent County          84975        87025    97.64
1  Delaware  New Castle County         279462       287633    97.16
2  Delaware      Sussex County         126498       129352    97.79
3   Georgia     Appling County           8187         8341    98.15
4   Georgia    Atkinson County           3097         3155    98.16

Let us merge this dataset with the winner data and his winning vote count/percent

In [ ]:
senate_county_candidate.head()

      state             county      candidate party  total_votes
0  Delaware        Kent County  Lauren Witzke   REP        38571
1  Delaware        Kent County    Mark Turley   IPD         1553
2  Delaware        Kent County   Nadine Frost   LIB          958
3  Delaware  New Castle County  Lauren Witzke   REP        80081
4  Delaware  New Castle County    Mark Turley   IPD         4277

In the data head we see the Delaware Kent County current_votes is 84975 where as the sum of total Kent County is around 40k. Let us verify the data for a single county

In [ ]:
def get_county_votes_diff_data(state, county):
  polled_votes = senate_merge_data[(senate_merge_data['state']==state) & (senate_merge_data['county']==county)]['current_votes'].item()
  candidate_total_votes = senate_county_candidate[(senate_county_candidate['state']==state) & (senate_county_candidate['county']==county)].groupby(by=['state','county'])['total_votes'].sum().item()
  return polled_votes-candidate_total_votes

In [ ]:
print(f"Delaware Kent County vote diff: {get_county_votes_diff_data('Delaware','Kent County')}")
print(f"Alabama Cullman County vote diff: {get_county_votes_diff_data('Alabama','Cullman County')}")

Delaware Kent County vote diff: 43893
Alabama Cullman County vote diff: 35949

When verified this data online we see that the winner of the senate for Delaware Kent County got 43893 votes and Alabama Cullman County got 35949 votes. So this senate_county_candidate dataset has candidates who lost the elections. So We need to replace the winner votes by summing the loser's votes and getting the party name which is not listed. As in US most of the areas will have either Democratic Leader or Republic Leader. We will just check for those party names. So there can be minor errors in the data where both these party names appear and if the winner is an independent

In [ ]:
senate_merge_data.duplicated(subset=['state','county']).sum()

159

In [ ]:
senate_merge_data[senate_merge_data.duplicated(subset=['state','county'])]

        state            county  current_votes  total_votes  percent
3423  Georgia    Appling County           8159         8341    97.82
3424  Georgia   Atkinson County           2995         3155    94.93
3425  Georgia      Bacon County           4512         4668    96.66
3426  Georgia      Baker County           1514         1555    97.36
3427  Georgia    Baldwin County          17942        18251    98.31
...       ...               ...            ...          ...      ...
3577  Georgia  Whitfield County          35593        36746    96.86
3578  Georgia     Wilcox County           3218         3281    98.08
3579  Georgia     Wilkes County           4905         5029    97.53
3580  Georgia  Wilkinson County           4689         4770    98.30
3581  Georgia      Worth County           9129         9286    98.31

[159 rows x 5 columns]

In [ ]:
senate_merge_data[senate_merge_data.duplicated(subset=['state','county'])]['state'].value_counts()

Georgia    159
Name: state, dtype: int64

Georgia has unique style of senate elections. Where same county is part of different electoral districts. So Analyzing this state in our approach is not possible. So we will eliminate Georgia from senate election analysis

In [ ]:
senate_merge_data = senate_merge_data[senate_merge_data['state']!='Georgia']
senate_county_candidate = senate_county_candidate[senate_county_candidate['state']!='Georgia']

In [ ]:
senate_merge_data[senate_merge_data.duplicated(subset=['state','county'])]

Empty DataFrame
Columns: [state, county, current_votes, total_votes, percent]
Index: []

In [ ]:
senate_merge_data.head()

        state             county  current_votes  total_votes  percent
0    Delaware        Kent County          84975        87025    97.64
1    Delaware  New Castle County         279462       287633    97.16
2    Delaware      Sussex County         126498       129352    97.79
162     Idaho         Ada County         258014       259389    99.47
163     Idaho       Adams County           1561         2586    60.36

In [ ]:
senate_merge_data['Winning_Party'] = ''
senate_merge_data['Winner_Votes'] = 0

<ipython-input-108-6239c2dd0a37>:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

<ipython-input-108-6239c2dd0a37>:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
senate_merge_data.head()

,state,county,current_votes,total_votes,percent,Winning_Party,Winner_Votes
0,Delaware,Kent County,84975,87025,97.64,,0
1,Delaware,New Castle County,279462,287633,97.16,,0
2,Delaware,Sussex County,126498,129352,97.79,,0
162,Idaho,Ada County,258014,259389,99.47,,0
163,Idaho,Adams County,1561,2586,60.36,,0

In [ ]:
senate_county_candidate.head()

      state             county      candidate party  total_votes
0  Delaware        Kent County  Lauren Witzke   REP        38571
1  Delaware        Kent County    Mark Turley   IPD         1553
2  Delaware        Kent County   Nadine Frost   LIB          958
3  Delaware  New Castle County  Lauren Witzke   REP        80081
4  Delaware  New Castle County    Mark Turley   IPD         4277

In [ ]:
 def add_winner_and_votes(row):
  total_loser_votes = senate_county_candidate[(senate_county_candidate['state']==row['state'])&(senate_county_candidate['county']==row['county'])].groupby(by=['state','county'])['total_votes'].sum().item()
  loss_party_list = senate_county_candidate[(senate_county_candidate['state']==row['state'])&(senate_county_candidate['county']==row['county'])]['party'].to_list()
  if 'REP' not in loss_party_list:
    winner_party = 'REP'
  elif 'DEM' not in loss_party_list:
    winner_party = 'DEM'
  else:
    winner_party = 'OTHER'
  row['Winning_Party'] = winner_party
  row['Winner_Votes'] = row['current_votes'] - total_loser_votes
  return row

In [ ]:
senate_merge_data = senate_merge_data.apply(add_winner_and_votes,axis=1)

In [ ]:
senate_merge_data.head()

,state,county,current_votes,total_votes,percent,Winning_Party,Winner_Votes
0,Delaware,Kent County,84975,87025,97.64,DEM,43893
1,Delaware,New Castle County,279462,287633,97.16,DEM,191774
2,Delaware,Sussex County,126498,129352,97.79,REP,67402
162,Idaho,Ada County,258014,259389,99.47,REP,130446
163,Idaho,Adams County,1561,2586,60.36,REP,828

####Cleaning county names in Senate_merge_data to match covid dataset

In [ ]:
#Renaming 'Broomfield County and City' to 'Broomfield County' in county_data
idx = merge_covid_dataset.index[merge_covid_dataset['County_Name']=='Broomfield County and City']
merge_covid_dataset.loc[idx,'County_Name'] = 'Broomfield County'
merge_covid_dataset[merge_covid_dataset['County_Name'].str.contains('Broomfield')]

/usr/local/lib/python3.8/dist-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,countyFIPS,County_Name,State,population,Total_Covid_Cases_Till_Election,Total_Covid_Deaths_Till_Election
253,8014,Broomfield County,CO,70465,1041.0,42.0

In [ ]:
# Illinois State has discrepancies Please verify:
# ['Cook Suburbs']
merge_covid_dataset[merge_covid_dataset['County_Name'].str.contains('Cook') & merge_covid_dataset['State'].str.contains('IL')]

,countyFIPS,County_Name,State,population,Total_Covid_Cases_Till_Election,Total_Covid_Deaths_Till_Election
612,17031,Cook County,IL,5150233,189660.0,5485.0

In [ ]:
senate_merge_data[senate_merge_data['county'].str.contains('Cook') & senate_merge_data['state'].str.contains('Illinois')]

,state,county,current_votes,total_votes,percent,Winning_Party,Winner_Votes
221,Illinois,Cook County,2289749,2417649,94.71,DEM,1574685
308,Illinois,Cook Suburbs,1158720,1221698,94.85,DEM,726423

Sum of total votes for Cook County and Cook Suburbs is less than population in Cook County of covid dataset. So merging these two rows

In [ ]:
idx1 = senate_merge_data.index[senate_merge_data['county'].str.contains('Cook County') & senate_merge_data['state'].str.contains('Illinois')].item()
idx2 = senate_merge_data.index[senate_merge_data['county'].str.contains('Cook Suburbs') & senate_merge_data['state'].str.contains('Illinois')].item()

In [ ]:
# For ease, we will add the current_votes, and total_votes of these rows to Cook County and drop Cook Suburbs
senate_merge_data.loc[idx1,'current_votes'] += senate_merge_data.loc[idx2,'current_votes']
senate_merge_data.loc[idx1,'total_votes'] += senate_merge_data.loc[idx2,'total_votes']
senate_merge_data.loc[idx1,'Winner_Votes'] += senate_merge_data.loc[idx2,'Winner_Votes']

In [ ]:
senate_merge_data[senate_merge_data['county'].str.contains('Cook') & senate_merge_data['state'].str.contains('Illinois')]

,state,county,current_votes,total_votes,percent,Winning_Party,Winner_Votes
221,Illinois,Cook County,3448469,3639347,94.71,DEM,2301108
308,Illinois,Cook Suburbs,1158720,1221698,94.85,DEM,726423

In [ ]:
senate_merge_data.drop(idx2,inplace=True)

In [ ]:
senate_merge_data[senate_merge_data['county'].str.contains('Cook') & senate_merge_data['state'].str.contains('Illinois')]

,state,county,current_votes,total_votes,percent,Winning_Party,Winner_Votes
221,Illinois,Cook County,3448469,3639347,94.71,DEM,2301108

In [ ]:
# Louisiana State has discrepancies Please verify:
# ['La Salle Parish', 'LaSalle Parish']
#Renaming the value in covid datset
idx = merge_covid_dataset.index[merge_covid_dataset['County_Name']=='La Salle Parish']
merge_covid_dataset.loc[idx,'County_Name'] = 'LaSalle Parish'
merge_covid_dataset[merge_covid_dataset['County_Name'].str.contains('Salle')]

/usr/local/lib/python3.8/dist-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,countyFIPS,County_Name,State,population,Total_Covid_Cases_Till_Election,Total_Covid_Deaths_Till_Election
646,17099,LaSalle County,IL,108669,2736.0,69.0
1144,22059,LaSalle Parish,LA,14892,517.0,10.0
2666,48283,La Salle County,TX,7520,381.0,15.0

In [ ]:
# Minnesota State has discrepancies Please verify:
# ['Lac qui Parle County', 'Lac Qui Parle County']
idx = senate_merge_data.index[senate_merge_data['county']=='Lac qui Parle County']
senate_merge_data.loc[idx,'county'] = 'Lac Qui Parle County'
senate_merge_data[senate_merge_data['county'].str.contains('Parle')]

,state,county,current_votes,total_votes,percent,Winning_Party,Winner_Votes
1665,Minnesota,Lac Qui Parle County,3982,4266,93.34,REP,2314

In [ ]:
# New Mexico State has discrepancies Please verify:
# ['Doña Ana County', 'Do�a Ana County']
idx = senate_merge_data.index[senate_merge_data['county'].str.contains('Ana County')]
senate_merge_data.loc[idx,'county'] = 'Doña Ana County'
senate_merge_data[senate_merge_data['county'].str.contains('Ana County')]

,state,county,current_votes,total_votes,percent,Winning_Party,Winner_Votes
2212,New Mexico,Doña Ana County,81506,82641,98.63,DEM,46918

Cleaning Virginia data in both senate data and covid data

In [ ]:
senate_merge_data['county'] = senate_merge_data['county'].apply(lambda x: x.replace(' city', ' City'))
merge_covid_dataset['County_Name'] = merge_covid_dataset['County_Name'].apply(lambda x: x.replace(' city', ' City'))

<ipython-input-125-eb61c913f981>:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
#Checking for County Name discrepancies for latest datasets
def get_different_county_names1(state_name):
  senate_county_names_list = senate_merge_data[senate_merge_data['state']==state_name]['county'].to_list()
  covid_dataset_county_names_list = merge_covid_dataset[merge_covid_dataset['State']==str(state_abbreviations_df[state_abbreviations_df['State']==state_name]['Abbreviation'].item())]['County_Name'].to_list()
  return list(set(senate_county_names_list).symmetric_difference(set(covid_dataset_county_names_list)))
get_different_county_names1('Virginia')

['Mathews County', 'Matthews County']

In [ ]:
merge_covid_dataset[merge_covid_dataset['County_Name'] == 'Matthews County']

,countyFIPS,County_Name,State,population,Total_Covid_Cases_Till_Election,Total_Covid_Deaths_Till_Election
2878,51115,Matthews County,VA,8834,137.0,0.0

In [ ]:
idx = merge_covid_dataset.index[merge_covid_dataset['County_Name'] == 'Matthews County']
merge_covid_dataset.loc[idx,'County_Name'] = 'Mathews County'

/usr/local/lib/python3.8/dist-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
get_different_county_names1('Virginia')

[]

Cleaning of the 5 states that needs county name changes. Now for the states where city names were given instead of counties, the data for cities and their associated counties is collected from the following websites

https://www.sec.state.ma.us/cis/cisctlist/ctlistcoun.htm

https://www.nh.gov/osi/resource-library/municipalities.htm

https://en.wikipedia.org/wiki/List_of_municipalities_in_Rhode_Island


https://en.wikipedia.org/wiki/List_of_municipalities_in_Maine

This csv will be used to transform the city related data to county data

In [ ]:
senate_merge_data[senate_merge_data['state'].isin(['Maine','Massachusetts','New Hampshire', 'Rhode Island'])]

,state,county,current_votes,total_votes,percent,Winning_Party,Winner_Votes
697,Maine,Aroostook Cty Townships,290,292,99.32,REP,175
698,Maine,Franklin Cty Townships,52,52,100.00,DEM,26
699,Maine,Hancock Cty Townships,13,13,100.00,DEM,5
700,Maine,Oxford Cty Townships,325,333,97.60,REP,184
701,Maine,Penobscot Cty Townships,506,506,100.00,REP,363
...,...,...,...,...,...,...,...
2485,Rhode Island,Charlestown,4984,5193,95.98,DEM,3044
2486,Rhode Island,Coventry,19228,19915,96.55,DEM,10440
2487,Rhode Island,Cranston,39498,40851,96.69,DEM,25591
2488,Rhode Island,Cumberland,18729,19576,95.67,DEM,11640
2489,Rhode Island,East Greenwich,8444,8574,98.48,DEM,5451

In [ ]:
#Reading the newly created dataset
city_county_dataset = pd.read_csv('/content/drive/Shareddrives/605-DataScience/DS_Project_Stage1/Additional_Resources/city_county.csv')
city_county_dataset.head()

               City             County        State
0      North Canaan  Litchfield County  Connecticut
1       North Haven   New Haven County  Connecticut
2  North Stonington  New London County  Connecticut
3           Norwalk   Fairfield County  Connecticut
4           Norwich  New London County  Connecticut

In [ ]:
def transform_county_names(x):
  if x['state'] in ['Maine','Massachusetts','New Hampshire', 'Rhode Island']:
    output = city_county_dataset[(city_county_dataset['State'] == x['state']) & (city_county_dataset['City'] == x['county'])]['County']
    x['county'] = output.item() if len(output)==1 else x['county']
  return x

In [ ]:
senate_merge_data = senate_merge_data.apply(transform_county_names, axis=1)

In [ ]:
# Verifying the data for an example county
senate_merge_data[senate_merge_data['county']=='Lincoln County']

,state,county,current_votes,total_votes,percent,Winning_Party,Winner_Votes
193,Idaho,Lincoln County,1931,1940,99.54,REP,1371
460,Kansas,Lincoln County,1559,1686,92.47,REP,1200
581,Kentucky,Lincoln County,10893,10914,99.81,REP,7820
922,Maine,Lincoln County,522,522,100.00,DEM,264
923,Maine,Lincoln County,2213,2213,100.00,REP,1120
924,Maine,Lincoln County,1400,1400,100.00,REP,700
925,Maine,Lincoln County,564,564,100.00,DEM,296
926,Maine,Lincoln County,2126,2126,100.00,REP,1029
927,Maine,Lincoln County,1482,1482,100.00,DEM,800
928,Maine,Lincoln County,1157,1159,99.83,REP,643
929,Maine,Lincoln County,889,889,100.00,DEM,429
930,Maine,Lincoln County,1690,1691,99.94,REP,1049
931,Maine,Lincoln County,62,62,100.00,DEM,43
932,Maine,Lincoln County,1368,1368,100.00,DEM,764
933,Maine,Lincoln County,1315,1315,100.00,REP,653
934,Maine,Lincoln County,358,358,100.00,REP,222
935,Maine,Lincoln County,719,719,100.00,DEM,361
936,Maine,Lincoln County,495,495,100.00,REP,258
937,Maine,Lincoln County,2928,2934,99.80,REP,1699
938,Maine,Lincoln County,549,551,99.64,REP,277
939,Maine,Lincoln County,1481,1481,100.00,REP,839
940,Maine,Lincoln County,2322,2322,100.00,REP,1298
1669,Minnesota,Lincoln County,3079,3343,92.10,REP,1936
1758,Mississippi,Lincoln County,16810,16818,99.95,REP,11378
1824,Montana,Lincoln County,11718,11747,99.75,REP,8490
1909,Nebraska,Lincoln County,17835,17107,104.26,REP,12679
2219,New Mexico,Lincoln County,10247,10306,99.43,REP,7102
2292,North Carolina,Lincoln County,49776,50217,99.12,REP,34673
2378,Oklahoma,Lincoln County,14833,14888,99.63,REP,11445
2435,Oregon,Lincoln County,30208,30726,98.31,DEM,17485
2576,South Dakota,Lincoln County,32234,32396,99.50,REP,21221
2653,Tennessee,Lincoln County,15108,15608,96.80,REP,12019
3105,West Virginia,Lincoln County,7619,7830,97.31,REP,5770
3150,Wyoming,Lincoln County,10306,10468,98.45,REP,8846
3317,Arkansas,Lincoln County,3800,3875,98.06,REP,2907
3388,Colorado,Lincoln County,2636,2651,99.43,REP,2141

In [ ]:
senate_merge_data[senate_merge_data.duplicated(['state','county','Winning_Party'])]

,state,county,current_votes,total_votes,percent,Winning_Party,Winner_Votes
706,Maine,Aroostook County,35,35,100.00,REP,24
707,Maine,Washington County,233,235,99.15,DEM,154
709,Maine,Androscoggin County,2803,2803,100.00,REP,1571
710,Maine,Androscoggin County,2642,2642,100.00,REP,1829
711,Maine,Androscoggin County,1362,1362,100.00,REP,896
...,...,...,...,...,...,...,...
2485,Rhode Island,Washington County,4984,5193,95.98,DEM,3044
2486,Rhode Island,Kent County,19228,19915,96.55,DEM,10440
2487,Rhode Island,Providence County,39498,40851,96.69,DEM,25591
2488,Rhode Island,Providence County,18729,19576,95.67,DEM,11640
2489,Rhode Island,Kent County,8444,8574,98.48,DEM,5451

Here we see the data is repeated since multiple cities are joined under counties and there are different winners from different cities in that county. Since we are only evaluating on a county basis, we will merge this data by grouping and then only retaining candidate with highest votes in the county

In [ ]:
senate_merge_data[senate_merge_data.duplicated(['state','county','Winning_Party'])]['state'].value_counts()

Maine            470
Massachusetts    330
New Hampshire    217
Rhode Island      32
Name: state, dtype: int64

In [ ]:
#Grouping and summing the votes for a candidate
senate_merge_data = senate_merge_data.groupby(by=['state','county','Winning_Party']).sum().reset_index()

In [ ]:
senate_merge_data[senate_merge_data['state']=='Maine']

,state,county,Winning_Party,current_votes,total_votes,percent,Winner_Votes
798,Maine,Androscoggin County,REP,58690,58883,1388.52,32979
799,Maine,Aroostook County,REP,35601,35813,6546.47,24033
800,Maine,Cumberland County,DEM,140093,140132,1398.68,83861
801,Maine,Cumberland County,REP,53956,53932,1403.43,29272
802,Maine,Franklin County,DEM,689,689,300.00,351
803,Maine,Franklin County,REP,16695,16732,1893.73,9514
804,Maine,Hancock County,DEM,12963,12982,1197.88,7276
805,Maine,Hancock County,REP,22352,22425,2565.76,12660
806,Maine,Kennebec County,DEM,9679,9687,199.90,5251
807,Maine,Kennebec County,REP,62207,62393,2688.20,35836
808,Maine,Knox County,DEM,14503,14518,799.00,8040
809,Maine,Knox County,REP,11255,11268,999.09,6293
810,Maine,Lincoln County,DEM,5606,5606,700.00,2957
811,Maine,Lincoln County,REP,18034,18045,1199.21,9787
812,Maine,Oxford County,DEM,288,299,96.32,137
813,Maine,Oxford County,REP,33134,33240,3567.96,19431
814,Maine,Penobscot County,DEM,5512,5512,200.00,3353
815,Maine,Penobscot County,REP,79696,79848,5862.98,49417
816,Maine,Piscataquis County,REP,9862,9909,1884.32,6603
817,Maine,Sagadahoc County,DEM,12899,12908,399.62,6541
818,Maine,Sagadahoc County,REP,11140,11158,599.06,6194
819,Maine,Somerset County,REP,27514,27615,3387.02,17861
820,Maine,Waldo County,DEM,7459,7462,399.33,3986
821,Maine,Waldo County,REP,16938,16964,2195.67,9810
822,Maine,Washington County,DEM,495,498,198.77,311
823,Maine,Washington County,REP,16848,16914,4375.59,11039
824,Maine,York County,DEM,67406,67470,998.63,35178
825,Maine,York County,REP,62172,62287,1896.69,35679

In [ ]:
senate_merge_data[senate_merge_data['state']=='Massachusetts']

,state,county,Winning_Party,current_votes,total_votes,percent,Winner_Votes
826,Massachusetts,Barnstable County,DEM,148732,150293,1487.07,89977
827,Massachusetts,Berkshire County,DEM,69512,71418,3119.48,51261
828,Massachusetts,Bristol County,DEM,244242,250951,1462.14,142827
829,Massachusetts,Bristol County,REP,27654,28328,488.19,14198
830,Massachusetts,Dukes County,DEM,12632,12798,692.40,9767
831,Massachusetts,Essex County,DEM,408706,415352,3255.65,264899
832,Massachusetts,Essex County,REP,5779,5858,98.65,2925
833,Massachusetts,Franklin County,DEM,41766,42378,2463.73,29877
834,Massachusetts,Franklin County,REP,59,60,98.33,35
835,Massachusetts,Hampden County,DEM,173758,178480,974.65,106194
836,Massachusetts,Hampden County,REP,38704,39681,1274.09,20420
837,Massachusetts,Hampshire County,DEM,85379,86637,1869.31,62566
838,Massachusetts,Hampshire County,REP,1201,1217,98.69,594
839,Massachusetts,Middlesex County,DEM,849577,863595,5320.49,611485
840,Massachusetts,Nantucket County,DEM,7194,7306,98.47,5132
841,Massachusetts,Norfolk County,DEM,400671,407438,2756.07,265210
842,Massachusetts,Plymouth County,DEM,235892,239808,1870.41,141150
843,Massachusetts,Plymouth County,REP,60833,62008,785.25,30841
844,Massachusetts,Suffolk County,DEM,326660,335462,384.97,266117
845,Massachusetts,Worcester County,DEM,363519,369641,4432.00,218779
846,Massachusetts,Worcester County,REP,61666,62452,1479.47,31716

In [ ]:
def get_winner_and_merged_votes(row):
  if row['state'] in ['Maine','Massachusetts','New Hampshire','Rhode Island']:
    slice_df = senate_merge_data[(senate_merge_data['state']==row['state'])&(senate_merge_data['county']==row['county'])]
    if len(slice_df) > 1:
      winner_row_idx = senate_merge_data[(senate_merge_data['state']==row['state'])&(senate_merge_data['county']==row['county'])]['Winner_Votes'].idxmax()
      return senate_merge_data.loc[winner_row_idx]
  return row

In [ ]:
senate_merge_data = senate_merge_data.apply(get_winner_and_merged_votes,axis=1) #This creates duplicate rows
senate_merge_data.drop_duplicates(inplace=True)

In [ ]:
senate_merge_data[senate_merge_data.duplicated(['state','county','Winning_Party'])]

Empty DataFrame
Columns: [state, county, Winning_Party, current_votes, total_votes, percent, Winner_Votes]
Index: []

In [ ]:
senate_merge_data.shape

(2183, 7)

In [ ]:
merge_covid_dataset.shape

(3144, 6)

For Senate Elections, we are removing some states which don't have senate elections and also Georgia, whose election way is not possible to assess in our approach. So we have to create a new covid dataset for senate to merge with

In [ ]:
senate_covid_merge_dataset = merge_covid_dataset.copy()

In [ ]:
senate_covid_merge_dataset.head()

,countyFIPS,County_Name,State,population,Total_Covid_Cases_Till_Election,Total_Covid_Deaths_Till_Election
0,1001,Autauga County,AL,55869,2159.0,30.0
1,1003,Baldwin County,AL,223234,6940.0,71.0
2,1005,Barbour County,AL,24686,1060.0,9.0
3,1007,Bibb County,AL,22394,873.0,15.0
4,1009,Blount County,AL,57826,2074.0,25.0

In [ ]:
senate_exclusion_states = ['AK', 'CA', 'CT', 'DC', 'FL', 'GA', 'HI', 'IN', 'MD', 'MO', 'NV', 'NY', 'ND', 'OH', 'PA', 'UT', 'VT', 'WA', 'WI']
senate_covid_merge_dataset = senate_covid_merge_dataset[~(senate_covid_merge_dataset['State'].isin(senate_exclusion_states))]

In [ ]:
#Dropping Alaska from senate_data
senate_merge_data = senate_merge_data[senate_merge_data['state']!='Alaska']

In [ ]:
print(f"States in covid merge data: {senate_covid_merge_dataset['State'].nunique()}")
print(f"Shape of covid merge data: {senate_covid_merge_dataset.shape}")

States in covid merge data: 32
Shape of covid merge data: (2143, 6)

In [ ]:
print(f"States in Senate merge data: {senate_merge_data['state'].nunique()}")
print(f"Shape of Senate merge data: {senate_merge_data.shape}")

States in Senate merge data: 32
Shape of Senate merge data: (2143, 7)

The states and data shape is matching

In [ ]:
#Checking for County Name discrepancies for latest datasets
def get_different_county_names2(state_name):
  senate_county_names_list = senate_merge_data[senate_merge_data['state']==state_name]['county'].to_list()
  covid_dataset_county_names_list = senate_covid_merge_dataset[senate_covid_merge_dataset['State']==str(state_abbreviations_df[state_abbreviations_df['State']==state_name]['Abbreviation'].item())]['County_Name'].to_list()
  return list(set(senate_county_names_list).symmetric_difference(set(covid_dataset_county_names_list)))

In [ ]:
states_list = senate_merge_data['state'].unique()
for state in states_list:
  output = get_different_county_names2(state)
  if len(output)>0:
    print(f"State Name: {state}")
    print(output)

In [ ]:
senate_covid_merge_dataset.head()

,countyFIPS,County_Name,State,population,Total_Covid_Cases_Till_Election,Total_Covid_Deaths_Till_Election
0,1001,Autauga County,AL,55869,2159.0,30.0
1,1003,Baldwin County,AL,223234,6940.0,71.0
2,1005,Barbour County,AL,24686,1060.0,9.0
3,1007,Bibb County,AL,22394,873.0,15.0
4,1009,Blount County,AL,57826,2074.0,25.0

Modify State Name

In [ ]:
def modify_state_name(row):
  row['State'] = state_abbreviations_df[state_abbreviations_df['Abbreviation']==row['State']]['State'].item()
  return row

In [ ]:
senate_covid_merge_dataset = senate_covid_merge_dataset.apply(modify_state_name,axis=1)
senate_covid_merge_dataset.head()

,countyFIPS,County_Name,State,population,Total_Covid_Cases_Till_Election,Total_Covid_Deaths_Till_Election
0,1001,Autauga County,Alabama,55869,2159.0,30.0
1,1003,Baldwin County,Alabama,223234,6940.0,71.0
2,1005,Barbour County,Alabama,24686,1060.0,9.0
3,1007,Bibb County,Alabama,22394,873.0,15.0
4,1009,Blount County,Alabama,57826,2074.0,25.0

In [ ]:
senate_merge_data.head()

,state,county,Winning_Party,current_votes,total_votes,percent,Winner_Votes
0,Alabama,Autauga County,REP,27707,27770,99.77,19387
1,Alabama,Baldwin County,REP,109350,109679,99.70,80200
2,Alabama,Barbour County,REP,10479,10518,99.63,5449
3,Alabama,Bibb County,REP,9581,9595,99.85,7320
4,Alabama,Blount County,REP,27506,27588,99.70,24163

### Merged Covid and Senate Data

In [ ]:
senate_covid_merged = pd.merge(senate_covid_merge_dataset,senate_merge_data,how='left',left_on=['County_Name','State'],right_on=['county','state'])
senate_covid_merged.drop(columns=['county','state'],inplace=True)
senate_covid_merged.head()

,countyFIPS,County_Name,State,population,Total_Covid_Cases_Till_Election,Total_Covid_Deaths_Till_Election,Winning_Party,current_votes,total_votes,percent,Winner_Votes
0,1001,Autauga County,Alabama,55869,2159.0,30.0,REP,27707,27770,99.77,19387
1,1003,Baldwin County,Alabama,223234,6940.0,71.0,REP,109350,109679,99.70,80200
2,1005,Barbour County,Alabama,24686,1060.0,9.0,REP,10479,10518,99.63,5449
3,1007,Bibb County,Alabama,22394,873.0,15.0,REP,9581,9595,99.85,7320
4,1009,Blount County,Alabama,57826,2074.0,25.0,REP,27506,27588,99.70,24163

We forgot to recalculate the percentage columns when we added the duplicate counties for Maine , Rhode Island

In [ ]:
senate_covid_merged[senate_covid_merged['State']=='Maine']

,countyFIPS,County_Name,State,population,Total_Covid_Cases_Till_Election,Total_Covid_Deaths_Till_Election,Winning_Party,current_votes,total_votes,percent,Winner_Votes
758,23001,Androscoggin County,Maine,108277,873.0,10.0,REP,58690,58883,1388.52,32979
759,23003,Aroostook County,Maine,67055,65.0,1.0,REP,35601,35813,6546.47,24033
760,23005,Cumberland County,Maine,295003,2621.0,70.0,DEM,140093,140132,1398.68,83861
761,23007,Franklin County,Maine,30199,82.0,1.0,REP,16695,16732,1893.73,9514
762,23009,Hancock County,Maine,54987,73.0,1.0,REP,22352,22425,2565.76,12660
763,23011,Kennebec County,Maine,122302,353.0,11.0,REP,62207,62393,2688.20,35836
764,23013,Knox County,Maine,39772,93.0,1.0,DEM,14503,14518,799.00,8040
765,23015,Lincoln County,Maine,34634,65.0,1.0,REP,18034,18045,1199.21,9787
766,23017,Oxford County,Maine,57975,178.0,2.0,REP,33134,33240,3567.96,19431
767,23019,Penobscot County,Maine,152148,310.0,6.0,REP,79696,79848,5862.98,49417
768,23021,Piscataquis County,Maine,16785,10.0,0.0,REP,9862,9909,1884.32,6603
769,23023,Sagadahoc County,Maine,35856,88.0,0.0,DEM,12899,12908,399.62,6541
770,23025,Somerset County,Maine,50484,193.0,8.0,REP,27514,27615,3387.02,17861
771,23027,Waldo County,Maine,39715,154.0,14.0,REP,16938,16964,2195.67,9810
772,23029,Washington County,Maine,31379,68.0,0.0,REP,16848,16914,4375.59,11039
773,23031,York County,Maine,207641,1435.0,21.0,REP,62172,62287,1896.69,35679

In [ ]:
#Recalcualting Percentage Column
senate_covid_merged['percent']= (senate_covid_merged['current_votes']/senate_covid_merged['total_votes'])*100

In [ ]:
senate_covid_merged.head()

,countyFIPS,County_Name,State,population,Total_Covid_Cases_Till_Election,Total_Covid_Deaths_Till_Election,Winning_Party,current_votes,total_votes,percent,Winner_Votes
0,1001,Autauga County,Alabama,55869,2159.0,30.0,REP,27707,27770,99.773136,19387
1,1003,Baldwin County,Alabama,223234,6940.0,71.0,REP,109350,109679,99.700034,80200
2,1005,Barbour County,Alabama,24686,1060.0,9.0,REP,10479,10518,99.629207,5449
3,1007,Bibb County,Alabama,22394,873.0,15.0,REP,9581,9595,99.854091,7320
4,1009,Blount County,Alabama,57826,2074.0,25.0,REP,27506,27588,99.702769,24163

### Preparing President's Data for merge

In [ ]:
president_county.head()

,state,county,current_votes,total_votes,percent
0,Delaware,Kent County,87025,87025,100
1,Delaware,New Castle County,287633,287633,100
2,Delaware,Sussex County,129352,129352,100
3,District of Columbia,District of Columbia,41681,41681,100
4,District of Columbia,Ward 2,32881,32881,100

In [ ]:
president_county_candidate.head()

      state             county      candidate party  total_votes    won
0  Delaware        Kent County      Joe Biden   DEM        44552   True
1  Delaware        Kent County   Donald Trump   REP        41009  False
2  Delaware        Kent County   Jo Jorgensen   LIB         1044  False
3  Delaware        Kent County  Howie Hawkins   GRN          420  False
4  Delaware  New Castle County      Joe Biden   DEM       195034   True

Tallying consistency  of the number of votes

In [ ]:
#Sum of total_votes got by each candidate in counties
president_county_candidate.groupby(['state','county'])['total_votes'].sum().reset_index()

        state             county  total_votes
0     Alabama     Autauga County        27770
1     Alabama     Baldwin County       109679
2     Alabama     Barbour County        10518
3     Alabama        Bibb County         9595
4     Alabama      Blount County        27588
...       ...                ...          ...
4628  Wyoming  Sweetwater County        16603
4629  Wyoming       Teton County        14677
4630  Wyoming       Uinta County         9402
4631  Wyoming    Washakie County         4012
4632  Wyoming      Weston County         3542

[4633 rows x 3 columns]

In [ ]:
president_county.sort_values(by=["state",'county'])

        state             county  current_votes  total_votes  percent
4155  Alabama     Autauga County          27770        27770      100
4166  Alabama     Baldwin County         109679       109679      100
4177  Alabama     Barbour County          10518        10518      100
4188  Alabama        Bibb County           9595         9595      100
4199  Alabama      Blount County          27588        27588      100
...       ...                ...            ...          ...      ...
4140  Wyoming  Sweetwater County          16603        16603      100
4141  Wyoming       Teton County          14677        14677      100
4142  Wyoming       Uinta County           9402         9402      100
4143  Wyoming    Washakie County           4012         4012      100
4144  Wyoming      Weston County           3542         3542      100

[4633 rows x 5 columns]

From the above two outputs the values are matching and the president_county_candidate has the Won Column as well. So We can directly get our winning candidate details

In [ ]:
president_county_winner = pd.DataFrame(president_county_candidate[president_county_candidate['won']==True])

In [ ]:
president_county_winner.shape

(4633, 6)

In [ ]:
president_county.shape

(4633, 5)

So the shapes are matching we can merge this two datasets to get merged president data

In [ ]:
president_merge_data = pd.merge(president_county,president_county_winner,how='left',left_on=['state','county'],right_on=['state','county'])

In [ ]:
president_merge_data.head()

,state,county,current_votes,total_votes_x,percent,candidate,party,total_votes_y,won
0,Delaware,Kent County,87025,87025,100,Joe Biden,DEM,44552,True
1,Delaware,New Castle County,287633,287633,100,Joe Biden,DEM,195034,True
2,Delaware,Sussex County,129352,129352,100,Donald Trump,REP,71230,True
3,District of Columbia,District of Columbia,41681,41681,100,Joe Biden,DEM,39041,True
4,District of Columbia,Ward 2,32881,32881,100,Joe Biden,DEM,29078,True

In [ ]:
president_merge_data.shape

(4633, 9)

In [ ]:
column_names = list(president_merge_data.columns)
column_names

['state',
 'county',
 'current_votes',
 'total_votes_x',
 'percent',
 'candidate',
 'party',
 'total_votes_y',
 'won']

In [ ]:
column_names[column_names.index('total_votes_y')] = 'Winner_Votes'
column_names[column_names.index('total_votes_x')] = 'total_votes'
president_merge_data.columns = column_names
president_merge_data.head()

,state,county,current_votes,total_votes,percent,candidate,party,Winner_Votes,won
0,Delaware,Kent County,87025,87025,100,Joe Biden,DEM,44552,True
1,Delaware,New Castle County,287633,287633,100,Joe Biden,DEM,195034,True
2,Delaware,Sussex County,129352,129352,100,Donald Trump,REP,71230,True
3,District of Columbia,District of Columbia,41681,41681,100,Joe Biden,DEM,39041,True
4,District of Columbia,Ward 2,32881,32881,100,Joe Biden,DEM,29078,True

In [ ]:
#Transforming percent just to make sure it is accurate
president_merge_data['percent'] = (president_merge_data['current_votes']/president_merge_data['total_votes'])*100

In [ ]:
president_merge_data['state'].nunique()

51

In [ ]:
president_merge_data[president_merge_data.duplicated(['state','county'])]

Empty DataFrame
Columns: [state, county, current_votes, total_votes, percent, candidate, party, Winner_Votes, won]
Index: []

In [ ]:
merge_covid_dataset.head()

,countyFIPS,County_Name,State,population,Total_Covid_Cases_Till_Election,Total_Covid_Deaths_Till_Election
0,1001,Autauga County,AL,55869,2159.0,30.0
1,1003,Baldwin County,AL,223234,6940.0,71.0
2,1005,Barbour County,AL,24686,1060.0,9.0
3,1007,Bibb County,AL,22394,873.0,15.0
4,1009,Blount County,AL,57826,2074.0,25.0

In [ ]:
merge_covid_dataset['State'].nunique()

51

In [ ]:
merge_covid_dataset.shape

(3144, 6)

The number of states in merge_covid_dataset and President_merge_data matches however the shape is different. This might be because of difference in the election places and counties. Let us convert the election regions to counties just like how we did for senate data.

In [ ]:
#Transform state names in merge covid dataset
merge_covid_dataset = merge_covid_dataset.apply(modify_state_name, axis=1)

In [ ]:
president_covid_merge_dataset = merge_covid_dataset.copy()

In [ ]:
#Checking for County Name discrepancies for latest datasets
def get_different_county_names_president(state_name):
  president_county_names_list = president_merge_data[president_merge_data['state']==state_name]['county'].to_list()
  covid_dataset_county_names_list = president_covid_merge_dataset[president_covid_merge_dataset['State']==state_name]['County_Name'].to_list()
  return list(set(president_county_names_list).symmetric_difference(set(covid_dataset_county_names_list)))

In [ ]:
covid_state_list = list(president_covid_merge_dataset['State'].unique())
president_state_list = list(president_merge_data['state'].unique())
list(set(covid_state_list).symmetric_difference(set(president_state_list)))

[]

There is no difference in the state list

In [ ]:
for state in covid_state_list:
  output = get_different_county_names_president(state)
  if len(output)>0:
    print(f"State {state} has discrepancies")
    print(output)

State Alaska has discrepancies
['ED 13', 'ED 39', 'Wrangell City and Borough', 'ED 1', 'Yakutat City and Borough', 'ED 17', 'Aleutians West Census Area', 'ED 26', 'Wade Hampton Census Area', 'ED 24', 'ED 25', 'ED 31', 'Municipality of Anchorage', 'ED 23', 'ED 38', 'Hoonah-Angoon Census Area', 'ED 36', 'ED 22', 'ED 8', 'ED 16', 'ED 12', 'ED 4', 'ED 3', 'Valdez-Cordova Census Area', 'Haines Borough', 'Northwest Arctic Borough', 'Aleutians East Borough', 'Petersburg Census Area', 'Bristol Bay Borough', 'Kenai Peninsula Borough', 'ED 34', 'Dillingham Census Area', 'North Slope Borough', 'ED 15', 'ED 27', 'Ketchikan Gateway Borough', 'Skagway Municipality', 'ED 35', 'ED 37', 'Denali Borough', 'ED 21', 'ED 7', 'Nome Census Area', 'ED 14', 'ED 29', 'Southeast Fairbanks Census Area', 'ED 18', 'Fairbanks North Star Borough', 'Kusilvak Census Area', 'Lake and Peninsula Borough', 'ED 5', 'ED 19', 'ED 2', 'ED 9', 'Bethel Census Area', 'ED 28', 'ED 32', 'Kodiak Island Borough', 'ED 33', 'Matanuska-Susitna Borough', 'Yukon-Koyukuk Census Area', 'Sitka City and Borough', 'ED 6', 'ED 30', 'ED 11', 'City and Borough of Juneau', 'Prince of Wales-Hyder Census Area', 'ED 40', 'ED 10', 'ED 20']
State California has discrepancies
['Grand Princess Cruise Ship']
State Connecticut has discrepancies
['Guilford', 'Voluntown', 'Sharon', 'Kent', 'Greenwich', 'Suffield', 'Mansfield', 'East Hampton', 'Middlebury', 'Litchfield', 'Southington', 'New Haven County', 'Wallingford', 'Warren', 'Colchester', 'Prospect', 'Killingly', 'Plainville', 'Norwich', 'West Hartford', 'East Granby', 'North Haven', 'North Branford', 'Sterling', 'Stafford', 'Windsor', 'Woodstock', 'Farmington', 'Hamden', 'Woodbury', 'Morris', 'Salem', 'Sherman', 'Brookfield', 'Thompson', 'New Hartford', 'Thomaston', 'Lebanon', 'Newington', 'Norfolk', 'Somers', 'Bolton', 'West Haven', 'Ellington', 'Wilton', 'Hampton', 'Newtown', 'North Canaan', 'Middletown', 'Essex', 'Burlington', 'Goshen', 'Madison', 'New London County', 'Middlesex County', 'North Stonington', 'Salisbury', 'Weston', 'Windsor Locks', 'Fairfield', 'Winchester', 'Rocky Hill', 'Canterbury', 'East Lyme', 'Preston', 'Hartford', 'Ledyard', 'Chester', 'Berlin', 'Granby', 'Brooklyn', 'Lyme', 'Orange', 'Willington', 'Litchfield County', 'Roxbury', 'Cheshire', 'Simsbury', 'Torrington', 'Colebrook', 'New Canaan', 'Deep River', 'Redding', 'Southbury', 'Windham', 'Trumbull', 'Killingworth', 'Milford', 'Ansonia', 'Stratford', 'Coventry', 'Pomfret', 'Portland', 'Beacon Falls', 'Montville', 'Old Saybrook', 'Bethel', 'Wethersfield', 'Bridgeport', 'Griswold', 'Barkhamsted', 'Hartland', 'Chaplin', 'Branford', 'Danbury', 'Oxford', 'Ashford', 'Waterford', 'Tolland', 'Hartford County', 'Manchester', 'Bridgewater', 'Monroe', 'Enfield', 'Washington', 'East Haven', 'New Milford', 'Cornwall', 'East Windsor', 'Darien', 'Stonington', 'Canaan', 'New Britain', 'Lisbon', 'New London', 'Groton', 'South Windsor', 'East Hartford', 'Stamford', 'New Haven', 'Haddam', 'Woodbridge', 'Vernon', 'Sprague', 'Harwinton', 'Westbrook', 'Scotland', 'Waterbury', 'Old Lyme', 'Wolcott', 'East Haddam', 'Union', 'Shelton', 'Columbia', 'Marlborough', 'Naugatuck', 'Eastford', 'New Fairfield', 'Windham County', 'Durham', 'Andover', 'Bozrah', 'Seymour', 'Bristol', 'Watertown', 'Hebron', 'Norwalk', 'Westport', 'Plymouth', 'Middlefield', 'Tolland County', 'Meriden', 'Cromwell', 'Putnam', 'Clinton', 'Easton', 'Bethany', 'Fairfield County', 'Bethlehem', 'Avon', 'Franklin', 'Glastonbury', 'Derby', 'Plainfield', 'Canton', 'Bloomfield', 'Ridgefield']
State District of Columbia has discrepancies
['Ward 6', 'Ward 5', 'Washington', 'Ward 7', 'Ward 2', 'Ward 3', 'Ward 8', 'Ward 4', 'District of Columbia']
State Hawaii has discrepancies
['Kalawao County']
State Illinois has discrepancies
['Cook Suburbs']
State Maine has discrepancies
['Mercer', 'Lewiston', 'Mexico', 'Harrington', 'Islesboro', 'Dennysville', 'Lincolnville', 'Hanover', 'Amherst', 'West Forks Plt.', 'Peru', 'Tremont', 'St. Francis', 'Oakfield', 'Prospect', 'Brownville', 'Machias', 'Seboeis Plt.', 'Freedom', 'Rome', 'Casco', 'Berwick', 'Jackman', 'Sedgwick', 'Smithfield', 'Woodstock', 'Bath', 'Farmington', 'Washington County', 'Dyer Brook', 'Nashville Plt.', 'Minot', 'Searsport', 'Gouldsboro', 'Friendship', 'Northfield', 'Castle Hill', 'Sherman', 'The Forks Plt.', 'Phippsburg', 'Moro Plt.', 'Franklin Cty Townships', 'Orient', 'Lebanon', 'Veazie', 'Corinna', 'York', 'Lincoln County', 'Monmouth', 'Cornville', 'Harrison', 'Wilton', 'Meddybemps', 'Wales', 'Ripley', 'Swanville', 'Brewer', 'Jefferson', 'Cherryfield', 'Franklin County', 'Lee', 'Linneus', 'Temple', 'Sebec', 'Beddington', 'Burlington', 'Winterville Plt.', 'Lovell', 'Princeton', 'Boothbay', 'Whitefield', 'Bridgton', 'Fairfield', 'Orrington', 'Wesley', 'Woodland', 'Waterboro', 'Standish', 'Indian Township Vtng Dst', 'Limerick', 'Eastbrook', 'Lyman', 'Newcastle', 'Millinocket', 'Whitneyville', 'Great Pond', 'Buckfield', 'Monticello', 'Hartford', 'Sorrento', 'Holden', 'Charlotte', 'Baring Plt.', 'Androscoggin County', 'Waldo County', 'Solon', 'Carrabassett Valley', 'Beals', 'Pleasant Point Votng Dst', 'Bangor', 'Cary Plt.', 'Greenbush', 'Rockport', 'Roxbury', 'Benton', 'Saco', 'Smyrna', 'Lake View Plt.', 'New Vineyard', 'Ludlow', 'Long Island', 'Chapman', 'Paris', 'Turner', 'Woolwich', 'Bremen', 'Ellsworth', 'Ashland', 'Westmanland', 'Bar Harbor', 'Dixmont', 'Greene', 'Bradford', 'Fayette', 'Topsfield', 'Isle Au Haut', 'Drew Plt.', 'Penobscot Nation Vot Dst', 'Patten', 'Otis', 'Chebeague Island', 'Kingsbury Plt.', 'South Bristol', 'Oxford County', 'Auburn', 'Dallas Plt.', 'New Sweden', 'Lubec', 'LaGrange', 'Old Town', 'Waterford', 'Caribou', 'Manchester', 'Shirley', 'Strong', 'Allagash', 'Vienna', 'Stockton Springs', 'Otisfield', 'Washburn', 'Mars Hill', 'Wallagrass', 'South Thomaston', 'Hammond', 'Falmouth', 'Dayton', 'Thorndike', 'York County', 'Hancock County', 'Somerset Cty Townships', 'Vanceboro', 'Stetson', 'Somerset County', 'Knox', 'Caratunk', 'Deblois', 'Bucksport', 'Portage Lake', 'Surry', 'Alna', 'Osborn', 'Alexander', 'Sagadahoc County', 'Starks', 'New Canada', 'Lakeville', 'Edinburg', 'Buxton', 'Trenton', 'Robbinston', 'Limestone', 'Phillips', 'Weld', 'Westbrook', 'Carroll Plt.', 'Levant', 'Knox County', 'Unity', 'West Gardiner', 'Hamlin', 'East Millinocket', 'Anson', 'Piscataquis County', 'Sangerville', 'Palermo', 'Piscataquis Cty Townshps', 'Reed Plt.', 'New Gloucester', 'Denmark', 'Presque Isle', 'Andover', 'Gray', 'Athens', 'Bradley', 'Wells', 'Bristol', 'Pleasant Ridge Plt.', 'Industry', 'Pittston', 'Garland', "Owl's Head", 'Orono', 'Bowerbank', 'Macwahoc Plt.', 'Hebron', 'Westport', 'Kenduskeag', 'Plymouth', 'Dexter', 'Belmont', 'Blue Hill', 'Embden', 'Lincoln', 'Waltham', 'Easton', 'Perham', 'Rangeley Plt.', 'Ogunquit', 'Woodville', 'Kingfield', 'Wayne', 'Winslow', 'Springfield', 'Medford', 'Skowhegan', 'Franklin', 'Baileyville', 'Dover-Foxcroft', 'Crawford', 'Coplin Plt.', 'Canton', 'North Berwick', 'Belfast', 'Upton', 'Cumberland', 'Bowdoin', 'Waldoboro', 'Brunswick', 'Sidney', 'Sumner', 'Winn', 'Guilford', 'Grand Isle', 'Lincoln Plt.', 'Old Orchrd Bch', 'Eliot', 'Litchfield', 'Rumford', 'Warren', 'Shapleigh', 'Poland', 'Eagle Lake', 'Hermon', 'Hallowell', 'Greenville', 'North Haven', 'Carmel', 'Frankfort', 'Cutler', 'Windsor', 'Hiram', 'Monson', 'Washington Cty Townships', 'Rockland', 'Topsham', 'Eastport', 'Naples', 'Fort Kent', 'Hancock Cty Townships', 'Kennebunkport', 'Stockholm', 'Penobscot County', 'Pownal', 'Thomaston', 'Newfield', "Swan's Island", 'Hodgdon', 'Aroostook Cty Townships', 'Boothbay Harbor', 'Talmadge', 'St. Albans', 'Winter Harbor', 'Jay', 'Cranberry Isles', 'Glenburn', 'Harpswell', 'Corinth', 'Hudson', 'Farmingdale', 'Beaver Cove', 'Alfred', 'Wellington', 'Madison', 'Columbia Falls', 'Houlton', 'Chelsea', 'Sweden', 'Garfield Plt.', 'Weston', 'New Sharon', 'Penobscot Cty Townships', 'Mattawamkeag', 'Milo', 'Stow', 'Magalloway Plt.', 'Yarmouth', 'Arundel', 'Hersey', 'Sabattus', 'Oxbow Plt.', 'Chester', 'West Bath', 'Fryeburg', 'Cape Elizabeth', 'Kittery', 'Cushing', 'Byron', 'Brownfield', 'Sullivan', 'Eustis', 'China', 'Cumberland County', 'Mapleton', 'Webster Plt.', 'Passadumkeag', 'Morrill', 'Parsonsfield', 'New Portland', 'Verona', 'Mount Desert', 'Arrowsic', 'Milbridge', 'North Yarmouth', 'Windham', 'Milford', 'Troy', 'Grand Lake Stream Plt', 'Camden', 'Northport', 'Hope', 'Matinicus Isle Plt.', 'Caswell', 'Vinalhaven', 'Palmyra', 'Portland', 'Frenchboro', 'Oxford Cty Townships', 'Cyr Plt.', 'Montville', 'Damariscotta', 'Perry', 'Bethel', 'Oakland', 'Norway', 'Gardiner', 'Brooks', 'Jackson', 'Charleston', 'Augusta', 'Abbot', 'Lowell', 'Hartland', 'Livermore Falls', 'Brighton Plt.', 'Freeport', 'Hollis', 'Lamoine', 'Merrill', 'Maxfield', 'Oxford', 'Penobscot', 'Aroostook County', 'Mariaville', 'Willimantic', 'Island Falls', 'Moose River', 'Danforth', 'Frye Island', 'Pembroke', 'Fort Fairfield', 'Waite', 'Bingham', 'Monroe', 'Bridgewater', 'South Portland', 'Albion', 'Blaine', 'Whiting', 'Enfield', 'Moscow', 'Appleton', 'Dennistown Plt.', 'Washington', 'Newburgh', 'Wade', 'Calais', 'Exeter', 'Canaan', 'Brooksville', 'Stonington', 'Littleton', 'Lisbon', 'Sebago', 'Rangeley', 'Brooklin', 'Stacyville', 'Waldo', 'Gorham', 'Dedham', 'Castine', 'Nobleboro', 'Newport', 'Biddeford', 'Readfield', 'Norridgewock', 'Raymond', 'Scarborough', 'Georgetown', 'Southport', 'Randolph', 'Limington', 'Vassalboro', 'Stoneham', 'Cambridge', 'Kennebunk', 'Cooper', 'Clifton', 'Searsmont', 'Dixfield', 'Detroit', 'Kennebec County', 'Winterport', 'Highland Plt.', 'Union', 'Mechanic Falls', 'Columbia', 'Liberty', 'Carthage', 'Parkman', 'Marshfield', 'Van Buren', 'Roque Bluffs', 'Cornish', 'East Machias', 'St. George', 'Glenwood Plt.', 'Durham', 'Hancock', 'Gilead', 'Frenchville', 'Southwest Harbor', 'Crystal', 'Saint Agatha', 'Waterville', 'Edgecomb', 'Porter', 'Hampden', 'Alton', 'Acton', 'Baldwin', 'Wiscasset', 'Medway', 'Eddington', 'Jonesboro', 'Westfield', 'Winthrop', 'Haynesville', 'Madawaska', 'New Limerick', 'Machiasport', 'Chesterville', 'Amity', 'Greenwood', 'West Paris', 'Clinton', 'Mount Vernon', 'Mount Chase', 'Jonesport', 'Etna', 'Orland', 'South Berwick', 'Monhegan Plt.', 'Livermore', 'Leeds', 'Dresden', 'Burnham', 'Masardis', 'Avon', 'Atkinson', 'Bowdoinham', 'Howland', 'Sanford', 'Deer Isle', 'Richmond', 'Somerville', 'Newry', 'Belgrade', 'Harmony', 'Pittsfield', 'Aurora', 'Steuben', 'Addison', 'Sandy River Plt.', 'St. John Plt.']
State Maryland has discrepancies
['Baltimore city', 'Baltimore City']
State Massachusetts has discrepancies
['Whately', 'Hanover', 'Westwood', 'Adams', 'Walpole', 'Nantucket County', 'Plainville', 'Athol', 'Hardwick', 'Montgomery', 'Hampshire County', 'Lancaster', 'Belchertown', 'Blandford', 'Holyoke', 'Framingham', 'Southwick', 'Kingston', 'Lee', 'Billerica', 'Seekonk', 'Lawrence', 'Princeton', 'Plympton', 'Nahant', 'Shutesbury', 'New Marlborough', 'Wayland', 'Newbury', 'North Attleborough', 'West Newbury', 'Northampton', 'Stoughton', 'Huntington', 'West Boylston', 'Orange', 'Hamilton', 'Rockport', 'Dover', 'Holland', 'Maynard', 'Norton', 'Cheshire', 'Ludlow', 'Brockton', 'Wareham', 'Boylston', 'Shrewsbury', 'Fall River', 'Chesterfield', 'Hampden County', 'Woburn', 'Dudley', 'Dennis', 'Sheffield', 'Otis', 'Northborough', 'Nantucket', 'Wakefield', 'Longmeadow', 'Granville', 'Wilmington', 'Falmouth', 'Swansea', 'Townsend', 'Wellfleet', 'Essex County', 'Worcester County', 'Greenfield', 'Eastham', 'Boxborough', 'Blackstone', 'Methuen', 'Lakeville', 'Gosnold', 'Sunderland', 'Phillipston', 'Andover', 'Arlington', 'Stockbridge', 'Rutland', 'Belmont', 'Beverly', 'Malden', 'Ashburnham', 'Springfield', 'Easthampton', 'Franklin', 'Provincetown', 'Canton', 'Salem', 'Paxton', 'Egremont', 'Tyringham', 'Sharon', 'Worcester', 'Marblehead', 'Sterling', 'Windsor', 'Colrain', 'North Andover', 'Monson', 'Brookline', 'Wrentham', 'Rockland', 'Millville', 'Raynham', 'Saugus', 'Hadley', 'Gloucester', 'Hudson', 'Abington', 'East Longmeadow', 'Concord', 'Hull', 'Uxbridge', 'Barnstable County', 'Chelsea', 'Winchendon', 'Chatham', 'Fairhaven', 'Chester', 'Berlin', 'Granby', 'Westborough', 'Clarksburg', 'Chilmark', 'Holliston', 'Wenham', 'Becket', 'Edgartown', 'Needham', 'Merrimac', 'Webster', 'Medfield', 'Dukes County', 'Orleans', 'Hopedale', 'Russell', 'West Bridgewater', 'Leverett', 'Lexington', 'East Bridgewater', 'Westford', 'Pembroke', 'Monroe', 'Mount Washington', 'Lynnfield', 'Holbrook', 'Great Barrington', 'Hingham', 'Halifax', 'Newton', 'Peabody', 'West Brookfield', 'Natick', 'Bourne', 'Melrose', 'Norwell', 'Bellingham', 'Plymouth County', 'Georgetown', 'Bedford', 'Randolph', 'Stoneham', 'Mashpee', 'Ipswich', 'Scituate', 'Ayer', 'Wilbraham', 'Hancock', 'Bristol County', 'Rowley', 'Chicopee', 'Savoy', 'Somerset', 'Middlefield', 'Medway', 'Warwick', 'Westfield', 'Wellesley', 'Lunenburg', 'Rowe', 'North Reading', 'Dighton', 'Deerfield', 'Amherst', 'Mansfield', 'Peru', 'Douglas', 'Tisbury', 'Mattapoisett', 'New Ashford', 'Taunton', 'Northfield', 'Swampscott', 'Middleton', 'Oak Bluffs', 'Pelham', 'Bolton', 'Tewksbury', 'Wales', 'Franklin County', 'Revere', 'Brewster', 'Goshen', 'Boston', 'Burlington', 'Middlesex County', 'Holden', 'Leicester', 'Haverhill', 'Carver', 'Mendon', 'Dracut', 'Conway', 'East Brookfield', 'Marion', 'Florida', 'Ashland', 'Lynn', 'Oakham', 'Gill', 'Topsfield', 'Foxborough', 'Southampton', 'Auburn', 'Harvard', 'Tolland', 'Manchester', 'Shirley', 'New Braintree', 'Sandwich', 'Wendell', 'Ashby', 'Hopkinton', 'Sandisfield', 'Grafton', 'Groton', 'Tyngsborough', 'Acushnet', 'Westminster', 'West Springfield', 'Agawam', 'Marlborough', 'Aquinnah', 'Shelburne', 'Hinsdale', 'Southborough', 'Charlton', 'Sudbury', 'Westport', 'Plymouth', 'Millis', 'Buckland', 'Lincoln', 'Waltham', 'Easton', 'Newburyport', 'Medford', 'Norfolk County', 'Upton', 'Milton', 'Monterey', 'Berkley', 'Petersham', 'Pepperell', 'Northbridge', 'Berkshire County', 'Duxbury', 'Brimfield', 'Warren', 'Boxford', 'Attleboro', 'Williamstown', 'Cohasset', 'Barre', 'Quincy', 'Barnstable', 'Brookfield', 'Charlemont', 'New Salem', 'Norfolk', 'Royalston', 'Gardner', 'Erving', 'Westhampton', 'Essex', 'Bernardston', 'Rehoboth', 'West Stockbridge', 'Salisbury', 'Weston', 'Leominster', 'Dunstable', 'Stow', 'Sherborn', 'Winchester', 'Yarmouth', 'North Adams', 'Palmer', 'Danvers', 'Whitman', 'Spencer', 'Weymouth', 'Fitchburg', 'West Tisbury', 'Braintree', 'Amesbury', 'Milford', 'Montague', 'Southbridge', 'Williamsburg', 'Reading', 'Leyden', 'Ashfield', 'Lowell', 'Oxford', 'Everett', 'Norwood', 'North Brookfield', 'Dalton', 'Bridgewater', 'Templeton', 'Hatfield', 'Washington', 'Heath', 'Hanson', 'Littleton', 'New Bedford', 'Lanesborough', 'Dedham', 'Cummington', 'Groveland', 'Sutton', 'Cambridge', 'Hawley', 'South Hadley', 'Chelmsford', 'Alford', 'Marshfield', 'Ware', 'Suffolk County', 'Middleborough', 'Worthington', 'Hampden', 'Acton', 'Watertown', 'Rochester', 'Freetown', 'Harwich', 'Winthrop', 'Hubbardston', 'Clinton', 'Dartmouth', 'Carlisle', 'Lenox', 'Avon', 'Truro', 'Richmond', 'Somerville', 'Pittsfield', 'Plainfield', 'Millbury', 'Sturbridge']
State Minnesota has discrepancies
['Lac Qui Parle County', 'Lac qui Parle County']
State Missouri has discrepancies
['St. Louis city', 'Jackson County', 'Jackson County (including other portions of Kansas City)', 'City of St. Louis']
State New Hampshire has discrepancies
['Sugar Hill', 'Merrimack', 'Alexandria', 'Stewartstown', 'Sharon', 'Hanover', 'Amherst', 'Merrimack County', 'Deerfield', 'Tamworth', 'Harrisville', 'Litchfield', 'Brentwood', 'Campton', 'Newfields', 'Walpole', 'Warren', 'Holderness', 'Henniker', 'Hillsborough', 'Grantham', 'New Hampton', 'Eaton', 'Croydon', 'Greenville', 'Freedom', 'Lancaster', 'Antrim', 'Bath', 'Woodstock', 'Windsor', 'Farmington', 'Brookline', 'Northfield', 'Stoddard', 'Middleton', 'Brookfield', 'Coos County', 'Pelham', 'Lebanon', 'Newington', 'Chichester', 'Hampton', 'Wilton', 'Gilmanton', 'Hudson', 'Warner', 'Jefferson', 'Concord', 'Kingston', 'Temple', 'Lee', 'Goshen', 'Hill', 'Cheshire County', 'Madison', 'New Castle', 'Northumberland', 'Salisbury', 'Whitefield', 'Bartlett', 'Allenstown', 'Rollinsford', 'Winchester', 'Langdon', 'Canterbury', 'Chatham', 'Lyman', 'Peterborough', 'Newbury', 'Jaffrey', 'Moultonborough', 'Effingham', 'Orford', 'Chester', 'Berlin', 'Lempster', 'Strafford County', 'East Kingston', 'Gilsum', 'Haverhill', 'Millsfield', 'Lyme', 'Hillsborough County', 'Wilmot', 'Orange', 'Fitzwilliam', 'Epsom', 'Rockingham County', 'Deering', 'Sullivan', 'Mont Vernon', 'Dover', 'Roxbury', 'Wentworth', 'Conway', 'Milan', 'Benton', 'Barnstead', 'New Durham', 'Dublin', 'Colebrook', 'Madbury', 'Charlestown', 'Albany', 'Sanbornton', 'Windham', 'Milford', 'Troy', 'Ellsworth', 'Stratford', 'Ashland', 'Nashua', 'Webster', 'Candia', 'Grafton County', 'Weare', 'Chesterfield', 'Fremont', 'Bradford', 'Westmoreland', 'Piermont', 'Jackson', 'Center Harbor', 'Hollis', 'Portsmouth', 'Danbury', 'Wakefield', 'Auburn', 'Thornton', 'Nelson', 'Pittsburg', 'Sullivan County', 'Newmarket', 'Pembroke', 'Dalton', 'Manchester', 'Bridgewater', 'Monroe', 'Stark', 'Hampton Falls', 'Enfield', 'Bennington', 'Sunapee', 'Sandwich', 'Carroll', 'Tuftonboro', 'Claremont', 'Washington', 'Meredith', 'Boscawen', 'Bow', "Wentworth's Location", 'Hopkinton', 'Exeter', 'Canaan', 'Littleton', 'Lisbon', 'Newton', 'Grafton', 'Epping', 'Strafford', 'Ossipee', 'Dunbarton', 'Barrington', 'New London', 'Gorham', 'Groton', 'Newport', 'Surry', 'Sandown', 'Alstead', 'Laconia', 'Greenfield', 'Tilton', 'Dixville', 'Mason', 'Gilford', 'Swanzey', 'Sutton', 'Francestown', 'Raymond', 'Carroll County', 'Nottingham', 'Londonderry', 'Randolph', 'Bedford', 'Somersworth', 'Landaff', 'Wolfeboro', 'Unity', 'Acworth', 'Danville', 'Marlborough', 'Columbia', 'Marlow', 'Shelburne', 'Errol', 'Loudon', 'Seabrook', 'Hinsdale', 'Belknap County', 'Cornish', 'Clarksville', 'Durham', 'Hancock', 'New Ipswich', 'Andover', 'Derry', 'Bristol', 'Waterville', 'Rumney', 'Alton', 'Goffstown', 'Hebron', 'Rochester', 'Plymouth', 'New Boston', 'South Hampton', 'Belmont', 'Franconia', 'Plaistow', 'Lincoln', 'Easton', 'Bethlehem', 'Hooksett', 'Harts Location', 'Springfield', 'Keene', 'Atkinson', 'Franklin', 'Kensington', 'Dummer', 'Richmond', 'North Hampton', 'Rindge', 'Pittsfield', 'Northwood', 'Stratham', 'Greenland', 'Plainfield', 'Milton', 'Rye', 'Lyndeborough', 'Salem', 'Dorchester', 'Hampstead']
State New Mexico has discrepancies
['Do�a Ana County', 'Doña Ana County']
State Rhode Island has discrepancies
['Newport County', 'West Warwick', 'Portsmouth', 'Warren', 'Providence County', 'Jamestown', 'Smithfield', 'Washington County', 'East Greenwich', 'Little Compton', 'Woonsocket', 'Providence', 'Hopkinton', 'Exeter', 'North Kingstown', 'South Kingstown', 'Barrington', 'Newport', 'Glocester', 'Central Falls', 'North Smithfield', 'Middletown', 'Tiverton', 'Cranston', 'Foster', 'Westerly', 'North Providence', 'West Greenwich', 'Scituate', 'Bristol County', 'Johnston', 'Bristol', 'New Shoreham', 'Warwick', 'Narragansett', 'Lincoln', 'Burrillville', 'Charlestown', 'Kent County', 'East Providence', 'Richmond', 'Coventry', 'Pawtucket', 'Cumberland']
State Vermont has discrepancies

Let us fix the above discrepancies one by one

In [ ]:
# State Alaska has discrepancies
# ['Haines Borough', 'Skagway Municipality', 'ED 21', 'ED 16', 'ED 27', 'Aleutians West Census Area', 'Hoonah-Angoon Census Area', 'Yukon-Koyukuk Census Area', 'ED 39', 'ED 19', 'Municipality of Anchorage', 'Southeast Fairbanks Census Area', 'Aleutians East Borough', 'ED 30', 'Sitka City and Borough', 'ED 10', 'ED 23', 'ED 35', 'Nome Census Area', 'Wade Hampton Census Area', 'ED 11', 'ED 38', 'ED 9', 'ED 34', 'Kenai Peninsula Borough', 'ED 13', 'Matanuska-Susitna Borough', 'ED 15', 'Denali Borough', 'ED 29', 'Dillingham Census Area', 'ED 4', 'ED 22', 'ED 6', 'Bethel Census Area', 'Kodiak Island Borough', 'ED 20', 'ED 33', 'ED 12', 'Northwest Arctic Borough', 'ED 40', 'City and Borough of Juneau', 'ED 2', 'ED 5', 'ED 31', 'Prince of Wales-Hyder Census Area', 'ED 28', 'ED 24', 'Ketchikan Gateway Borough', 'Fairbanks North Star Borough', 'North Slope Borough', 'ED 36', 'ED 1', 'Yakutat City and Borough', 'ED 7', 'ED 17', 'Bristol Bay Borough', 'Wrangell City and Borough', 'ED 37', 'ED 25', 'ED 8', 'ED 14', 'Lake and Peninsula Borough', 'ED 32', 'ED 18', 'Valdez-Cordova Census Area', 'ED 26', 'Kusilvak Census Area', 'ED 3', 'Petersburg Census Area']

'''
As we already saw that the Alaska elections takes place in election districts and not counties. 
So let us drop Alaska from both president and covid data for president merge
'''
president_merge_data = president_merge_data[president_merge_data['state']!='Alaska']
president_covid_merge_dataset = president_covid_merge_dataset[president_covid_merge_dataset['State']!='Alaska']

In [ ]:
# State California has discrepancies
# ['Grand Princess Cruise Ship']

'''
The ship data is present as part of covid dataset. Let us drop this row
'''
idx = president_covid_merge_dataset.index[president_covid_merge_dataset['County_Name']=='Grand Princess Cruise Ship']
president_covid_merge_dataset.drop(idx,inplace=True)
president_covid_merge_dataset[president_covid_merge_dataset['County_Name']=='Grand Princess Cruise Ship']

/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py:4906: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Empty DataFrame
Columns: [countyFIPS, County_Name, State, population, Total_Covid_Cases_Till_Election, Total_Covid_Deaths_Till_Election]
Index: []

In [ ]:
# State District of Columbia has discrepancies
# ['Washington', 'Ward 3', 'District of Columbia', 'Ward 2', 'Ward 5', 'Ward 6', 'Ward 8', 'Ward 7', 'Ward 4']
'''
DC has only one county. So let us merge all the data by renaming all wards to Washington county
'''
idx = president_merge_data.index[president_merge_data['state']=='District of Columbia']
president_merge_data.loc[idx,'county'] = 'Washington'
president_merge_data.loc[idx]

/usr/local/lib/python3.8/dist-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,state,county,current_votes,total_votes,percent,candidate,party,Winner_Votes,won
3,District of Columbia,Washington,41681,41681,100.0,Joe Biden,DEM,39041,True
4,District of Columbia,Washington,32881,32881,100.0,Joe Biden,DEM,29078,True
5,District of Columbia,Washington,44231,44231,100.0,Joe Biden,DEM,39397,True
6,District of Columbia,Washington,45296,45296,100.0,Joe Biden,DEM,42489,True
7,District of Columbia,Washington,46107,46107,100.0,Joe Biden,DEM,43320,True
8,District of Columbia,Washington,62918,62918,100.0,Joe Biden,DEM,56719,True
9,District of Columbia,Washington,38384,38384,100.0,Joe Biden,DEM,36382,True
10,District of Columbia,Washington,32858,32858,100.0,Joe Biden,DEM,30897,True

In [ ]:
president_merge_data[president_merge_data.duplicated(['state','county','percent','candidate','party','won'])]

,state,county,current_votes,total_votes,percent,candidate,party,Winner_Votes,won
4,District of Columbia,Washington,32881,32881,100.0,Joe Biden,DEM,29078,True
5,District of Columbia,Washington,44231,44231,100.0,Joe Biden,DEM,39397,True
6,District of Columbia,Washington,45296,45296,100.0,Joe Biden,DEM,42489,True
7,District of Columbia,Washington,46107,46107,100.0,Joe Biden,DEM,43320,True
8,District of Columbia,Washington,62918,62918,100.0,Joe Biden,DEM,56719,True
9,District of Columbia,Washington,38384,38384,100.0,Joe Biden,DEM,36382,True
10,District of Columbia,Washington,32858,32858,100.0,Joe Biden,DEM,30897,True

In [ ]:
president_merge_data = president_merge_data.groupby(['state','county','percent','candidate','party','won']).sum().reset_index()

In [ ]:
president_merge_data[president_merge_data['state']=='District of Columbia']

,state,county,percent,candidate,party,won,current_votes,total_votes,Winner_Votes
451,District of Columbia,Washington,100.0,Joe Biden,DEM,True,344356,344356,317323

In [ ]:
# State Hawaii has discrepancies
# ['Kalawao County']
'''
The Kalawao County is present only in covid dataset and it has less 100 population.
So let us delete it from covid dataset
'''
idx = president_covid_merge_dataset.index[president_covid_merge_dataset['County_Name']=='Kalawao County']
president_covid_merge_dataset.drop(idx,inplace=True)
president_covid_merge_dataset[president_covid_merge_dataset['County_Name']=='Kalawao County']

Empty DataFrame
Columns: [countyFIPS, County_Name, State, population, Total_Covid_Cases_Till_Election, Total_Covid_Deaths_Till_Election]
Index: []

In [ ]:
# State Illinois has discrepancies
# ['Cook Suburbs']
'''
Cook Suburbs is present only in president election data.
Let us merge it with Cook County
'''
president_merge_data[(president_merge_data['county'].str.contains('Cook')) & (president_merge_data['state'].str.contains('Illinois'))]

,state,county,percent,candidate,party,won,current_votes,total_votes,Winner_Votes
741,Illinois,Cook County,96.018860,Joe Biden,DEM,True,2321399,2417649,1725973
742,Illinois,Cook Suburbs,96.313328,Joe Biden,DEM,True,1176658,1221698,781238

In [ ]:
idx1 = president_merge_data.index[(president_merge_data['county'].str.contains('Cook County')) & (president_merge_data['state'].str.contains('Illinois'))].item()
idx2 = president_merge_data.index[(president_merge_data['county'].str.contains('Cook Suburbs')) & (president_merge_data['state'].str.contains('Illinois'))].item()
president_merge_data.loc[idx1,'current_votes'] +=  president_merge_data.loc[idx2,'current_votes']
president_merge_data.loc[idx1,'total_votes'] += president_merge_data.loc[idx2,'total_votes']
president_merge_data.loc[idx1,'Winner_Votes'] += president_merge_data.loc[idx2,'Winner_Votes']
president_merge_data.drop(idx2,inplace=True)
president_merge_data[(president_merge_data['county'].str.contains('Cook')) & (president_merge_data['state'].str.contains('Illinois'))]

,state,county,percent,candidate,party,won,current_votes,total_votes,Winner_Votes
741,Illinois,Cook County,96.01886,Joe Biden,DEM,True,3498057,3639347,2507211

In [ ]:
# State Maryland has discrepancies
# ['Baltimore city', 'Baltimore City']
'''
This is an issue with city letter case. In our previous cleaning we faced the same issue with Virginia as well
So let us fix this in both datasets to have Capital C
'''
president_merge_data['county'] = president_merge_data['county'].apply(lambda x: x.replace(' city', ' City'))
president_covid_merge_dataset['County_Name'] = president_covid_merge_dataset['County_Name'].apply(lambda x: x.replace(' city', ' City'))

In [ ]:
# State Minnesota has discrepancies
# ['Lac Qui Parle County', 'Lac qui Parle County']
idx = president_merge_data.index[president_merge_data['county'] == 'Lac qui Parle County']
president_merge_data.loc[idx,'county'] = 'Lac Qui Parle County'

In [ ]:
# State New Mexico has discrepancies
# ['Doña Ana County', 'Do�a Ana County']

idx = president_merge_data.index[president_merge_data['county'].str.contains(' Ana County')]
president_merge_data.loc[idx, 'county'] = 'Doña Ana County'

In [ ]:
# State Missouri has discrepancies
# ['Jackson County (including other portions of Kansas City)', 'St. Louis city', 'City of St. Louis', 'Jackson County']
idx = president_covid_merge_dataset.index[president_covid_merge_dataset['County_Name'].str.contains('including')]
president_covid_merge_dataset.loc[idx,'County_Name'] = 'Jackson County'

In [ ]:
idx = president_covid_merge_dataset.index[president_covid_merge_dataset['County_Name']=='City of St. Louis']
president_covid_merge_dataset.loc[idx,'County_Name'] = 'St. Louis City' # Using uppercase C since we already transformed City values

In [ ]:
# Rest of all states whose data has city names are
# Connecticut, Maine, Massachusetts, New Hampshire, Rhode Island, Vermont, Virginia 
def transform_county_names1(x):
  if x['state'] in ['Connecticut', 'Maine','Massachusetts','New Hampshire', 'Rhode Island', 'Vermont', 'Virginia']:
    output = city_county_dataset[(city_county_dataset['State'] == x['state']) & (city_county_dataset['City'] == x['county'])]['County']
    x['county'] = output.item() if len(output)==1 else x['county']
  return x

In [ ]:
president_merge_data = president_merge_data.apply(transform_county_names1, axis=1)

In [ ]:
president_merge_data = president_merge_data.groupby(by=['state','county','candidate','party','won']).sum().reset_index()

In [ ]:
president_merge_data[president_merge_data['state']=='Connecticut']

,state,county,candidate,party,won,percent,current_votes,total_votes,Winner_Votes
279,Connecticut,Fairfield County,Donald Trump,REP,True,300.000000,44452,44452,23079
280,Connecticut,Fairfield County,Joe Biden,DEM,True,1993.751078,428538,431324,276729
281,Connecticut,Hartford County,Donald Trump,REP,True,400.000000,50530,50530,25789
282,Connecticut,Hartford County,Joe Biden,DEM,True,2500.033538,398806,398805,259378
283,Connecticut,Litchfield County,Donald Trump,REP,True,1400.000000,70918,70918,40342
284,Connecticut,Litchfield County,Joe Biden,DEM,True,1199.530516,36626,36631,20779
285,Connecticut,Middlesex County,Joe Biden,DEM,True,1497.191198,99203,99329,56848
286,Connecticut,New Haven County,Donald Trump,REP,True,999.961158,96377,96383,53723
287,Connecticut,New Haven County,Joe Biden,DEM,True,1699.902495,321603,321620,201317
288,Connecticut,New London County,Donald Trump,REP,True,1000.000000,27665,27665,14677
289,Connecticut,New London County,Joe Biden,DEM,True,1094.912609,111939,112428,67124
290,Connecticut,Tolland County,Donald Trump,REP,True,300.000000,12724,12724,6972
291,Connecticut,Tolland County,Joe Biden,DEM,True,1000.000000,67822,67822,38503
292,Connecticut,Windham County,Donald Trump,REP,True,1000.000000,37343,37343,20973
293,Connecticut,Windham County,Joe Biden,DEM,True,500.000000,19734,19734,11172

Since we renamed the counties now we will have duplicate data and might have two winners in a given county. So we need to eliminate it

In [ ]:
def get_winner_and_merged_votes1(row):
  if row['state'] in ['Connecticut', 'Maine','Massachusetts','New Hampshire', 'Rhode Island', 'Vermont', 'Virginia']:
    slice_df = president_merge_data[(president_merge_data['state']==row['state'])&(president_merge_data['county']==row['county'])]
    if len(slice_df) > 1:
      winner_row_idx = president_merge_data[(president_merge_data['state']==row['state'])&(president_merge_data['county']==row['county'])]['Winner_Votes'].idxmax()
      return president_merge_data.loc[winner_row_idx]
  return row

In [ ]:
president_merge_data = president_merge_data.apply(get_winner_and_merged_votes1, axis=1)
president_merge_data.drop_duplicates(inplace=True)

In [ ]:
president_merge_data.head()

,state,county,candidate,party,won,percent,current_votes,total_votes,Winner_Votes
0,Alabama,Autauga County,Donald Trump,REP,True,100.0,27770,27770,19838
1,Alabama,Baldwin County,Donald Trump,REP,True,100.0,109679,109679,83544
2,Alabama,Barbour County,Donald Trump,REP,True,100.0,10518,10518,5622
3,Alabama,Bibb County,Donald Trump,REP,True,100.0,9595,9595,7525
4,Alabama,Blount County,Donald Trump,REP,True,100.0,27588,27588,24711

In [ ]:
president_merge_data[president_merge_data.duplicated(['state','county','candidate'])]

Empty DataFrame
Columns: [state, county, candidate, party, won, percent, current_votes, total_votes, Winner_Votes]
Index: []

In [ ]:
president_merge_data.shape

(3112, 9)

In [ ]:
president_covid_merge_dataset.shape

(3112, 6)

So the shape matches. So checking for the discrepancies again

In [ ]:
for state in covid_state_list:
  output = get_different_county_names_president(state)
  if len(output)>0:
    print(f"State {state} has discrepancies")
    print(output)

No Discrepancies found. So merging the data

In [ ]:
# Transforming the percent column again before merging
president_merge_data['percent'] = round((president_merge_data['current_votes']/president_merge_data['total_votes'])*100,2)

In [ ]:
president_merge_data[president_merge_data['state']=='Connecticut']

,state,county,candidate,party,won,percent,current_votes,total_votes,Winner_Votes
279,Connecticut,Fairfield County,Joe Biden,DEM,True,99.35,428538,431324,276729
281,Connecticut,Hartford County,Joe Biden,DEM,True,100.00,398806,398805,259378
283,Connecticut,Litchfield County,Donald Trump,REP,True,100.00,70918,70918,40342
285,Connecticut,Middlesex County,Joe Biden,DEM,True,99.87,99203,99329,56848
286,Connecticut,New Haven County,Joe Biden,DEM,True,99.99,321603,321620,201317
288,Connecticut,New London County,Joe Biden,DEM,True,99.57,111939,112428,67124
290,Connecticut,Tolland County,Joe Biden,DEM,True,100.00,67822,67822,38503
292,Connecticut,Windham County,Donald Trump,REP,True,100.00,37343,37343,20973

### Merged Covid and President Data

In [ ]:
president_covid_merged = pd.merge(president_covid_merge_dataset,president_merge_data,how='left',left_on=['County_Name','State'],right_on=['county','state'])
president_covid_merged.drop(columns=['county','state'],inplace=True)
president_covid_merged.head()

,countyFIPS,County_Name,State,population,Total_Covid_Cases_Till_Election,Total_Covid_Deaths_Till_Election,candidate,party,won,percent,current_votes,total_votes,Winner_Votes
0,1001,Autauga County,Alabama,55869,2159.0,30.0,Donald Trump,REP,True,100.0,27770,27770,19838
1,1003,Baldwin County,Alabama,223234,6940.0,71.0,Donald Trump,REP,True,100.0,109679,109679,83544
2,1005,Barbour County,Alabama,24686,1060.0,9.0,Donald Trump,REP,True,100.0,10518,10518,5622
3,1007,Bibb County,Alabama,22394,873.0,15.0,Donald Trump,REP,True,100.0,9595,9595,7525
4,1009,Blount County,Alabama,57826,2074.0,25.0,Donald Trump,REP,True,100.0,27588,27588,24711

In [ ]:
president_covid_merged.shape

(3112, 13)

### Preparing Governor's Data for Merge

In [ ]:
governors_county.head()

      state             county  current_votes  total_votes  percent
0  Delaware        Kent County          85415        87025      100
1  Delaware  New Castle County         280039       287633      100
2  Delaware      Sussex County         127181       129352      100
3   Indiana       Adams County          14154        14209      100
4   Indiana       Allen County         168312       169082      100

In [ ]:
governors_county_candidate.head()

      state             county        candidate party   votes    won
0  Delaware        Kent County      John Carney   DEM   44352   True
1  Delaware        Kent County  Julianne Murray   REP   39332  False
2  Delaware        Kent County  Kathy DeMatteis   IPD    1115  False
3  Delaware        Kent County    John Machurek   LIB     616  False
4  Delaware  New Castle County      John Carney   DEM  191678   True

In [ ]:
governors_state.head()

           state    votes
0       Delaware   492635
1        Indiana  3020383
2       Missouri  3012274
3        Montana   603587
4  New Hampshire   792804

Tallying votes count across all datasets

In [ ]:
governors_county

              state             county  current_votes  total_votes  percent
0          Delaware        Kent County          85415        87025      100
1          Delaware  New Castle County         280039       287633      100
2          Delaware      Sussex County         127181       129352      100
3           Indiana       Adams County          14154        14209      100
4           Indiana       Allen County         168312       169082      100
...             ...                ...            ...          ...      ...
1020  West Virginia     Webster County           3339         3402      100
1021  West Virginia      Wetzel County           6553         6667      100
1022  West Virginia        Wirt County           2544         2653      100
1023  West Virginia        Wood County          38435        38762      100
1024  West Virginia     Wyoming County           8320         8592      100

[1025 rows x 5 columns]

In [ ]:
governors_county_candidate.groupby(by=['state','county'])['votes'].sum().reset_index()

              state             county   votes
0          Delaware        Kent County   85415
1          Delaware  New Castle County  280039
2          Delaware      Sussex County  127181
3           Indiana       Adams County   14154
4           Indiana       Allen County  168312
...             ...                ...     ...
1020  West Virginia     Webster County    3339
1021  West Virginia      Wetzel County    6553
1022  West Virginia        Wirt County    2544
1023  West Virginia        Wood County   38435
1024  West Virginia     Wyoming County    8320

[1025 rows x 3 columns]

The sum of state and county polled votes from governor's county candidate dataset matches with current_votes value in governor's county dataset. So the data is consistent

In [ ]:
governor_county_winner = pd.DataFrame(governors_county_candidate[governors_county_candidate['won']==True])

In [ ]:
governor_county_winner.shape

(1025, 6)

In [ ]:
governors_county.shape

(1025, 5)

Both shape matches now we can merge these datasets to form governors merge dataset

In [ ]:
governors_merge_data = pd.merge(governors_county,governor_county_winner,how='left',left_on=['state','county'],right_on=['state','county'])

In [ ]:
governors_merge_data.head()

,state,county,current_votes,total_votes,percent,candidate,party,votes,won
0,Delaware,Kent County,85415,87025,100,John Carney,DEM,44352,True
1,Delaware,New Castle County,280039,287633,100,John Carney,DEM,191678,True
2,Delaware,Sussex County,127181,129352,100,Julianne Murray,REP,68435,True
3,Indiana,Adams County,14154,14209,100,Eric Holcomb,REP,9441,True
4,Indiana,Allen County,168312,169082,100,Eric Holcomb,REP,98406,True

In [ ]:
governors_merge_data.shape

(1025, 9)

In [ ]:
column_names = list(governors_merge_data.columns)
column_names[column_names.index('votes')] = 'Winner_Votes'
governors_merge_data.columns = column_names
governors_merge_data.head()

,state,county,current_votes,total_votes,percent,candidate,party,Winner_Votes,won
0,Delaware,Kent County,85415,87025,100,John Carney,DEM,44352,True
1,Delaware,New Castle County,280039,287633,100,John Carney,DEM,191678,True
2,Delaware,Sussex County,127181,129352,100,Julianne Murray,REP,68435,True
3,Indiana,Adams County,14154,14209,100,Eric Holcomb,REP,9441,True
4,Indiana,Allen County,168312,169082,100,Eric Holcomb,REP,98406,True

In [ ]:
governors_merge_data['state'].nunique()

11

In [ ]:
governors_merge_data[governors_merge_data.duplicated(['state','county'])]

Empty DataFrame
Columns: [state, county, current_votes, total_votes, percent, candidate, party, Winner_Votes, won]
Index: []

In [ ]:
merge_covid_dataset.head()

,countyFIPS,County_Name,State,population,Total_Covid_Cases_Till_Election,Total_Covid_Deaths_Till_Election
0,1001,Autauga County,Alabama,55869,2159.0,30.0
1,1003,Baldwin County,Alabama,223234,6940.0,71.0
2,1005,Barbour County,Alabama,24686,1060.0,9.0
3,1007,Bibb County,Alabama,22394,873.0,15.0
4,1009,Blount County,Alabama,57826,2074.0,25.0

In [ ]:
merge_covid_dataset.shape

(3144, 6)

In [ ]:
governors_covid_merge_dataset = merge_covid_dataset.copy()

In [ ]:
#Checking for County Name discrepancies for latest datasets
def get_different_county_names_governor(state_name):
  governor_county_names_list = governors_merge_data[governors_merge_data['state']==state_name]['county'].to_list()
  covid_dataset_county_names_list = governors_covid_merge_dataset[governors_covid_merge_dataset['State']==state_name]['County_Name'].to_list()
  return list(set(governor_county_names_list).symmetric_difference(set(covid_dataset_county_names_list)))

In [ ]:
covid_state_list = list(governors_covid_merge_dataset['State'].unique())
governors_state_list = list(governors_merge_data['state'].unique())
governor_excluded_states = list(set(covid_state_list).symmetric_difference(set(governors_state_list)))
governor_excluded_states

['New Jersey',
 'Virginia',
 'South Dakota',
 'Hawaii',
 'Maryland',
 'Georgia',
 'New Mexico',
 'Michigan',
 'Oregon',
 'Kentucky',
 'Louisiana',
 'Maine',
 'New York',
 'Colorado',
 'California',
 'Minnesota',
 'Connecticut',
 'Alaska',
 'Texas',
 'Mississippi',
 'Kansas',
 'Tennessee',
 'Iowa',
 'Arizona',
 'Idaho',
 'South Carolina',
 'Wisconsin',
 'Ohio',
 'Arkansas',
 'Florida',
 'Alabama',
 'District of Columbia',
 'Oklahoma',
 'Massachusetts',
 'Pennsylvania',
 'Wyoming',
 'Nevada',
 'Rhode Island',
 'Nebraska',
 'Illinois']

These are the states for which governor election didn't take place in 2020. So let us drop these from governor covid dataset

In [ ]:
governors_covid_merge_dataset = governors_covid_merge_dataset[~(governors_covid_merge_dataset['State'].isin(governor_excluded_states))]

In [ ]:
governors_covid_merge_dataset['State'].nunique()

11

Rechecking the state difference

In [ ]:
covid_state_list = list(governors_covid_merge_dataset['State'].unique())
governors_state_list = list(governors_merge_data['state'].unique())
list(set(covid_state_list).symmetric_difference(set(governors_state_list)))

[]

In [ ]:
for state in covid_state_list:
  output = get_different_county_names_governor(state)
  if len(output)>0:
    print(f"State {state} has discrepancies")
    print(output)

State Missouri has discrepancies
['St. Louis city', 'Jackson County', 'Jackson County (including other portions of Kansas City)', 'City of St. Louis']
State New Hampshire has discrepancies
['Sugar Hill', 'Merrimack', 'Alexandria', 'Stewartstown', 'Sharon', 'Hanover', 'Amherst', 'Merrimack County', 'Deerfield', 'Tamworth', 'Harrisville', 'Litchfield', 'Brentwood', 'Campton', 'Newfields', 'Walpole', 'Warren', 'Holderness', 'Henniker', 'Hillsborough', 'Grantham', 'New Hampton', 'Eaton', 'Croydon', 'Greenville', 'Freedom', 'Lancaster', 'Antrim', 'Bath', 'Woodstock', 'Windsor', 'Farmington', 'Brookline', 'Northfield', 'Stoddard', 'Middleton', 'Brookfield', 'Coos County', 'Pelham', 'Lebanon', 'Newington', 'Chichester', 'Hampton', 'Wilton', 'Gilmanton', 'Hudson', 'Warner', 'Jefferson', 'Concord', 'Kingston', 'Temple', 'Lee', 'Goshen', 'Hill', 'Cheshire County', 'Madison', 'New Castle', 'Northumberland', 'Salisbury', 'Whitefield', 'Bartlett', 'Allenstown', 'Rollinsford', 'Winchester', 'Langdon', 'Canterbury', 'Chatham', 'Lyman', 'Peterborough', 'Newbury', 'Jaffrey', 'Moultonborough', 'Effingham', 'Orford', 'Chester', 'Berlin', 'Lempster', 'Strafford County', 'East Kingston', 'Gilsum', 'Haverhill', 'Millsfield', 'Lyme', 'Hillsborough County', 'Wilmot', 'Orange', 'Fitzwilliam', 'Epsom', 'Rockingham County', 'Deering', 'Sullivan', 'Mont Vernon', 'Dover', 'Roxbury', 'Wentworth', 'Conway', 'Milan', 'Benton', 'Barnstead', 'New Durham', 'Dublin', 'Colebrook', 'Madbury', 'Charlestown', 'Albany', 'Sanbornton', 'Windham', 'Milford', 'Troy', 'Ellsworth', 'Stratford', 'Ashland', 'Nashua', 'Webster', 'Candia', 'Grafton County', 'Weare', 'Chesterfield', 'Fremont', 'Bradford', 'Westmoreland', 'Piermont', 'Jackson', 'Center Harbor', 'Hollis', 'Portsmouth', 'Danbury', 'Wakefield', 'Auburn', 'Thornton', 'Nelson', 'Pittsburg', 'Sullivan County', 'Newmarket', 'Pembroke', 'Dalton', 'Manchester', 'Bridgewater', 'Monroe', 'Stark', 'Hampton Falls', 'Enfield', 'Bennington', 'Sunapee', 'Sandwich', 'Carroll', 'Tuftonboro', 'Claremont', 'Washington', 'Meredith', 'Boscawen', 'Bow', "Wentworth's Location", 'Hopkinton', 'Exeter', 'Canaan', 'Littleton', 'Lisbon', 'Newton', 'Grafton', 'Epping', 'Strafford', 'Ossipee', 'Dunbarton', 'Barrington', 'New London', 'Gorham', 'Groton', 'Newport', 'Surry', 'Sandown', 'Alstead', 'Laconia', 'Greenfield', 'Tilton', 'Dixville', 'Mason', 'Gilford', 'Swanzey', 'Sutton', 'Francestown', 'Raymond', 'Carroll County', 'Nottingham', 'Londonderry', 'Randolph', 'Bedford', 'Somersworth', 'Landaff', 'Wolfeboro', 'Unity', 'Acworth', 'Danville', 'Marlborough', 'Columbia', 'Marlow', 'Shelburne', 'Errol', 'Loudon', 'Seabrook', 'Hinsdale', 'Belknap County', 'Cornish', 'Clarksville', 'Durham', 'Hancock', 'New Ipswich', 'Andover', 'Derry', 'Bristol', 'Waterville', 'Rumney', 'Alton', 'Goffstown', 'Hebron', 'Rochester', 'Plymouth', 'New Boston', 'South Hampton', 'Belmont', 'Franconia', 'Plaistow', 'Lincoln', 'Easton', 'Bethlehem', 'Hooksett', 'Harts Location', 'Springfield', 'Keene', 'Atkinson', 'Franklin', 'Kensington', 'Dummer', 'Richmond', 'North Hampton', 'Rindge', 'Pittsfield', 'Northwood', 'Stratham', 'Greenland', 'Plainfield', 'Milton', 'Rye', 'Lyndeborough', 'Salem', 'Dorchester', 'Hampstead']
State Vermont has discrepancies
['Elmore', 'Addison', 'Newfane', 'Guilford', 'Grand Isle', 'Sharon', 'Morristown', 'Middlebury', 'Peru', 'Duxbury', 'Wallingford', 'Warren', 'Middletown Springs', 'Colchester', 'Guildhall', 'Lyndon', 'Norwich', 'Vergennes', 'Williamstown', 'Worcester', 'Walden', 'Tinmouth', 'West Rutland', 'Fletcher', 'Benson', 'Sandgate', 'Montgomery', 'Waitsfield', 'Barre', 'Lamoille County', 'Windsor', 'Woodstock', 'Washington County', 'Rupert', 'South Burlington', 'Whitingham', 'Woodbury', 'Northfield', 'Rutland Town', 'Topsham', 'Mount Holly', 'Brookline', 'Brookfield', 'Stratton', 'Winooski', 'Poultney', 'Pownal', 'Grand Isle County', 'St. Albans', 'Jay', 'Bolton', 'Dummerston', 'West Haven', 'Orange County', 'Cabot', 'Corinth', 'Belvidere', 'Townshend', 'Craftsbury', 'Lemington', 'Tunbridge', 'Concord', 'Franklin County', 'Essex', 'Burlington', 'Goshen', 'Mount Tabor', 'Peacham', 'Pawlet', 'Salisbury', 'Pittsford', 'Jericho', 'Weston', 'Chelsea', 'Wheelock', 'Isle La Motte', 'Searsburg', 'Fairfield', 'St. Albans Town', 'Bakersfield', 'Brandon', 'Newbury', 'Middlesex', 'Newport Town', 'East Montpelier', 'Charlotte', 'Hartford', 'South Hero', 'Underhill', 'Chester', 'Berlin', 'Greensboro', 'Granby', 'Leicester', 'Barnard', 'North Hero', 'Huntington', 'Orange', 'Shaftsbury', 'Berkshire', 'Thetford', 'Chittenden County', 'Hubbardton', 'Braintree', 'Mendon', 'Cavendish', 'Dover', 'Morgan', 'Barre Town', 'Roxbury', 'Norton', 'Woodford', 'Eden', 'Holland', 'Ludlow', 'Putney', 'Fayston', 'Glover', 'Chittenden', 'Hardwick', 'St. Johnsbury', 'Albany', 'Brighton', 'Fair Haven', 'Burke', 'Windham', 'Troy', 'Coventry', 'Irasburg', 'Pomfret', 'Richford', 'Shrewsbury', 'Swanton', 'Wardsboro', 'Reading', 'Bethel', 'Bradford', 'Stowe', 'Killington', 'Maidstone', 'Rutland County', 'Charleston', 'Marlboro', 'Lowell', 'Hartland', 'Sheffield', 'Fairlee', 'Proctor', 'Brownington', 'Rockingham', 'Montpelier', 'Alburgh', 'Winhall', 'Castleton', 'Windsor County', 'Waterford', 'Ryegate', 'West Fairlee', 'Westford', 'Manchester', 'Granville', 'Bridgewater', 'Whiting', 'Johnson', 'Baltimore', 'Bennington', 'Wilmington', 'Highgate', 'Addison County', 'Washington', 'East Haven', 'Landgrove', 'Stannard', 'Cornwall', 'Ferrisburg', 'Jamaica', 'Calais', 'Sheldon', 'Halifax', 'Canaan', 'Strafford', 'Monkton', 'Newark', 'Grafton', 'Bennington County', 'Essex County', 'Groton', 'Hinesburg', 'Newport', 'Panton', 'Stamford', 'Barton', 'Hyde Park', 'New Haven', 'Westminster', 'Ira', 'Ripton', 'Sutton', 'Vernon', 'Danby', 'Londonderry', 'Randolph', 'Vershire', 'Cambridge', 'Readsboro', 'Waterbury', 'Orwell', 'Caledonia County', 'Starksboro', 'Georgia', 'Wolcott', 'Danville', 'Shelburne', 'Sunderland', 'Marshfield', 'West Windsor', 'Windham County', 'St. George', 'Andover', 'Fairfax', 'Arlington', 'Athens', 'Hancock', 'Wells', 'Waterville', 'Sudbury', 'Kirby', 'Shoreham', 'Stockbridge', 'Rutland', 'Bristol', 'Rochester', 'Plymouth', 'Royalton', 'Westfield', 'Dorset', 'Lincoln', 'Waltham', 'Weybridge', 'Williston', 'Lunenburg', 'Barnet', 'Moretown', 'Clarendon', 'Bridport', 'Orleans County', 'Springfield', 'Enosburgh', 'Westmore', 'Franklin', 'Victory', 'Weathersfield', 'Richmond', 'Derby', 'Pittsfield', 'Plainfield', 'Milton', 'Bloomfield', 'Brattleboro', 'Brunswick']

Missouri discrepancies can be fixed by renaming the data and the discrepancies in New Hampshire and Vermont will be fixed using the city_county dataset

In [ ]:
governors_merge_data['county'] = governors_merge_data['county'].apply(lambda x: x.replace(' city', ' City'))
governors_covid_merge_dataset['County_Name'] = governors_covid_merge_dataset['County_Name'].apply(lambda x: x.replace(' city', ' City'))

In [ ]:
# State Missouri has discrepancies
# ['Jackson County', 'Jackson County (including other portions of Kansas City)', 'St. Louis city', 'City of St. Louis']
idx = governors_covid_merge_dataset.index[governors_covid_merge_dataset['County_Name'].str.contains('including')]
governors_covid_merge_dataset.loc[idx,'County_Name'] = 'Jackson County'

In [ ]:
idx = governors_covid_merge_dataset.index[governors_covid_merge_dataset['County_Name']=='City of St. Louis']
governors_covid_merge_dataset.loc[idx,'County_Name'] = 'St. Louis City' # Using uppercase C since we already transformed City values

In [ ]:
# Rest of all states whose data has city names are
# New Hampshire, Vermont
def transform_county_names2(x):
  if x['state'] in ['New Hampshire', 'Vermont']:
    output = city_county_dataset[(city_county_dataset['State'] == x['state']) & (city_county_dataset['City'] == x['county'])]['County']
    x['county'] = output.item() if len(output)==1 else x['county']
  return x

In [ ]:
governors_merge_data = governors_merge_data.apply(transform_county_names2, axis=1)

In [ ]:
governors_merge_data.head()

,state,county,current_votes,total_votes,percent,candidate,party,Winner_Votes,won
0,Delaware,Kent County,85415,87025,100,John Carney,DEM,44352,True
1,Delaware,New Castle County,280039,287633,100,John Carney,DEM,191678,True
2,Delaware,Sussex County,127181,129352,100,Julianne Murray,REP,68435,True
3,Indiana,Adams County,14154,14209,100,Eric Holcomb,REP,9441,True
4,Indiana,Allen County,168312,169082,100,Eric Holcomb,REP,98406,True

Adding the votes for a candidate from different cities to their grouped county

In [ ]:
governors_merge_data = governors_merge_data.groupby(by=['state','county','candidate','party','won']).sum().reset_index()

In [ ]:
governors_merge_data[governors_merge_data['state']=='Vermont']

,state,county,candidate,party,won,current_votes,total_votes,percent,Winner_Votes
464,Vermont,Addison County,Phil Scott,REP,True,21867,22031,2300,15034
465,Vermont,Bennington County,Phil Scott,REP,True,20007,20377,1595,12053
466,Vermont,Caledonia County,Phil Scott,REP,True,15973,16169,1700,11701
467,Vermont,Chittenden County,David Zuckerman,DEM,True,21721,22218,100,10600
468,Vermont,Chittenden County,Phil Scott,REP,True,75894,76699,1600,54364
469,Vermont,Essex County,Phil Scott,REP,True,3181,3290,1300,2408
470,Vermont,Franklin County,Phil Scott,REP,True,25649,25537,1495,20095
471,Vermont,Grand Isle County,Phil Scott,REP,True,4824,4851,500,3755
472,Vermont,Lamoille County,Phil Scott,REP,True,14816,14916,1000,10695
473,Vermont,Orange County,Phil Scott,REP,True,16999,17153,1695,12174
474,Vermont,Orleans County,Phil Scott,REP,True,13851,14061,1895,10291
475,Vermont,Rutland County,Phil Scott,REP,True,33530,33973,2795,24588
476,Vermont,Washington County,Phil Scott,REP,True,35016,35312,2000,24188
477,Vermont,Windham County,David Zuckerman,DEM,True,8605,8824,300,4437
478,Vermont,Windham County,Phil Scott,REP,True,16894,17219,1900,10079
479,Vermont,Windsor County,Phil Scott,REP,True,33884,34446,2400,22737

Removing the duplicates created due to merging of the cities into counties

In [ ]:
def get_winner_and_merged_votes2(row):
  if row['state'] in ['New Hampshire', 'Vermont']:
    slice_df = governors_merge_data[(governors_merge_data['state']==row['state'])&(governors_merge_data['county']==row['county'])]
    if len(slice_df) > 1:
      winner_row_idx = governors_merge_data[(governors_merge_data['state']==row['state'])&(governors_merge_data['county']==row['county'])]['Winner_Votes'].idxmax()
      return governors_merge_data.loc[winner_row_idx]
  return row

In [ ]:
governors_merge_data = governors_merge_data.apply(get_winner_and_merged_votes2, axis=1)
governors_merge_data.drop_duplicates(inplace=True)

In [ ]:
governors_merge_data.head()

,state,county,candidate,party,won,current_votes,total_votes,percent,Winner_Votes
0,Delaware,Kent County,John Carney,DEM,True,85415,87025,100,44352
1,Delaware,New Castle County,John Carney,DEM,True,280039,287633,100,191678
2,Delaware,Sussex County,Julianne Murray,REP,True,127181,129352,100,68435
3,Indiana,Adams County,Eric Holcomb,REP,True,14154,14209,100,9441
4,Indiana,Allen County,Eric Holcomb,REP,True,168312,169082,100,98406

In [ ]:
governors_merge_data[governors_merge_data.duplicated(['state','county','candidate'])]

Empty DataFrame
Columns: [state, county, candidate, party, won, current_votes, total_votes, percent, Winner_Votes]
Index: []

In [ ]:
governors_merge_data.shape

(566, 9)

In [ ]:
governors_covid_merge_dataset.shape

(566, 6)

As the shapes matched checking for the discrepancies again

In [ ]:
for state in covid_state_list:
  output = get_different_county_names_governor(state)
  if len(output)>0:
    print(f"State {state} has discrepancies")
    print(output)

No Discrepancies

In [ ]:
# Transforming the percent column
governors_merge_data['percent'] = round((governors_merge_data['current_votes']/governors_merge_data['total_votes'])*100,2)

In [ ]:
governors_merge_data[governors_merge_data['state']=='New Hampshire']

,state,county,candidate,party,won,current_votes,total_votes,percent,Winner_Votes
266,New Hampshire,Belknap County,Chris Sununu,REP,True,38079,38453,99.03,28074
267,New Hampshire,Carroll County,Chris Sununu,REP,True,32117,32509,98.79,21791
269,New Hampshire,Cheshire County,Chris Sununu,REP,True,29425,30027,98.00,18156
271,New Hampshire,Coos County,Chris Sununu,REP,True,16348,16539,98.85,11409
272,New Hampshire,Grafton County,Chris Sununu,REP,True,36869,37374,98.65,23543
274,New Hampshire,Hillsborough County,Chris Sununu,REP,True,220716,225473,97.89,147642
276,New Hampshire,Merrimack County,Chris Sununu,REP,True,89019,89910,99.01,56266
277,New Hampshire,Rockingham County,Chris Sununu,REP,True,182514,184504,98.92,127431
279,New Hampshire,Strafford County,Chris Sununu,REP,True,65118,65946,98.74,41522
281,New Hampshire,Sullivan County,Chris Sununu,REP,True,24107,24415,98.74,15872

### Merged Governor and covid dataset

In [ ]:
governors_covid_merged = pd.merge(governors_covid_merge_dataset,governors_merge_data,how='left',left_on=['County_Name','State'],right_on=['county','state'])
governors_covid_merged.drop(columns=['county','state'],inplace=True)
governors_covid_merged.head()

,countyFIPS,County_Name,State,population,Total_Covid_Cases_Till_Election,Total_Covid_Deaths_Till_Election,candidate,party,won,current_votes,total_votes,percent,Winner_Votes
0,10001,Kent County,Delaware,180786,3570.0,121.0,John Carney,DEM,True,85415,87025,98.15,44352
1,10003,New Castle County,Delaware,558753,13186.0,353.0,John Carney,DEM,True,280039,287633,97.36,191678
2,10005,Sussex County,Delaware,234225,8099.0,235.0,Julianne Murray,REP,True,127181,129352,98.32,68435
3,18001,Adams County,Indiana,35777,972.0,9.0,Eric Holcomb,REP,True,14154,14209,99.61,9441
4,18003,Allen County,Indiana,379299,9523.0,248.0,Eric Holcomb,REP,True,168312,169082,99.54,98406

In [ ]:
governors_covid_merged.shape

(566, 13)

### Preparing House Data for Merge

In [ ]:
house_candidate.head()

                 district             candidate party  total_votes    won
0       Delaware at large  Lisa Blunt Rochester   DEM       281382   True
1       Delaware at large            Lee Murphy   REP       196392  False
2       Delaware at large     Catherine Purcell   IND         6682  False
3       Delaware at large          David Rogers   LIB         3814  False
4  Florida’s 1st district            Matt Gaetz   REP       283352   True

In [ ]:
house_state.head()

                 district  current_votes  total_votes  percent
0       Delaware at large         488270       488270      100
1  Florida’s 1st district         438562       438562      100
2  Florida’s 2nd district         311999       311999      100
3  Florida’s 3rd district         390401       390401      100
4  Florida’s 4th district         504940       504940      100

In [ ]:
house_state.district.nunique()

436

The House of Representatives is elected at Congressional District level all over the 50 states. Each congressional district consists of couple of counties. Some may have parts of counties or cities in them. So it is difficult to either divide the districts to counties or join counties data to form district. So House Election data will be analyzed at state level for the simplicity

In [ ]:
#Merging the data to statewide
house_state.district.unique()

array(['Delaware at large', 'Florida’s 1st district',
       'Florida’s 2nd district', 'Florida’s 3rd district',
       'Florida’s 4th district', 'Florida’s 5th district',
       'Florida’s 6th district', 'Florida’s 7th district',
       'Florida’s 8th district', 'Florida’s 9th district',
       'Florida’s 10th district', 'Florida’s 11th district',
       'Florida’s 12th district', 'Florida’s 13th district',
       'Florida’s 14th district', 'Florida’s 15th district',
       'Florida’s 16th district', 'Florida’s 17th district',
       'Florida’s 18th district', 'Florida’s 19th district',
       'Florida’s 20th district', 'Florida’s 21st district',
       'Florida’s 22nd district', 'Florida’s 23rd district',
       'Florida’s 24th district', 'Florida’s 25th district',
       'Florida’s 26th district', 'Florida’s 27th district',
       'Georgia’s 1st district', 'Georgia’s 2nd district',
       'Georgia’s 3rd district', 'Georgia’s 4th district',
       'Georgia’s 5th district', 'Georgia’s 6th district',
       'Georgia’s 7th district', 'Georgia’s 8th district',
       'Georgia’s 9th district', 'Georgia’s 10th district',
       'Georgia’s 11th district', 'Georgia’s 12th district',
       'Georgia’s 13th district', 'Georgia’s 14th district',
       'Hawaii’s 1st district', 'Hawaii’s 2nd district',
       'Idaho’s 1st district', 'Idaho’s 2nd district',
       'Illinois’s 1st district', 'Illinois’s 2nd district',
       'Illinois’s 3rd district', 'Illinois’s 4th district',
       'Illinois’s 5th district', 'Illinois’s 6th district',
       'Illinois’s 7th district', 'Illinois’s 8th district',
       'Illinois’s 9th district', 'Illinois’s 10th district',
       'Illinois’s 11th district', 'Illinois’s 12th district',
       'Illinois’s 13th district', 'Illinois’s 14th district',
       'Illinois’s 15th district', 'Illinois’s 16th district',
       'Illinois’s 17th district', 'Illinois’s 18th district',
       'Indiana’s 1st district', 'Indiana’s 2nd district',
       'Indiana’s 3rd district', 'Indiana’s 4th district',
       'Indiana’s 5th district', 'Indiana’s 6th district',
       'Indiana’s 7th district', 'Indiana’s 8th district',
       'Indiana’s 9th district', 'Iowa’s 1st district',
       'Iowa’s 2nd district', 'Iowa’s 3rd district',
       'Iowa’s 4th district', 'Kansas’s 1st district',
       'Kansas’s 2nd district', 'Kansas’s 3rd district',
       'Kansas’s 4th district', 'Kentucky’s 1st district',
       'Kentucky’s 2nd district', 'Kentucky’s 3rd district',
       'Kentucky’s 4th district', 'Kentucky’s 5th district',
       'Kentucky’s 6th district', 'Louisiana’s 1st district',
       'Louisiana’s 2nd district', 'Louisiana’s 3rd district',
       'Louisiana’s 4th district', 'Louisiana’s 5th district',
       'Louisiana’s 6th district', 'Maine’s 1st district',
       'Maine’s 2nd district', 'Maryland’s 1st district',
       'Maryland’s 2nd district', 'Maryland’s 3rd district',
       'Maryland’s 4th district', 'Maryland’s 5th district',
       'Maryland’s 6th district', 'Maryland’s 7th district',
       'Maryland’s 8th district', 'Massachusetts’s 1st district',
       'Massachusetts’s 2nd district', 'Massachusetts’s 3rd district',
       'Massachusetts’s 4th district', 'Massachusetts’s 5th district',
       'Massachusetts’s 6th district', 'Massachusetts’s 7th district',
       'Massachusetts’s 8th district', 'Massachusetts’s 9th district',
       'Michigan’s 1st district', 'Michigan’s 2nd district',
       'Michigan’s 3rd district', 'Michigan’s 4th district',
       'Michigan’s 5th district', 'Michigan’s 6th district',
       'Michigan’s 7th district', 'Michigan’s 8th district',
       'Michigan’s 9th district', 'Michigan’s 10th district',
       'Michigan’s 11th district', 'Michigan’s 12th district',
       'Michigan’s 13th district', 'Michigan’s 14th district',
       'Minnesota’s 1st district', 'Minnesota’s 2nd district',
       'Minnesota’s 3rd district', 'Minnesota’s 4th district',
       'Minnesota’s 5th district', 'Minnesota’s 6th district',
       'Minnesota’s 7th district', 'Minnesota’s 8th district',
       'Mississippi’s 1st district', 'Mississippi’s 2nd district',
       'Mississippi’s 3rd district', 'Mississippi’s 4th district',
       'Missouri’s 1st district', 'Missouri’s 2nd district',
       'Missouri’s 3rd district', 'Missouri’s 4th district',
       'Missouri’s 5th district', 'Missouri’s 6th district',
       'Missouri’s 7th district', 'Missouri’s 8th district',
       'Montana at large', 'Nebraska’s 1st district',
       'Nebraska’s 2nd district', 'Nebraska’s 3rd district',
       'Nevada’s 1st district', 'Nevada’s 2nd district',
       'Nevada’s 3rd district', 'Nevada’s 4th district',
       'New Hampshire’s 1st district', 'New Hampshire’s 2nd district',
       'New Jersey’s 1st district', 'New Jersey’s 2nd district',
       'New Jersey’s 3rd district', 'New Jersey’s 4th district',
       'New Jersey’s 5th district', 'New Jersey’s 6th district',
       'New Jersey’s 7th district', 'New Jersey’s 8th district',
       'New Jersey’s 9th district', 'New Jersey’s 10th district',
       'New Jersey’s 11th district', 'New Jersey’s 12th district',
       'New Mexico’s 1st district', 'New Mexico’s 2nd district',
       'New Mexico’s 3rd district', 'New York’s 1st district',
       'New York’s 2nd district', 'New York’s 3rd district',
       'New York’s 4th district', 'New York’s 5th district',
       'New York’s 6th district', 'New York’s 7th district',
       'New York’s 8th district', 'New York’s 9th district',
       'New York’s 10th district', 'New York’s 11th district',
       'New York’s 12th district', 'New York’s 13th district',
       'New York’s 14th district', 'New York’s 15th district',
       'New York’s 16th district', 'New York’s 17th district',
       'New York’s 18th district', 'New York’s 19th district',
       'New York’s 20th district', 'New York’s 21st district',
       'New York’s 22nd district', 'New York’s 23rd district',
       'New York’s 24th district', 'New York’s 25th district',
       'New York’s 26th district', 'New York’s 27th district',
       'North Carolina’s 1st district', 'North Carolina’s 2nd district',
       'North Carolina’s 3rd district', 'North Carolina’s 4th district',
       'North Carolina’s 5th district', 'North Carolina’s 6th district',
       'North Carolina’s 7th district', 'North Carolina’s 8th district',
       'North Carolina’s 9th district', 'North Carolina’s 10th district',
       'North Carolina’s 11th district', 'North Carolina’s 12th district',
       'North Carolina’s 13th district', 'North Dakota at large',
       'Ohio’s 1st district', 'Ohio’s 2nd district',
       'Ohio’s 3rd district', 'Ohio’s 4th district',
       'Ohio’s 5th district', 'Ohio’s 6th district',
       'Ohio’s 7th district', 'Ohio’s 8th district',
       'Ohio’s 9th district', 'Ohio’s 10th district',
       'Ohio’s 11th district', 'Ohio’s 12th district',
       'Ohio’s 13th district', 'Ohio’s 14th district',
       'Ohio’s 15th district', 'Ohio’s 16th district',
       'Oklahoma’s 1st district', 'Oklahoma’s 2nd district',
       'Oklahoma’s 3rd district', 'Oklahoma’s 4th district',
       'Oklahoma’s 5th district', 'Oregon’s 1st district',
       'Oregon’s 2nd district', 'Oregon’s 3rd district',
       'Oregon’s 4th district', 'Oregon’s 5th district',
       'Pennsylvania’s 1st district', 'Pennsylvania’s 2nd district',
       'Pennsylvania’s 3rd district', 'Pennsylvania’s 4th district',
       'Pennsylvania’s 5th district', 'Pennsylvania’s 6th district',
       'Pennsylvania’s 7th district', 'Pennsylvania’s 8th district',
       'Pennsylvania’s 9th district', 'Pennsylvania’s 10th district',
       'Pennsylvania’s 11th district', 'Pennsylvania’s 12th district',
       'Pennsylvania’s 13th district', 'Pennsylvania’s 14th district',
       'Pennsylvania’s 15th district', 'Pennsylvania’s 16th district',
       'Pennsylvania’s 17th district', 'Pennsylvania’s 18th district',
       'Rhode Island’s 1st district', 'Rhode Island’s 2nd district',
       'South Carolina’s 1st district', 'South Carolina’s 2nd district',
       'South Carolina’s 3rd district', 'South Carolina’s 4th district',
       'South Carolina’s 5th district', 'South Carolina’s 6th district',
       'South Carolina’s 7th district', 'South Dakota at large',
       'Tennessee’s 1st district', 'Tennessee’s 2nd district',
       'Tennessee’s 3rd district', 'Tennessee’s 4th district',
       'Tennessee’s 5th district', 'Tennessee’s 6th district',
       'Tennessee’s 7th district', 'Tennessee’s 8th district',
       'Tennessee’s 9th district', 'Texas’s 1st district',
       'Texas’s 2nd district', 'Texas’s 3rd district',
       'Texas’s 4th district', 'Texas’s 5th district',
       'Texas’s 6th district', 'Texas’s 7th district',
       'Texas’s 8th district', 'Texas’s 9th district',
       'Texas’s 10th district', 'Texas’s 11th district',
       'Texas’s 12th district', 'Texas’s 13th district',
       'Texas’s 14th district', 'Texas’s 15th district',
       'Texas’s 16th district', 'Texas’s 17th district',
       'Texas’s 18th district', 'Texas’s 19th district',
       'Texas’s 20th district', 'Texas’s 21st district',
       'Texas’s 22nd district', 'Texas’s 23rd district',
       'Texas’s 24th district', 'Texas’s 25th district',
       'Texas’s 26th district', 'Texas’s 27th district',
       'Texas’s 28th district', 'Texas’s 29th district',
       'Texas’s 30th district', 'Texas’s 31st district',
       'Texas’s 32nd district', 'Texas’s 33rd district',
       'Texas’s 34th district', 'Texas’s 35th district',
       'Texas’s 36th district', 'Utah’s 1st district',
       'Utah’s 2nd district', 'Utah’s 3rd district',
       'Utah’s 4th district', 'Vermont at large',
       'Virginia’s 1st district', 'Virginia’s 2nd district',
       'Virginia’s 3rd district', 'Virginia’s 4th district',
       'Virginia’s 5th district', 'Virginia’s 6th district',
       'Virginia’s 7th district', 'Virginia’s 8th district',
       'Virginia’s 9th district', 'Virginia’s 10th district',
       'Virginia’s 11th district', 'Washington’s 1st district',
       'Washington’s 2nd district', 'Washington’s 3rd district',
       'Washington’s 4th district', 'Washington’s 5th district',
       'Washington’s 6th district', 'Washington’s 7th district',
       'Washington’s 8th district', 'Washington’s 9th district',
       'Washington’s 10th district', 'West Virginia’s 1st district',
       'West Virginia’s 2nd district', 'West Virginia’s 3rd district',
       'Wisconsin’s 1st district', 'Wisconsin’s 2nd district',
       'Wisconsin’s 3rd district', 'Wisconsin’s 4th district',
       'Wisconsin’s 5th district', 'Wisconsin’s 6th district',
       'Wisconsin’s 7th district', 'Wisconsin’s 8th district',
       'Wyoming at large', 'Alabama’s 1st district',
       'Alabama’s 2nd district', 'Alabama’s 3rd district',
       'Alabama’s 4th district', 'Alabama’s 5th district',
       'Alabama’s 6th district', 'Alabama’s 7th district',
       'Alaska at large', 'Arizona’s 1st district',
       'Arizona’s 2nd district', 'Arizona’s 3rd district',
       'Arizona’s 4th district', 'Arizona’s 5th district',
       'Arizona’s 6th district', 'Arizona’s 7th district',
       'Arizona’s 8th district', 'Arizona’s 9th district',
       'Arkansas’s 1st district', 'Arkansas’s 2nd district',
       'Arkansas’s 3rd district', 'Arkansas’s 4th district',
       'California’s 10th district', 'California’s 11th district',
       'California’s 12th district', 'California’s 13th district',
       'California’s 14th district', 'California’s 15th district',
       'California’s 16th district', 'California’s 17th district',
       'California’s 18th district', 'California’s 19th district',
       'California’s 1st district', 'California’s 20th district',
       'California’s 22nd district', 'California’s 23rd district',
       'California’s 24th district', 'California’s 26th district',
       'California’s 27th district', 'California’s 28th district',
       'California’s 29th district', 'California’s 2nd district',
       'California’s 30th district', 'California’s 31st district',
       'California’s 32nd district', 'California’s 33rd district',
       'California’s 34th district', 'California’s 35th district',
       'California’s 36th district', 'California’s 37th district',
       'California’s 38th district', 'California’s 3rd district',
       'California’s 40th district', 'California’s 41st district',
       'California’s 42nd district', 'California’s 43rd district',
       'California’s 44th district', 'California’s 45th district',
       'California’s 46th district', 'California’s 47th district',
       'California’s 48th district', 'California’s 49th district',
       'California’s 4th district', 'California’s 50th district',
       'California’s 51st district', 'California’s 52nd district',
       'California’s 53rd district', 'California’s 5th district',
       'California’s 6th district', 'California’s 7th district',
       'California’s 8th district', 'California’s 9th district',
       'Colorado’s 1st district', 'Colorado’s 2nd district',
       'Colorado’s 3rd district', 'Colorado’s 4th district',
       'Colorado’s 5th district', 'Colorado’s 6th district',
       'Colorado’s 7th district', 'Connecticut’s 1st district',
       'Connecticut’s 2nd district', 'Connecticut’s 3rd district',
       'Connecticut’s 4th district', 'Connecticut’s 5th district',
       'United States’s 0th district', 'California’s 21st district',
       'California’s 25th district', 'California’s 39th district'],
      dtype=object)

After observing the above data, the district names either have the words **'s district number or at large ** after the state_name. So let us extract the state name from the data and sum the metrics of a state to get the state wide results

In [ ]:
house_merge_data = house_state.copy()

In [ ]:
house_merge_data.head()

                 district  current_votes  total_votes  percent
0       Delaware at large         488270       488270      100
1  Florida’s 1st district         438562       438562      100
2  Florida’s 2nd district         311999       311999      100
3  Florida’s 3rd district         390401       390401      100
4  Florida’s 4th district         504940       504940      100

In [ ]:
def get_state_name(row):
  if "’s" in row['district']:
    state_name = row['district'].split("’")[0]
  else:
    state_name = row['district'].split(" at")[0]
  row['district'] = state_name
  return row

In [ ]:
house_merge_data = house_merge_data.apply(get_state_name,axis=1)

In [ ]:
house_merge_data.shape

(436, 4)

Senate has 435 seats. In the above data we got 436 rows. We can see data for Whole United States as well. So deleting the row

In [ ]:
us_index = house_merge_data.index[house_merge_data.district.str.contains('United States')].item()

In [ ]:
house_merge_data = house_merge_data.drop(index=us_index, axis=1)

In [ ]:
house_merge_data.shape

(435, 4)

In [ ]:
house_merge_data.head()

   district  current_votes  total_votes  percent
0  Delaware         488270       488270      100
1   Florida         438562       438562      100
2   Florida         311999       311999      100
3   Florida         390401       390401      100
4   Florida         504940       504940      100

Now let us aggregate the current_votes and total_votes for a state

In [ ]:
house_merge_data = house_merge_data.groupby(by='district').aggregate({"current_votes": sum,'total_votes':sum}).reset_index()

In [ ]:
col_names = list(house_merge_data.columns)

In [ ]:
col_names

['district', 'current_votes', 'total_votes']

In [ ]:
col_names[0] = 'state'

In [ ]:
house_merge_data.columns = col_names

In [ ]:
house_merge_data.head()

        state  current_votes  total_votes
0     Alabama        2033209      2033209
1      Alaska         353165       353165
2     Arizona        3268249      3268249
3    Arkansas        1179396      1179396
4  California       16723953     16723953

In [ ]:
house_candidate.head()

                 district             candidate party  total_votes    won
0       Delaware at large  Lisa Blunt Rochester   DEM       281382   True
1       Delaware at large            Lee Murphy   REP       196392  False
2       Delaware at large     Catherine Purcell   IND         6682  False
3       Delaware at large          David Rogers   LIB         3814  False
4  Florida’s 1st district            Matt Gaetz   REP       283352   True

Let us reapply the district to state transformation function to the house_candidate data as well

In [ ]:
house_merge_candidate = house_candidate.copy()

In [ ]:
house_merge_candidate = house_merge_candidate.apply(get_state_name,axis=1)

In [ ]:
house_merge_candidate.head()

   district             candidate party  total_votes    won
0  Delaware  Lisa Blunt Rochester   DEM       281382   True
1  Delaware            Lee Murphy   REP       196392  False
2  Delaware     Catherine Purcell   IND         6682  False
3  Delaware          David Rogers   LIB         3814  False
4   Florida            Matt Gaetz   REP       283352   True

Let us add a column to house merge data to get number of districts for a given state

In [ ]:
def get_district_count(state_name):
  return len(house_state[house_state.district.str.contains(state_name)])

In [ ]:
house_merge_data['district_count'] = house_merge_data.state.apply(get_district_count)

In [ ]:
house_merge_data.head()

        state  current_votes  total_votes  district_count
0     Alabama        2033209      2033209               7
1      Alaska         353165       353165               1
2     Arizona        3268249      3268249               9
3    Arkansas        1179396      1179396               4
4  California       16723953     16723953              53

Let us join the candidate data to this merge data through columns of Number of wins by a party in the state (We consider Democratic party, Republic Party and Independent Party) wins and their vote share in the state

In [ ]:
def get_each_party_win_count_vote_share(data):
  state_name = data['state']
  state_summary_df = house_merge_candidate[house_merge_candidate.district.str.contains(state_name)].groupby(
                          by='party').aggregate({"won":sum,"total_votes":sum}).reset_index()
  output = {}
  for label, row in state_summary_df.iterrows():
    if row['party'] == 'DEM':
      data['dem_win'] = row['won']
      data['dem_total_votes'] = row['total_votes']
    elif row['party'] == 'REP':
      data['rep_win'] = row['won']
      data['rep_total_votes'] = row['total_votes']
    else:
      data['oth_win'] = row['won']
      data['oth_total_votes'] = row['total_votes']
  return data

In [ ]:
house_merge_data = house_merge_data.apply(get_each_party_win_count_vote_share,axis=1)
house_merge_data.head()

,current_votes,dem_total_votes,dem_win,district_count,oth_total_votes,oth_win,rep_total_votes,rep_win,state,total_votes
0,2033209,608809.0,1.0,7,8388.0,0.0,1416012,6,Alabama,2033209
1,353165,159856.0,0.0,1,1183.0,0.0,192126,1,Alaska,353165
2,3268249,1629318.0,5.0,9,415.0,0.0,1638516,4,Arizona,3268249
3,1179396,330485.0,0.0,4,20645.0,0.0,828266,4,Arkansas,1179396
4,16723953,11083738.0,42.0,53,NaN,NaN,5640215,11,California,16723953

In [ ]:
#Formatting column order
columns_order = ['state','total_votes','current_votes','district_count','dem_win','dem_total_votes','rep_win','rep_total_votes','oth_win','oth_total_votes']
house_merge_data = house_merge_data[columns_order]
house_merge_data.head()

,state,total_votes,current_votes,district_count,dem_win,dem_total_votes,rep_win,rep_total_votes,oth_win,oth_total_votes
0,Alabama,2033209,2033209,7,1.0,608809.0,6,1416012,0.0,8388.0
1,Alaska,353165,353165,1,0.0,159856.0,1,192126,0.0,1183.0
2,Arizona,3268249,3268249,9,5.0,1629318.0,4,1638516,0.0,415.0
3,Arkansas,1179396,1179396,4,0.0,330485.0,4,828266,0.0,20645.0
4,California,16723953,16723953,53,42.0,11083738.0,11,5640215,NaN,NaN

There are NaN values where the party didn't participate. Let us replace those values with 0

In [ ]:
#Replace Nan with zero
house_merge_data.fillna(0,inplace=True)
house_merge_data.head()

,state,total_votes,current_votes,district_count,dem_win,dem_total_votes,rep_win,rep_total_votes,oth_win,oth_total_votes
0,Alabama,2033209,2033209,7,1.0,608809.0,6,1416012,0.0,8388.0
1,Alaska,353165,353165,1,0.0,159856.0,1,192126,0.0,1183.0
2,Arizona,3268249,3268249,9,5.0,1629318.0,4,1638516,0.0,415.0
3,Arkansas,1179396,1179396,4,0.0,330485.0,4,828266,0.0,20645.0
4,California,16723953,16723953,53,42.0,11083738.0,11,5640215,0.0,0.0

In [ ]:
house_merge_data.shape

(50, 10)

In [ ]:
house_merge_data.state.nunique()

50

In [ ]:
house_merge_data.state.unique()

array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
       'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia',
       'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas',
       'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts',
       'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana',
       'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico',
       'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma',
       'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina',
       'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont',
       'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'],
      dtype=object)

There are 50 states data in the house merge data dataframe. Now let us convert the covid data to state wide data so that we can merge both these datasets

In [ ]:
merge_covid_dataset.head()

,countyFIPS,County_Name,State,population,Total_Covid_Cases_Till_Election,Total_Covid_Deaths_Till_Election
0,1001,Autauga County,Alabama,55869,2159.0,30.0
1,1003,Baldwin County,Alabama,223234,6940.0,71.0
2,1005,Barbour County,Alabama,24686,1060.0,9.0
3,1007,Bibb County,Alabama,22394,873.0,15.0
4,1009,Blount County,Alabama,57826,2074.0,25.0

In [ ]:
merge_covid_dataset.State.nunique()

51

Merge covid dataset has 51 states we need to find out the extra state and remove that row

In [ ]:
merge_covid_dataset.State.unique()

array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
       'Colorado', 'Connecticut', 'Delaware', 'District of Columbia',
       'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana',
       'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
       'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi',
       'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
       'New Jersey', 'New Mexico', 'New York', 'North Carolina',
       'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania',
       'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee',
       'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
       'West Virginia', 'Wisconsin', 'Wyoming'], dtype=object)

District of Columbia is the extra state listed in Covid dataset. Let us remove that record to merge these datasets

In [ ]:
house_merge_covid_data = merge_covid_dataset.copy()

In [ ]:
house_merge_covid_data[house_merge_covid_data.State.str.contains('District')]

,countyFIPS,County_Name,State,population,Total_Covid_Cases_Till_Election,Total_Covid_Deaths_Till_Election
321,11001,Washington,District of Columbia,705749,17266.0,646.0

In [ ]:
dc_index = house_merge_covid_data.index[house_merge_covid_data.State.str.contains('District')].item()

In [ ]:
house_merge_covid_data = house_merge_covid_data.drop(index=dc_index)

In [ ]:
house_merge_covid_data[house_merge_covid_data.State.str.contains('District')]

Empty DataFrame
Columns: [countyFIPS, County_Name, State, population, Total_Covid_Cases_Till_Election, Total_Covid_Deaths_Till_Election]
Index: []

Since we are focusing only on State wide data, let us drop countyFIPS and County_Name columns

In [ ]:
house_merge_covid_data = house_merge_covid_data.drop(columns=['countyFIPS','County_Name'])

In [ ]:
house_merge_covid_data.head()

,State,population,Total_Covid_Cases_Till_Election,Total_Covid_Deaths_Till_Election
0,Alabama,55869,2159.0,30.0
1,Alabama,223234,6940.0,71.0
2,Alabama,24686,1060.0,9.0
3,Alabama,22394,873.0,15.0
4,Alabama,57826,2074.0,25.0

Aggregating the values for each state

In [ ]:
house_merge_covid_data = house_merge_covid_data.groupby(by='State').sum().reset_index()

In [ ]:
house_merge_covid_data.shape

(50, 4)

In [ ]:
house_merge_covid_data.State.nunique()

50

The number of states match for both covid data and house election data. Merging both dataframes

In [ ]:
house_covid_merged = pd.merge(house_merge_covid_data,house_merge_data,how='left',left_on='State',right_on='state')

In [ ]:
house_covid_merged.head()

,State,population,Total_Covid_Cases_Till_Election,Total_Covid_Deaths_Till_Election,state,total_votes,current_votes,district_count,dem_win,dem_total_votes,rep_win,rep_total_votes,oth_win,oth_total_votes
0,Alabama,4903185,192285.0,2964.0,Alabama,2033209,2033209,7,1.0,608809.0,6,1416012,0.0,8388.0
1,Alaska,731545,15706.0,88.0,Alaska,353165,353165,1,0.0,159856.0,1,192126,0.0,1183.0
2,Arizona,7278717,245946.0,5978.0,Arizona,3268249,3268249,9,5.0,1629318.0,4,1638516,0.0,415.0
3,Arkansas,3017804,110079.0,1924.0,Arkansas,1179396,1179396,4,0.0,330485.0,4,828266,0.0,20645.0
4,California,39512223,954149.0,18241.0,California,16723953,16723953,53,42.0,11083738.0,11,5640215,0.0,0.0

In [ ]:
house_covid_merged = house_covid_merged.drop(columns='state')
house_covid_merged.head()

,State,population,Total_Covid_Cases_Till_Election,Total_Covid_Deaths_Till_Election,total_votes,current_votes,district_count,dem_win,dem_total_votes,rep_win,rep_total_votes,oth_win,oth_total_votes
0,Alabama,4903185,192285.0,2964.0,2033209,2033209,7,1.0,608809.0,6,1416012,0.0,8388.0
1,Alaska,731545,15706.0,88.0,353165,353165,1,0.0,159856.0,1,192126,0.0,1183.0
2,Arizona,7278717,245946.0,5978.0,3268249,3268249,9,5.0,1629318.0,4,1638516,0.0,415.0
3,Arkansas,3017804,110079.0,1924.0,1179396,1179396,4,0.0,330485.0,4,828266,0.0,20645.0
4,California,39512223,954149.0,18241.0,16723953,16723953,53,42.0,11083738.0,11,5640215,0.0,0.0