# STAGE 1: Enrichment Data Set Merges with the Super Covid Dataset

Member: Ashrita Dasari

Description:  In this task, we performing initial merges with the previously made super covid data set, after cleaning all the data.

In [23]:
import pandas as pd
import os

In [29]:
#checking if the path exists for the given link
import os
#"C:\Users\ashdh\Documents\GitHub\Ferocious5_CS605\DATASETS\ENRICHMENT DATASETS\ACSDP1Y2021.DP04-DataHousing.csv"
relative_path = r"..\..\DATASETS\ENRICHMENT DATASETS\Enrichment_Housing1Y2021.csv"

if os.path.exists(relative_path):
    print("The file exists at the specified path.")
else:
    print("The file does not exist at the specified path.")

The file exists at the specified path.

In [30]:
#reading the data for the Enrichment_Housing1Y2021.csv and displaying them
housingEnrichment= pd.read_csv(r"..\..\DATASETS\ENRICHMENT DATASETS\Enrichment_Housing1Y2021.csv", low_memory=False)
housingEnrichment

,GEO_ID,NAME,DP04_0001E,DP04_0001EA,DP04_0001M,DP04_0001MA,DP04_0002E,DP04_0002EA,DP04_0002M,DP04_0002MA,...,DP04_0141PM,DP04_0141PMA,DP04_0142PE,DP04_0142PM,DP04_0142PMA,DP04_0142PEA,DP04_0143PE,DP04_0143PEA,DP04_0143PM,DP04_0143PMA
0,Geography,Geographic Area Name,Estimate!!HOUSING OCCUPANCY!!Total housing units,Annotation of Estimate!!HOUSING OCCUPANCY!!Tot...,Margin of Error!!HOUSING OCCUPANCY!!Total hous...,Annotation of Margin of Error!!HOUSING OCCUPAN...,Estimate!!HOUSING OCCUPANCY!!Total housing uni...,Annotation of Estimate!!HOUSING OCCUPANCY!!Tot...,Margin of Error!!HOUSING OCCUPANCY!!Total hous...,Annotation of Margin of Error!!HOUSING OCCUPAN...,...,Percent Margin of Error!!GROSS RENT AS A PERCE...,Annotation of Percent Margin of Error!!GROSS R...,Percent!!GROSS RENT AS A PERCENTAGE OF HOUSEHO...,Percent Margin of Error!!GROSS RENT AS A PERCE...,Annotation of Percent Margin of Error!!GROSS R...,Annotation of Percent!!GROSS RENT AS A PERCENT...,Percent!!GROSS RENT AS A PERCENTAGE OF HOUSEHO...,Annotation of Percent!!GROSS RENT AS A PERCENT...,Percent Margin of Error!!GROSS RENT AS A PERCE...,Annotation of Percent Margin of Error!!GROSS R...
1,0500000US01003,"Baldwin County, Alabama",128533,NaN,889,NaN,94105,NaN,3462,NaN,...,6,NaN,37.2,9.6,NaN,NaN,(X),(X),(X),(X)
2,0500000US01015,"Calhoun County, Alabama",53211,NaN,656,NaN,44631,NaN,1889,NaN,...,4,NaN,42.6,8,NaN,NaN,(X),(X),(X),(X)
3,0500000US01043,"Cullman County, Alabama",39465,NaN,186,NaN,35131,NaN,1361,NaN,...,4.1,NaN,31.1,10.2,NaN,NaN,(X),(X),(X),(X)
4,0500000US01049,"DeKalb County, Alabama",30774,NaN,204,NaN,24979,NaN,1117,NaN,...,4.6,NaN,42.6,12.7,NaN,NaN,(X),(X),(X),(X)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
837,0500000US72113,"Ponce Municipio, Puerto Rico",65434,NaN,1629,NaN,50007,NaN,1956,NaN,...,6.1,NaN,44,8.6,NaN,NaN,(X),(X),(X),(X)
838,0500000US72127,"San Juan Municipio, Puerto Rico",183964,NaN,2866,NaN,135865,NaN,3463,NaN,...,2.2,NaN,48.9,4.7,NaN,NaN,(X),(X),(X),(X)
839,0500000US72135,"Toa Alta Municipio, Puerto Rico",25754,NaN,883,NaN,20918,NaN,1199,NaN,...,N,N,N,N,N,N,(X),(X),(X),(X)
840,0500000US72137,"Toa Baja Municipio, Puerto Rico",34372,NaN,1042,NaN,28276,NaN,1461,NaN,...,4.5,NaN,44.2,12.2,NaN,NaN,(X),(X),(X),(X)
841,0500000US72139,"Trujillo Alto Municipio, Puerto Rico",28630,NaN,938,NaN,24898,NaN,1268,NaN,...,N,N,N,N,N,N,(X),(X),(X),(X)

In [31]:
#Removing all the null and NaN values and cleaning the data
housingEnrichmentnew = housingEnrichment. dropna(axis=1) . drop(0)
housingEnrichmentnew

,GEO_ID,NAME,DP04_0001E,DP04_0001M,DP04_0002E,DP04_0002M,DP04_0003E,DP04_0003M,DP04_0004E,DP04_0004M,...,DP04_0140PE,DP04_0140PM,DP04_0141PE,DP04_0141PM,DP04_0142PE,DP04_0142PM,DP04_0143PE,DP04_0143PEA,DP04_0143PM,DP04_0143PMA
1,0500000US01003,"Baldwin County, Alabama",128533,889,94105,3462,34428,3410,1.4,0.9,...,5.2,2.9,14.1,6,37.2,9.6,(X),(X),(X),(X)
2,0500000US01015,"Calhoun County, Alabama",53211,656,44631,1889,8580,1750,1.6,1.5,...,8.9,4.8,6.9,4,42.6,8,(X),(X),(X),(X)
3,0500000US01043,"Cullman County, Alabama",39465,186,35131,1361,4334,1350,1.8,2.2,...,11.3,6,4.9,4.1,31.1,10.2,(X),(X),(X),(X)
4,0500000US01049,"DeKalb County, Alabama",30774,204,24979,1117,5795,1105,0.1,0.2,...,13.5,8.9,6.4,4.6,42.6,12.7,(X),(X),(X),(X)
5,0500000US01051,"Elmore County, Alabama",37081,602,32108,1460,4973,1304,1.3,1.6,...,7.4,6.3,4.8,6.3,34.1,11.7,(X),(X),(X),(X)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
837,0500000US72113,"Ponce Municipio, Puerto Rico",65434,1629,50007,1956,15427,1832,1.1,0.8,...,12.4,6,14.5,6.1,44,8.6,(X),(X),(X),(X)
838,0500000US72127,"San Juan Municipio, Puerto Rico",183964,2866,135865,3463,48099,3225,3.1,1,...,11.8,2.9,7.5,2.2,48.9,4.7,(X),(X),(X),(X)
839,0500000US72135,"Toa Alta Municipio, Puerto Rico",25754,883,20918,1199,4836,1007,0.8,0.9,...,N,N,N,N,N,N,(X),(X),(X),(X)
840,0500000US72137,"Toa Baja Municipio, Puerto Rico",34372,1042,28276,1461,6096,1160,1.7,1.1,...,10.8,8.8,4.7,4.5,44.2,12.2,(X),(X),(X),(X)
841,0500000US72139,"Trujillo Alto Municipio, Puerto Rico",28630,938,24898,1268,3732,1149,1.9,1.5,...,N,N,N,N,N,N,(X),(X),(X),(X)

In [32]:
housingEnrichmentnew

,GEO_ID,NAME,DP04_0001E,DP04_0001M,DP04_0002E,DP04_0002M,DP04_0003E,DP04_0003M,DP04_0004E,DP04_0004M,...,DP04_0140PE,DP04_0140PM,DP04_0141PE,DP04_0141PM,DP04_0142PE,DP04_0142PM,DP04_0143PE,DP04_0143PEA,DP04_0143PM,DP04_0143PMA
1,0500000US01003,"Baldwin County, Alabama",128533,889,94105,3462,34428,3410,1.4,0.9,...,5.2,2.9,14.1,6,37.2,9.6,(X),(X),(X),(X)
2,0500000US01015,"Calhoun County, Alabama",53211,656,44631,1889,8580,1750,1.6,1.5,...,8.9,4.8,6.9,4,42.6,8,(X),(X),(X),(X)
3,0500000US01043,"Cullman County, Alabama",39465,186,35131,1361,4334,1350,1.8,2.2,...,11.3,6,4.9,4.1,31.1,10.2,(X),(X),(X),(X)
4,0500000US01049,"DeKalb County, Alabama",30774,204,24979,1117,5795,1105,0.1,0.2,...,13.5,8.9,6.4,4.6,42.6,12.7,(X),(X),(X),(X)
5,0500000US01051,"Elmore County, Alabama",37081,602,32108,1460,4973,1304,1.3,1.6,...,7.4,6.3,4.8,6.3,34.1,11.7,(X),(X),(X),(X)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
837,0500000US72113,"Ponce Municipio, Puerto Rico",65434,1629,50007,1956,15427,1832,1.1,0.8,...,12.4,6,14.5,6.1,44,8.6,(X),(X),(X),(X)
838,0500000US72127,"San Juan Municipio, Puerto Rico",183964,2866,135865,3463,48099,3225,3.1,1,...,11.8,2.9,7.5,2.2,48.9,4.7,(X),(X),(X),(X)
839,0500000US72135,"Toa Alta Municipio, Puerto Rico",25754,883,20918,1199,4836,1007,0.8,0.9,...,N,N,N,N,N,N,(X),(X),(X),(X)
840,0500000US72137,"Toa Baja Municipio, Puerto Rico",34372,1042,28276,1461,6096,1160,1.7,1.1,...,10.8,8.8,4.7,4.5,44.2,12.2,(X),(X),(X),(X)
841,0500000US72139,"Trujillo Alto Municipio, Puerto Rico",28630,938,24898,1268,3732,1149,1.9,1.5,...,N,N,N,N,N,N,(X),(X),(X),(X)

In [33]:
# Removing all the other unwanted columns which may not be usful for us
for col in housingEnrichmentnew.columns:
    if col[-2:-1]=='P' or col[-3:-2]=='P':
        del housingEnrichmentnew[col]
        #print(i)
housingEnrichmentnew

,GEO_ID,NAME,DP04_0001E,DP04_0001M,DP04_0002E,DP04_0002M,DP04_0003E,DP04_0003M,DP04_0004E,DP04_0004M,...,DP04_0139E,DP04_0139M,DP04_0140E,DP04_0140M,DP04_0141E,DP04_0141M,DP04_0142E,DP04_0142M,DP04_0143E,DP04_0143M
1,0500000US01003,"Baldwin County, Alabama",128533,889,94105,3462,34428,3410,1.4,0.9,...,2688,1043,990,541,2673,1212,7075,2287,3703,1428
2,0500000US01015,"Calhoun County, Alabama",53211,656,44631,1889,8580,1750,1.6,1.5,...,848,535,984,535,761,444,4711,1162,1105,442
3,0500000US01043,"Cullman County, Alabama",39465,186,35131,1361,4334,1350,1.8,2.2,...,1242,672,787,448,341,300,2173,848,1458,690
4,0500000US01049,"DeKalb County, Alabama",30774,204,24979,1117,5795,1105,0.1,0.2,...,290,185,623,434,297,219,1967,722,694,335
5,0500000US01051,"Elmore County, Alabama",37081,602,32108,1460,4973,1304,1.3,1.6,...,1321,952,588,495,384,503,2720,1086,1130,705
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
837,0500000US72113,"Ponce Municipio, Puerto Rico",65434,1629,50007,1956,15427,1832,1.1,0.8,...,556,444,1077,565,1268,503,3838,876,5514,1119
838,0500000US72127,"San Juan Municipio, Puerto Rico",183964,2866,135865,3463,48099,3225,3.1,1,...,4131,1092,5189,1410,3285,979,21428,2194,22052,2558
839,0500000US72135,"Toa Alta Municipio, Puerto Rico",25754,883,20918,1199,4836,1007,0.8,0.9,...,N,N,N,N,N,N,N,N,N,N
840,0500000US72137,"Toa Baja Municipio, Puerto Rico",34372,1042,28276,1461,6096,1160,1.7,1.1,...,609,364,431,362,189,183,1768,649,3666,811
841,0500000US72139,"Trujillo Alto Municipio, Puerto Rico",28630,938,24898,1268,3732,1149,1.9,1.5,...,N,N,N,N,N,N,N,N,N,N

In [17]:
# Keeping only the data thats required and removing all other columns
housingEnrichmentnew1 = housingEnrichmentnew.loc[:, (
'GEO_ID',
'NAME',
'DP04_0001E',
'DP04_0001M',
'DP04_0002E',
'DP04_0002M',
'DP04_0003E',
'DP04_0003M',
'DP04_0004E',
'DP04_0004M',
'DP04_0005E',
'DP04_0005M',
'DP04_0006E',
'DP04_0006M',
'DP04_0007E',
'DP04_0007M',
'DP04_0008E',
'DP04_0008M',
'DP04_0009E',
'DP04_0009M',
'DP04_0010E',
'DP04_0010M',
'DP04_0011E',
'DP04_0011M',
'DP04_0012E',
'DP04_0012M',
'DP04_0013E',
'DP04_0013M',
'DP04_0014E',
'DP04_0014M',
'DP04_0015E',
'DP04_0015M',
'DP04_0027E',
'DP04_0027M',
'DP04_0028E',
'DP04_0028M',
'DP04_0029E',
'DP04_0029M',
'DP04_0030E',
'DP04_0030M',
'DP04_0031E',
'DP04_0031M',
'DP04_0032E',
'DP04_0032M',
'DP04_0033E',
'DP04_0033M',
'DP04_0034E',
'DP04_0034M',
'DP04_0035E',
'DP04_0035M',
'DP04_0036E',
'DP04_0036M',
'DP04_0037E',
'DP04_0037M',
'DP04_0038E',
'DP04_0038M',
'DP04_0039E',
'DP04_0039M',
'DP04_0040E',
'DP04_0040M',
'DP04_0041E',
'DP04_0041M',
'DP04_0042E',
'DP04_0042M',
'DP04_0043E',
'DP04_0043M',
'DP04_0044E',
'DP04_0044M',
'DP04_0045E',
'DP04_0045M',
'DP04_0046E',
'DP04_0046M',
'DP04_0047E',
'DP04_0047M',
'DP04_0048E',
'DP04_0048M',
'DP04_0049E',
'DP04_0049M',
'DP04_0050E',
'DP04_0050M',
'DP04_0051E',
'DP04_0051M',
'DP04_0052E',
'DP04_0052M',
'DP04_0053E',
'DP04_0053M',
'DP04_0054E',
'DP04_0054M',
'DP04_0055E',
'DP04_0055M',
'DP04_0056E',
'DP04_0056M',
'DP04_0057E',
'DP04_0057M',
'DP04_0058E',
'DP04_0058M',
'DP04_0059E',
'DP04_0059M',
'DP04_0060E',
'DP04_0060M',
'DP04_0061E',
'DP04_0061M',
'DP04_0076E',
'DP04_0076M',
'DP04_0077E',
'DP04_0077M',
'DP04_0078E',
'DP04_0078M',
'DP04_0079E',
'DP04_0079M') ]

housingEnrichmentnew1

,GEO_ID,NAME,DP04_0001E,DP04_0001M,DP04_0002E,DP04_0002M,DP04_0003E,DP04_0003M,DP04_0004E,DP04_0004M,...,DP04_0061E,DP04_0061M,DP04_0076E,DP04_0076M,DP04_0077E,DP04_0077M,DP04_0078E,DP04_0078M,DP04_0079E,DP04_0079M
1,0500000US01003,"Baldwin County, Alabama",128533,889,94105,3462,34428,3410,1.4,0.9,...,21901,2769,94105,3462,92836,3510,1269,786,0,216
2,0500000US01015,"Calhoun County, Alabama",53211,656,44631,1889,8580,1750,1.6,1.5,...,13044,1906,44631,1889,43578,1946,760,538,293,329
3,0500000US01043,"Cullman County, Alabama",39465,186,35131,1361,4334,1350,1.8,2.2,...,12253,1563,35131,1361,34290,1401,587,395,254,283
4,0500000US01049,"DeKalb County, Alabama",30774,204,24979,1117,5795,1105,0.1,0.2,...,7828,1197,24979,1117,23889,1261,944,558,146,155
5,0500000US01051,"Elmore County, Alabama",37081,602,32108,1460,4973,1304,1.3,1.6,...,10731,1376,N,N,N,N,N,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
837,0500000US72113,"Ponce Municipio, Puerto Rico",65434,1629,50007,1956,15427,1832,1.1,0.8,...,6260,1305,50007,1956,48688,2048,1202,594,117,141
838,0500000US72127,"San Juan Municipio, Puerto Rico",183964,2866,135865,3463,48099,3225,3.1,1,...,13197,1992,135865,3463,133074,3384,1699,769,1092,466
839,0500000US72135,"Toa Alta Municipio, Puerto Rico",25754,883,20918,1199,4836,1007,0.8,0.9,...,4155,1106,N,N,N,N,N,N,N,N
840,0500000US72137,"Toa Baja Municipio, Puerto Rico",34372,1042,28276,1461,6096,1160,1.7,1.1,...,4994,975,28276,1461,27589,1536,583,319,104,124
841,0500000US72139,"Trujillo Alto Municipio, Puerto Rico",28630,938,24898,1268,3732,1149,1.9,1.5,...,5368,1239,N,N,N,N,N,N,N,N

In [34]:
# Merging the two data sets and displaying them
# reading csv files
data1 = pd.read_csv(r"..\..\DATASETS\SUPER DATASETS\superCovidDS.csv", low_memory=False)
#data2= pd.read_csv(r"..\..\Member\AshritaD\housingEnrichmentnew1.csv", low_memory=False)

#getting the last 5 digits to match the countyfips in covidsuperdata
housingEnrichmentnew1['countyFIPS'] = housingEnrichmentnew1['GEO_ID'].str[-5:]
#print(housingEnrichmentnew1['countyFIPS'])
housingEnrichmentnew1['countyFIPS'] = pd.to_numeric(housingEnrichmentnew1['countyFIPS'])

# using merge function by setting 
output1 = pd.merge(data1, housingEnrichmentnew1,
                   on= ('countyFIPS')
                   )
                   
#displaying result
output1.drop(output1.columns[output1.columns.str.contains('unnamed',case = False)],axis = 1, inplace = True)
output1 = output1.drop('NAME', axis=1)

output1

,countyFIPS,County Name,State,StateFIPS,2020-01-22_x,2020-01-23_x,2020-01-24_x,2020-01-25_x,2020-01-26_x,2020-01-27_x,...,DP04_0061E,DP04_0061M,DP04_0076E,DP04_0076M,DP04_0077E,DP04_0077M,DP04_0078E,DP04_0078M,DP04_0079E,DP04_0079M
0,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,21901,2769,94105,3462,92836,3510,1269,786,0,216
1,1015,Calhoun County,AL,1,0,0,0,0,0,0,...,13044,1906,44631,1889,43578,1946,760,538,293,329
2,1043,Cullman County,AL,1,0,0,0,0,0,0,...,12253,1563,35131,1361,34290,1401,587,395,254,283
3,1049,DeKalb County,AL,1,0,0,0,0,0,0,...,7828,1197,24979,1117,23889,1261,944,558,146,155
4,1051,Elmore County,AL,1,0,0,0,0,0,0,...,10731,1376,N,N,N,N,N,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
825,55133,Waukesha County,WI,55,0,0,0,0,0,0,...,37233,2037,167089,1527,166094,1598,889,548,106,134
826,55139,Winnebago County,WI,55,0,0,0,0,0,0,...,15869,1417,72794,1154,71618,1266,802,404,374,292
827,55141,Wood County,WI,55,0,0,0,0,0,0,...,8060,1234,N,N,N,N,N,N,N,N
828,56021,Laramie County,WY,56,0,0,0,0,0,0,...,11218,1577,N,N,N,N,N,N,N,N
829,56025,Natrona County,WY,56,0,0,0,0,0,0,...,9390,1390,N,N,N,N,N,N,N,N